### ISSUE TITLE
Evaluate if we can update the app to Calcite 1.0 and what may need to be fixed to support it

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solutions-components#108]
From Yelena Kreyndel <ykreyndel@esri.com>:

[Calcite Design System](https://developers.arcgis.com/calcite-design-system/) is moving out of beta and releasing 1.0 next month on Wednesday, January 18. There are a couple of topics we need to bring to your attention in the meantime.  
 
Breaking changes 
Since last month’s beta release we have incorporated many breaking changes and enhancements for inclusion in our 1.0 release. If you or members of your team are using our previous beta version, beta.98, we recommend testing with our [latest npm “next” release](https://www.npmjs.com/package/@esri/calcite-components) this week, or starting next Monday, December 19 with our final beta release, beta.99^. For a list of breaking changes, check out our [CHANGELOG](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#-breaking-changes) and let us know if you find any issues when conducting your testing.

**Comment by jmhauck** [comment]
We've been at 1.x for quite awhile
