### ISSUE TITLE
PN 4.x: Add addressee layer name in the notification list label

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#124]
John,
I am thinking of a scenario where I created two notification lists using two different addressee layers, I used sketch method for slection in both cases without buffer, once I am done it and I looked at the List panel and I see two notifications with very similar label and it seems like they are both based on the same addressee layer showing up in the panel.

![image](https://user-images.githubusercontent.com/10148401/213009648-43e6f34c-803c-48af-92a3-8281467ca3ec.png)

so wondering if we can add 
1) what this addressee layer dropdown functionality is in the Note section or add an info button after addressee layer 
and 2) add Addressee layer name in the notification list label something like the following screenshot

![image](https://user-images.githubusercontent.com/10148401/213023599-d6f48bfe-3130-4577-b77a-370d73fbf344.png)

![image](https://user-images.githubusercontent.com/10148401/213025525-d9b56504-602e-408d-949b-b06f4ac5a820.png)

**Comment by jmhauck** [comment]
@aparveen You can only use one addressee layer. If you change the addressee layer after making a selection the selection geometries will be applied to the new addressee layer. Seems like when the addressee layer is changed a popup type message that would indicate what is about to occur and ask if they would like to proceed may be appropriate here.

**Comment by aparveen** [comment]
> @aparveen You can only use one addressee layer. If you change the addressee layer after making a selection the selection geometries will be applied to the new addressee layer. Seems like when the addressee layer is changed a popup type message that would indicate what is about to occur and ask if they would like to proceed may be appropriate here.

@jmhauck that will work

**Comment by aparveen** [comment]
Verified
