### ISSUE TITLE
Support Floor Filtering in new Reporter and Manager apps

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-components#130]
See:
https://devtopia.esri.com/WebGIS/solutions-web-development/issues/22

**Comment by avezina** [comment]
We need to discuss implementation and impact areas.

**Comment by azizaparveen** [comment]
Test map: https://localdeployment.maps.arcgis.com/apps/mapviewer/index.html?webmap=b422923b7a4c4958b9788118255f2f0a

**Comment by jmhauck** [comment]
@avezina this has been in for awhile and ready for review

**Comment by azizaparveen** [comment]
Test devext map for this issue https://solutions.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=89c348ba385948ee905f88b95d7517e2

**Comment by avezina** [comment]
Looking into, what's the expectation here? The web map loads, but there isn't a way to filter the different floors.
I assume the FloorFilter widget should show up as one of the map tools?
https://developers.arcgis.com/javascript/latest/sample-code/widgets-floorfilter/
![image](https://github.com/Esri/solutions-components/assets/50338557/0108ae0b-9956-4939-a7cf-925c68394eca)

**Comment by azizaparveen** [comment]
@avezina I need to make the map floor aware, forgot to do that, let me find the settings for that, and will reach out

**Comment by avezina** [comment]
OK resolved the web map issue, the widget icon is showing up 
![image](https://github.com/Esri/solutions-components/assets/50338557/c5602450-3478-4669-b8b5-2e52c232f9d4)
But the widget is not loading properly
![image](https://github.com/Esri/solutions-components/assets/50338557/db74e480-dea6-4594-bfff-f0861a72bde5)

**Comment by azizaparveen** [comment]
Discuss with Indoor team about this what is the expectation whether to have config option, AP will reach out

**Comment by azizaparveen** [comment]
Instant App is practicing the same behavior in 3D viewer.
![image](https://github.com/Esri/solutions-components/assets/138827632/42922b0e-0e91-4e5a-964f-4b0b67bcefca)

**Comment by azizaparveen** [comment]
looks good in devext

**Comment by azizaparveen** [comment]
@jmhauck I can't seem to open the floor widget this morning
![manager_floorfilter](https://github.com/Esri/solutions-components/assets/138827632/b81c8aee-7211-4b64-81df-e048d0603233)
test app: https://holistic.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=3f7e39f0545a49bf9cc07055520fcdfb

**Comment by azizaparveen** [comment]
The issues are not reproducible in devext anymore.
![image](https://github.com/Esri/solutions-components/assets/138827632/5195aaa5-ff9e-4c24-a4ff-0b16fccf8a81)

**Comment by azizaparveen** [comment]
I am seeing the the following issue again in qa, and I am seeing this behavior in Chrome
FYI, @sarahmcdonald7 
Test app: https://solutionsqa.mapsqa.arcgis.com/apps/instant/manager/index.html?appid=38a8886d4c214220b42514d25fe61abb

- [ ] In configuration preview, clicking on the floor widget do not do anything 
- [ ] At runtime, I have to click twice for the widget to open but it works at runtime

**Comment by azizaparveen** [comment]
I see these issues both in dev and qa

**Comment by jmhauck** [comment]
@azizaparveen seems to be working this morning...I don't really know what to do to increase stability of this. I've not changed anything about it since first adding it but seems like it comes and goes. It's wrapped just like the other JS api widgets we show on the screen so it's weird that it just stops every so often and the others don't seem to do the same.

![image](https://github.com/Esri/solutions-components/assets/2170893/62c3fcfc-52b3-41de-a597-47641c7d10ab)

**Comment by azizaparveen** [comment]
Thanks John, closing this.
