### ISSUE TITLE
PN 4.x : Default notification list name not showing buffer info when using search method to select features

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#133]
Default notification list name not showing buffer info when using search method to select features.

**To repro:**

1) Click Add button to start a notification list
2) Select Search tab, enter Glendale, choose the first entry from the suggestion list.
3) Notice that PN component found the address and mark with point, since the default buffer is 0, no feature is selected.
4) Increase the buffer to 5000 meters and 22 records are found and selected.
5) Click Done without adding any notification label
6) in the My list panel, the list shows up but does not include the buffer information.
Note: if I use sketch to select with buffer, it shows the buffer information.

![image](https://user-images.githubusercontent.com/10148401/215625883-25ad3757-312d-439c-ba8d-bbc59451a054.png)

**Comment by aparveen** [comment]
it is a minor issue @jmhauck,

**Comment by jmhauck** [comment]
@aparveen this went in with a PR and should be resolved but I didn't add a good label so I forget what PR it was

**Comment by aparveen** [comment]
Verified
