### ISSUE TITLE
PN 4.x: Custom notification label changes to default label when editing existing notification and selection method changes

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#134]
Custom notification label changes to default label when editing existing notification and selection method changes.

**To repro:**

1) Click Add to start a notification list
2) Use search box to search Burbank, select the first suggestion and enter 5000 as buffer distance
3) Enter a custom label and click Done.
4) from the My Lists panel, click on the edit button of the recently created list. it will take you the selection status.
5) Now change the selection mode to Sketch and draw a rectangle, the map updates with new aoi, buffer distance and new selection.
6) Notice that the custom label is still there, click done and notice the custom label changed to default label for search.

![Customlabel_notpersisting1](https://user-images.githubusercontent.com/10148401/215891641-df51fb60-ce8e-4c1d-be10-d665d10f6ea9.gif)

**Comment by jmhauck** [comment]
@aparveen this should be resolved as well in one of the recent PRs

**Comment by aparveen** [comment]
Verified
