### ISSUE TITLE
PN 4.x: Vertically Center check box on lists on Download pages

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#137]
Could we center the checkbox vertically with the corresponding list box:

![image](https://user-images.githubusercontent.com/6796763/216452360-b2fd698b-63c2-4eea-8831-109d60adb91c.png)

**Comment by jmhauck** [comment]
@chris-fox on devext today

**Comment by aparveen** [comment]
![image](https://user-images.githubusercontent.com/10148401/216720449-09129889-2bf9-4799-922e-1bcd8ae082c4.png)

Verified
