### ISSUE TITLE
PN 4.x: Buffer distance doesn't update in list label when changed

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#138]
**To repro:**

1) Click Add button to start a notification list
2) Select Search tab and search for an address
3) Enter a buffer distance of 100 feet and click Done
4) The label correctly shows the searched address and the buffer distance
5) Edit the list and change the buffer distance to 500 feet, click Done
6) The label still lists 100 feet.

**Comment by aparveen** [comment]
Verified at the component level
