### ISSUE TITLE
PN 4.x: When I add an additional Search source in the configuration it breaks the search component

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#139]
**To repro:**

1) In the config under interactivity add an additional search source using a layer from the map (In my case I used Parcels and want to be able to search on the PIN)
2) In the widget attempt to add a list using Search, the search component doesn't load:

![image](https://user-images.githubusercontent.com/6796763/216455775-24351541-898e-4243-8efb-e3884445e143.png)

**Comment by jmhauck** [comment]
@chris-fox will keep an eye on this. Not completely sure about what all we can rely on yet from the config. I am seeing this problem in the preview but seems to be fine when I publish and launch the app.

**Comment by aparveen** [comment]
This is still broken as of today. Sent a bunch of issues to Sarah. She will log them in them in their repo.

**Comment by aparveen** [comment]
This is fixed
![image](https://user-images.githubusercontent.com/10148401/219417300-aa8311f4-b175-4069-9fee-274ead299bcf.png)
