### ISSUE TITLE
In Refine selection workflow, feature removed count does not update if I remove features 2nd time

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#142]
In Refine selection workflow, feature removed count does not update if I remove feature twice.

**Repro steps:**

1) Click add to create a notification list
2) Using sketch tool, select some features, click done
3) Click on the Refine tab
4) Make sure remove is selected
5) Unselect few parcels to remove those from selection, notice that the count gets updated properly
6) Repeat step 5 and notice that the Features removed count is not getting updated this time, total and features added is working as expected.

Test app : https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=6d9eb68f0932403f80df1b6f487494c7

![image](https://user-images.githubusercontent.com/10148401/216712883-8a3d2e3d-e851-41ea-b2ca-e0df8f64c970.png)

**Comment by jmhauck** [comment]
@aparveen fixes are in the demo app and devext

**Comment by aparveen** [comment]
Verified in devext
