### ISSUE TITLE
Point sketch tool does not show up when use layer feature is checked

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#147]
Point sketch tool does not show up when use layer feature is checked

**To Repro**

1. Click add to create a new list
2. Click Sketch tab and notice that point sketch tool is visible
3. Check Use layer features
4. Notice that point tool is missing from the sketch tool toolbar

![image](https://user-images.githubusercontent.com/10148401/217086341-5ad42a7b-cbf9-4dc3-8a9a-da8484e8c4f8.png)

**Comment by jmhauck** [comment]
@aparveen the select tool does the point sketch but agree that wasn't the best choice for the icon. Switched it to use the same icon as the sketch widget for point.

**Comment by aparveen** [comment]
Verified
