### ISSUE TITLE
Public Notification Instant App - resizing button width

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#162]
Right now buttons like Add, Cancel, and Download, etc; take the full panel width and it can be resized to a smaller width for a cleaner look.

![image](https://user-images.githubusercontent.com/3836616/217913396-bb5631b7-aa53-4e0d-82f9-39df89d03dca.png)

**Comment by aparveen** [comment]
Sent this request to Instant Apps team, they need to handle this from there side

**Comment by aparveen** [comment]
We requested Instant App team to set up a maximum width for the panel, so the panel will not look wider and button will also look better, will that help @skrishn? Here is the issue in Instant App repo https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/7824.

**Comment by aparveen** [comment]
Closing this one since we are tracking this in https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/7824.
