### ISSUE TITLE
Public Notification Instant App - Extra Features selected when "Use layer features" is on

### ISSUE THREAD

**Issue by shoe913** [Esri/solutions-components#164]
When selecting a single polygon with the point sketch tool, if "Use layer features" is on, extra polygons are selected.

Without Setting:
![image](https://user-images.githubusercontent.com/11777080/217918788-9f77f7b5-9128-4e81-9160-859ac45808fd.png)

With Setting:
![image](https://user-images.githubusercontent.com/11777080/217918987-e9c0f972-65d0-461f-86fe-ca26242d9843.png)

**Comment by aparveen** [comment]
Duplicate of https://github.com/Esri/solutions-components/issues/148

**Comment by aparveen** [comment]
We will track this one in #148, closing this
