### ISSUE TITLE
If remove duplicates is checked in PDF tab, it also gets checked in csv tab

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#183]
If remove duplicates is checked in PDF tab, it also gets checked in csv tab. My expectation was they will work independently. 
Test App: https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/notification/index.html?appid=01ea10aea2274497a148a6a4078b7f2e

**Comment by MikeTschudi** [comment]
Implemented in [version 0.4.9](https://github.com/Esri/solutions-components/releases/tag/v0.4.9)

**Comment by aparveen** [comment]
Verified in QA
