### ISSUE TITLE
Search buffer changes to default buffer distance in the config using sketch tools search method when editing a notification list

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#184]
Search buffer changes to default buffer set in the config using sketch tools search method when editing a notification list. I was able to reproduce when I changed the default buffer to zero from 1 (my default buffer set in the config) before sketch.

Test App:  https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/notification/index.html?appid=01ea10aea2274497a148a6a4078b7f2e

**To Repro:**
1) Click Add to create a list
2) Select Sketch and change the buffer distance from 1 (default) to 0
3) Select rectangle sketch tool and draw an aoi
4) Click Done
5) From My List tab, click edit button on the notification list you just created, and notice that the buffer distance changes to 1

![bufferdistancechanges](https://user-images.githubusercontent.com/10148401/219507404-fec5e8ba-9437-4cc3-8217-7f08e1c616c7.gif)

**Comment by jmhauck** [comment]
@aparveen can you still see this?

**Comment by aparveen** [comment]
@jmhauck, sorry I changed the default distance in the config to 0 for some reason. Try now and you should be able to repro this, the key step is the default distance needs to be set at 1.

**Comment by aparveen** [comment]
@jmhauck  the fix is working good but the drawn aoi does not go way and seeing a console error
![image](https://user-images.githubusercontent.com/10148401/220970550-c3d3cda7-1c24-4a33-aa1f-0aa0c0e900b5.png)

**Comment by jmhauck** [comment]
This should go in with patch D tonight

**Comment by aparveen** [comment]
This looks good in devext
