### ISSUE TITLE
Download PDF and CSV panel css looks messed up 

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#185]
Test App: https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/notification/index.html?appid=01ea10aea2274497a148a6a4078b7f2e
![image](https://user-images.githubusercontent.com/10148401/219515253-645657df-afc4-4e82-a257-4b292b1a077c.png)

**Comment by aparveen** [comment]
@MikeTschudi  could you please take a look at this as well? Thanks

**Comment by MikeTschudi** [comment]
@aparveen, what should it look like, please?

**Comment by MikeTschudi** [comment]
@aparveen, how's this?
![image](https://user-images.githubusercontent.com/2125181/219803170-4f75a8b9-de3d-4ab8-9670-ceb6ff47e2e2.png)

**Comment by aparveen** [comment]
@MikeTschudi it looks great

**Comment by MikeTschudi** [comment]
Same code; it's fixed in both. Will submit it.

**Comment by aparveen** [comment]
Awesome, thanks so much Mike

**Comment by aparveen** [comment]
Looking good in QA
