### ISSUE TITLE
Add support for related records in PN

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#201]
Relationship query is not working in Public Notification, in the popup or in the label, I can't remember if we added support for it, In this test app, All Owners and Occupants have related table, when viewing the popup in map viewer, I can see the related records for this layer but not in PN app. Also in the label, related field values are not showing up.

Test map: https://arcgis4localgov2.maps.arcgis.com/apps/mapviewer/index.html?webmap=20f089c9110b4c738bb24a409b3f05ff
Test app: https://arcgis4localgov2.maps.arcgis.com/apps/instant/notification/index.html?appid=d92ddfe30e024ee09823c4532fedd261

![image](https://user-images.githubusercontent.com/10148401/233216713-f06e5e11-4aa7-432f-9e14-ae787a292edf.png)

**Comment by ChrisBuscaglia** [comment]
The old app used to have a setting for ‘use related records’ that we had to check on to enable this, I don’t see that at all in the config.

This is the output from the OG PN

![20c517e5-8fda-4d01-9052-2480f1788b68](https://user-images.githubusercontent.com/5614261/233432234-6d38856a-a19b-438c-9a06-27f0b63182f6.jpg)

**Comment by aparveen** [comment]
> The old app used to have a setting for ‘use related records’ that we had to check on to enable this, I don’t see that at all in the config.
> 
@ChrisBuscaglia We decided to go away from the config parameter, the idea was since the related records are configured in the pop-up, any field that is configured in the pop-up will show up in the label regardless of where the field is coming from. 
I missed to test this specific scenario before production, I am hopeful that we will be fix this soon.

**Comment by aparveen** [comment]
@MikeTschudi here is a devext map that has related records, the layer pop-up has only related table element and the related table pop-up is configured, PN is exporting labels from the layer, not from the related table 
App: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=7f9f674f1d40478c95036e9b3c451faf
Map: https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=ca71a9348e48400c9896994a2bd05e5a

**Comment by aparveen** [comment]
@ChrisBuscaglia @HeatherEisan Mike added support for related records, but at this moment it works with Classic viewer map only, we need to spend little more time on investigating how to support this in new map viewer, so I am pushing this to next release.

**Comment by azizaparveen** [comment]
Mike and I discussed last Friday about when to use parent layer pop-up and  when to use related layer pop-up when both layer has pop-up configured, wanted to know your thoughts on this as well .
We have two options
1) Always use related table layer pop-up when configured, since pop-up are always enabled by default (Field list) for both feature layers and tables and we support field lists as well, I can't think of a way to know whether they are configured intentionally unless we look for specific label structure.
2) Add a parameter in the config like what we used have in Web Appbuilder. Asked Heather she also mentioned about the parameter.
I am kind of leaning towards the parameter option. Bus asked me before on this and Initially we thought of using the related table pop-up by default. 
@chris-fox @ChrisBuscaglia @jmhauck

**Comment by azizaparveen** [comment]
@HeatherEisan @ChrisBuscaglia @sarahmcdonald7 
We have added support for related records using new map viewer pop-up configuration. it works a bit differently that how it used to work with classic map viewer pop-up.

**How to set up pop-up to work with related records in Public Notification**
Example web map: https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=be3f58213d4c43a3be1eab52b81a6b40

1) In your parent layer pop-up, only add related records element and nothing else
![image](https://github.com/Esri/solutions-components/assets/138827632/432a92ea-e99e-4f89-a405-624ef41cb107)

2) In your related table pop-up, add a text element and configure the address labels in that
![image](https://github.com/Esri/solutions-components/assets/138827632/a3c47985-e3bd-48f5-82bf-d7fda04bff67)

3) Save the map and use it in PN, here is a sample app for you to test 
https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=cb0c9aca35e345b78a89730a4a248b77

**Note**:
1) The app can retrieve multiple related records tied to a single feature. 
2) Only known limitation is, if a field being added from parent layer to related table pop-up using arcade expression that field  is not getting resolved. We are planning to fix this in next release.

**Comment by azizaparveen** [comment]
Verified in devext

**Comment by HeatherEisan** [comment]
I am not a member of the org you linked to above, so I cannot see your map.

**Comment by azizaparveen** [comment]
> https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=be3f58213d4c43a3be1eab52b81a6b40

@HeatherEisan could you try again please, the map is publicly shared, it should not ask for credentials, only you have to provide the splash screen credentials for devext

**Comment by HeatherEisan** [comment]
@azizaparveen: Thank you, I can see it now.

**Comment by azizaparveen** [comment]
@HeatherEisan another known issue is, it does not work with classic map viewer maps pop-up configuration. The way new map viewer works with related record is very different than what we used to have in classic viewer so we had to switch from classic to new.
Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=082f01850c884d4b999299ed25817e67
Test map: https://sg-em-devext.mapsdevext.arcgis.com/home/webmap/viewer.html?webmap=36d2a2e2040a47eb98567e342281e8a7

![image](https://github.com/Esri/solutions-components/assets/138827632/dda70c05-7898-4bd7-b5bd-3c67bebf6414)
