### ISSUE TITLE
Once there is a selection set, turn on Layer features and select a layer to be used for selection is not updating the existing selection set

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#208]
In a workflow where I sketch and select some features, after that if I turn on Layer features, I was expecting that selection set will be updated using the selected layer features, but it is not updating. If I create new sketch it honors the layer selection.
![LayerFeature_NotUpdating](https://user-images.githubusercontent.com/10148401/235224828-15e1d7ac-59b8-44ed-9b45-4b5c9e819c32.gif)

**Comment by jmhauck** [comment]
@aparveen this should be good now please let me know if you see any issues with it still

**Comment by aparveen** [comment]
This looks good and working as expected, I couldn't repro the issue I was seeing last week.
