### ISSUE TITLE
Add addressee layer name in the refine list like the other lists

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#219]
Notification lists has addressee layer name, it will great if we can do the same for refine list, if there are more than one addressee layer, and more than one refine list, I think it will be helpful for the users.
very low priority for June release
![image](https://github.com/Esri/solutions-components/assets/10148401/22ab8ec7-4d9c-4abc-b4b3-5a15daa0f5b8)

**Comment by jmhauck** [comment]
@aparveen The way refine is implemented it is unique and only ever has one set even if you add/remove from multiple layers.

**Comment by aparveen** [comment]
> @aparveen The way refine is implemented it is unique and only ever has one set even if you add/remove from multiple layers. So you can still manage selections across all sets.
oh ok got it, so we don't need to change string for this
![image](https://github.com/Esri/solutions-components/assets/10148401/a2aa8078-2aa5-4e7f-bf1a-f7f34c5f507c)

**Comment by jmhauck** [comment]
@aparveen correct...seems like we should go back

**Comment by aparveen** [comment]
> @aparveen correct...seems like we should go back

@jmhauck wondering if we need to mention anything about selecting input layer, it will be in cases where multiple input layers are available, in most cases it won't so not sure about this

**Comment by jmhauck** [comment]
@aparveen at the bare min we should probably update this to say something about "lists" rather than selection sets since this is the only spot that we say "selection sets". We only show the layer dropdown if they have made selections against multiple layers so if we do we should be careful how we word it.

**Comment by jmhauck** [comment]
This is what they put in for the main select page from their doc writer yesterday:

> Select features from the input layer to add to your list. Draw with sketch tools, specify a search distance, and use features from another layer to select overlapping features.
