### ISSUE TITLE
Duplicate count is not counting duplicate labels but overlapping features in multiple lists

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#222]
Remove duplicate function is working but count is not counting duplicate labels
Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=005416b95280406a91961ae085922c25&locale=en-US
I have two duplicate labels on the top right section of the Tax Parcels layer.
![image](https://github.com/Esri/solutions-components/assets/10148401/e2b7880a-e76c-4457-a53e-ff57db6babee)
when selected, duplicate count is showing 0 and I can see both labels in the printed pdf
![image](https://github.com/Esri/solutions-components/assets/10148401/4aac48bd-e808-4d1e-8e73-f3d0300b68d1)
**Note: if I check Remove duplicates, it removed one of them so the Remove duplicate function is working  but the count is not.**

**Comment by jmhauck** [comment]
@aparveen this should be in tomorrow morning

**Comment by aparveen** [comment]
Verified in devext
