### ISSUE TITLE
Can we make rectangle sketch tool default instead of Select feature tool in the select panel and refine tabs

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#223]
Select tool does not seem to do much, so wondering if we can make Rectangle sketch tool default instead.
feedback got from Alix and Chris 
![image](https://github.com/Esri/solutions-components/assets/10148401/5cd55867-111e-4ca7-a68a-8ec074ae830f)

**Comment by jmhauck** [comment]
@aparveen  I've added the hide select tool and auto set the rectangle. 

I wonder if we will get feedback about auto setting of the rectangle though. It could be annoying if you first want to pan/zoom to the area of interest before you start sketching and try to do so and get a sketch and then need to delete it and deselect the sketch tool before you can simply pan the map. It would be nice if you are already at the area of interest but I just wonder if that will be the case in workflows that are not just simple test cases.

If we think some will want and some will not it could have a config option but seems like that would need to wait for next release as it would require a new string.

**Comment by aparveen** [comment]
Final decision was to keep the pan tool as default in the selection panel and in Refine panel we decided to keep the selected tool active after completing an sketch so users do not have to select the same tool again if they want to continue with drawing more sketches.
The final changes are looking good.
