### ISSUE TITLE
Label came out undefined when pop-up uses uppercase but feature layer uses lowercase field names

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#251]
As per the discussion with Mike, we decided to convert both pop-up field cases and feature layer field cases to lowercase and then match them. 

![image](https://github.com/Esri/solutions-components/assets/10148401/4784fc6d-9f47-41b7-a3af-79efe724289b)

**Comment by azizaparveen** [comment]
Duplicate, tracking this in #293
