### ISSUE TITLE
Don't enable editing on graphic when searching for a feature

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#259]
Use the app below to create a new list and search for parcel 0702301004. When you execute the search by default the graphic will be in edit mode. I don't think we should enter edit mode in this scenario. I would only enter this mode when we draw an interactive graphic. This feedback came from a user at the UC.

https://www.arcgis.com/apps/instant/notification/index.html?appid=5bf6a7ff456e404cbd1c0aa0082a0587

**Comment by azizaparveen** [comment]
Verified in devext
