### ISSUE TITLE
Improve UX for user onboarding when app first loads and record must be selected

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#262]
Suggested changes to potentially improve user experience the first time a user needs to select a record from the table. 

The gray box doesn't look like the common checkbox most people a familiar with (it's dark-themed) and it may just not occur to some people that checking the in the table box = select a record. 

**Current design:**
![image](https://github.com/Esri/solutions-components/assets/50338557/7f8aac88-54de-4783-ae77-47581cf39df3)

**Proposed changes:**
with filled icon, which matches the checkbox style when selected in the table
![image](https://github.com/Esri/solutions-components/assets/50338557/3eb2b82b-5ed7-44bd-aa55-05eef18d4abb)
![image](https://github.com/Esri/solutions-components/assets/50338557/8492f1ce-ebd9-4fc4-a06a-0e5e249ec804)

or with clear icon
![MicrosoftTeams-image (3)](https://github.com/Esri/solutions-components/assets/50338557/449ec1fc-835c-40cd-936e-1ac2a5e7a7f8)

Maybe there are also other things that can be done to onboard the user.

For example, could we add a tooltip that displays when the app first loads and there are no records selected?
This would be similar to the tooltips we currently see displayed for buttons
![image](https://github.com/Esri/solutions-components/assets/50338557/63fb8596-635e-4577-9884-7e7949971062)
But this one could be displayed against the first row's checkbox, and it's active until the user dismisses it.
To do this, maybe we could use the [popover component](https://developers.arcgis.com/calcite-design-system/components/popover/)? There may be some limitations I'm not aware of - for example, can we prevent the popover from showing up again after it's been dismissed once in the session?

cc @azizaparveen

**Comment by avezina** [comment]
@jmhauck You shared the following design updates to prompt the user to select or create a new record.
![image](https://github.com/Esri/solutions-components/assets/50338557/40297823-e3ba-452d-831b-a9bff37421ea)

I understand the need to also specify that the user can add a record if we implement https://github.com/Esri/solutions-components/issues/275

In the screenshot above, is the button part of the notice, or is that just an icon? I think with both the checkbox and the add icon within the notice it's a little too much?

Here's also some suggestions:

1. We could just have text here:
![image](https://github.com/Esri/solutions-components/assets/50338557/0d8ef42b-0879-432c-96b9-eca57ed002dc)

2. Add the popover along the checkbox row in the table? Maybe something like in this codepen, but tie the popover to the first grid cell instead of the checkbox? Not sure if that's possible.
https://codepen.io/avezina/pen/XWyoOay
![image](https://github.com/Esri/solutions-components/assets/50338557/d4e6f1fc-f330-4647-b8d7-b4d6dc06237d)

3. Add record would be a standalone button that will open the Editor. Something like below
![image](https://github.com/Esri/solutions-components/assets/50338557/b0ddf791-07fe-49c0-abf2-48ee42d74b51)


cc @azizaparveen

**Comment by jmhauck** [comment]
@avezina I know we are going to not do the Add Record at the moment. But one thing I wanted to point out about the initial message is that I have implemented select from the map or select from the table. Selecting in either will update the other.

**Comment by avezina** [comment]
@jmhauck We can probably just keep what you have right now and do some usability testing with a few people to see what their first instinct is when they open the app for the first time and see "Select a record to get started".

**Comment by azizaparveen** [comment]
We will have onboarding messages in the full release from IA team as well
