### ISSUE TITLE
Update switch selection icon

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#263]
The icon for "Switch selected" is the same as "Refresh" in Crowdsource Manager.
![image](https://github.com/Esri/solutions-components/assets/50338557/6e479ace-6098-432f-8291-4cd8b3e3d3f5)

The Instant Apps tea may come up with a new icon for switch, or perhaps we can use one of these:
![image](https://github.com/Esri/solutions-components/assets/50338557/14a1a75f-1288-4836-88f5-6940916f15c8)

cc @azizaparveen

**Comment by azizaparveen** [comment]
Sarah and team didn't back on this, wondering if we can use this one for Switch selected. Arrow-up-down looks like a good icon for sort
![image](https://github.com/Esri/solutions-components/assets/138827632/878810b7-21cd-4cf7-a4a2-b93e572d5708)

**Comment by azizaparveen** [comment]
new switch selection icon, also noticed that the icon colors are blue instead of gray
![image](https://github.com/Esri/solutions-components/assets/138827632/c4857390-2f2d-4b4e-8dd2-29c4ec89542c)

**Comment by azizaparveen** [comment]
Verified in devext
