### ISSUE TITLE
Move Clear Selection button out of overflow popover and into the main header toolbar

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#264]
The button to clear selection will get high use as users navigate their data in the table. I feel it would make more sense to expose this button as part of the main toolbar rather than in the overflow. 

![MicrosoftTeams-image (4)](https://github.com/Esri/solutions-components/assets/50338557/0dd392f2-27f5-4579-bdb8-d78d88346a01)

cc @azizaparveen

**Comment by azizaparveen** [comment]
This one also implemented in the demo app
![image](https://github.com/Esri/solutions-components/assets/138827632/5e35bc9b-726d-414e-9d05-37db3eeaa859)
