### ISSUE TITLE
Explore collapsible options for Information and Map panels

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#266]
This would allow users to fully expand the map or the information panel.
![image](https://github.com/Esri/solutions-components/assets/50338557/6d8794d8-5aec-4e81-bf24-ba5b4508234f)

If we don't want to do custom work, it seems our only option would be to use a horizontal [action-bar](https://developers.arcgis.com/calcite-design-system/components/action-bar/), as we did for expanding the Table.

**Comment by jmhauck** [comment]
@avezina this should be resolved with the newer design

**Comment by azizaparveen** [comment]
Verified in devext
