### ISSUE TITLE
Change Layout labels

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#268]
Maybe I just have a different perspective and I'm being nit-picky... but I feel like the labels for these should be reversed?

This is vertical?
![image](https://github.com/Esri/solutions-components/assets/50338557/7a714558-f77b-4456-bb5e-45b98ff5b166)

This is horizontal?
![image](https://github.com/Esri/solutions-components/assets/50338557/1010161f-80b1-4f9b-8a68-d5363d8a3f2c)

@chris-fox what do you think?

**Comment by azizaparveen** [comment]
Looks like John already took care of this. verified in the demo app.
![image](https://github.com/Esri/solutions-components/assets/138827632/994fdee0-574b-4ce6-a358-dbab5ad98dfb)
![image](https://github.com/Esri/solutions-components/assets/138827632/f074ba47-0c81-461c-a8b0-334e1f5c91c6)

**Comment by azizaparveen** [comment]
Closing
