### ISSUE TITLE
Explore having Editor widget within Information panel

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#269]
Editor widget can replace the Information panel while editing and the section can expand to full height. 
Quick example, if we implement also the collapsible https://github.com/Esri/solutions-components/issues/266
![MicrosoftTeams-image](https://github.com/Esri/solutions-components/assets/50338557/e1428804-d9f4-49d5-9410-988abf05bfcc)
![MicrosoftTeams-image (1)](https://github.com/Esri/solutions-components/assets/50338557/883b2153-ec75-4cac-9bf4-36f5b74e94f2)

This will work well for the Grid and the horizontal layouts, but will be a challenge for vertical.
![image](https://github.com/Esri/solutions-components/assets/50338557/f14c3493-8e3b-4e33-9eed-1cfc297ab282)

![image](https://github.com/Esri/solutions-components/assets/50338557/e4cb6b97-b322-48e6-98ca-41dd23576f4e)
Not sure if for this case, the Editor would need to show in a floating side panel, or if we split the Information section into two parts with Information on once side and Editor on the other... 🤔 

cc @chris-fox

**Comment by jmhauck** [comment]
@avezina showing in that panel will be no problem. The main thing I don't know how to deal with is the fact that the editor doesn't seem to fire any event when you go to add a related record or if you cancel the adding of a related record. So I don't know how to tell if the back button should close the widget or go back to the main edit panel. 

If add related record changed the state like when you go to add an attachment then it would not be an issue. I can show an example tomorrow if this isn't clear.

**Comment by chris-fox** [comment]
@avezina, yea I am not sure how useful the vertical layout is. Looks kind of weird with the information spread out all the way across the app like you said. Maybe more useful on a mobile device? We haven't been thinking about mobile a lot yet for Manager, but it is probably something we need to support.

**Comment by avezina** [comment]
@chris-fox 
> I am not sure how useful the vertical layout is. Looks kind of weird with the information spread out all the way across the app

Agreed. I feel like having the table full width is valuable, but you can still do that with the other 2 layouts by collapsing the left section. We can evaluate mobile device if needed: https://github.com/Esri/solutions-components/issues/274

**Comment by jmhauck** [comment]
@avezina anything seen as incomplete with this?

**Comment by avezina** [comment]
@jmhauck I think we're good on this, thanks!
