### ISSUE TITLE
Provide count of records in the table

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#270]
An often requested enhancement for the ExB Table widget was to provide a count of features. https://devtopia.esri.com/Beijing-R-D-Center/ExperienceBuilder-Web-Extensions/issues/13179

I think we may also want to do the same. We also had this in CM 3.x.
![image](https://github.com/Esri/solutions-components/assets/50338557/24927786-2dc9-42e2-80ba-cf9bbae091eb)

Other examples: 
![image](https://github.com/Esri/solutions-components/assets/50338557/7e63c3ac-62cd-442c-8a1f-654874793de1)
![image](https://github.com/Esri/solutions-components/assets/50338557/4fca2a96-c32d-459d-a001-dbc6d55fbac6)

@jmhauck any suggestions on how/if we can also display that information?

**Comment by jmhauck** [comment]
@avezina the FeatureTable does support this but feels weird with our design

![image](https://github.com/Esri/solutions-components/assets/2170893/6030c958-1d6d-4058-bb73-ab70a7479af1)

Could look at adding to the layer picker but it also feels off:

![image](https://github.com/Esri/solutions-components/assets/2170893/6a6d3cdc-8fa8-4ea5-8c18-e2ce63c304ac)

or

![image](https://github.com/Esri/solutions-components/assets/2170893/312ee40e-53a3-42a2-aa63-415b098b9bfd)

We can certainly display that stuff but where is the main question.

**Comment by avezina** [comment]
@jmhauck Would something like this be an option then?
![image](https://github.com/Esri/solutions-components/assets/50338557/155c1622-994c-450d-aead-2fcbf2457b64)

**Comment by jmhauck** [comment]
@avezina should see this in lower left as the last example above

**Comment by azizaparveen** [comment]
@jmhauck can we add a little bit of padding,
![image](https://github.com/Esri/solutions-components/assets/138827632/a1aba745-d5ba-41b2-99fd-94511ac89952)

**Comment by avezina** [comment]
@jmhauck Tinkered with it a bit. I suggest:
![image](https://github.com/Esri/solutions-components/assets/50338557/fdfaa30b-b183-4895-92cd-d23d3a63ec0d)

**Comment by azizaparveen** [comment]
Can we add this at the top right corner of the table? Since we are thinking about the buttons to go in the overflow menu, will this be causing any issue?
![image](https://github.com/Esri/solutions-components/assets/138827632/4d63230d-1d62-46f5-8d66-91bcdfa40fb4)

**Comment by jmhauck** [comment]
@avezina  We can change the words and separator if that is preferred but have already accounted for the general format issue:

`"{{total}} records, {{selected}} selected"`

**Comment by avezina** [comment]
@jmhauck Looked into getting some extra clarification around this, here's the full explanation on why we should use that specific format
![image](https://github.com/Esri/solutions-components/assets/50338557/48fe38ca-23dd-427d-886c-299768282a1c)

**Comment by avezina** [comment]
Adding a new observation: EXB opted to place their count below the table:
![image](https://github.com/Esri/solutions-components/assets/50338557/3d73068f-4128-4835-a893-9f726a021de7)

Perhaps we should do the same; placing it above the scroll bar may be a challenge due to variability in scroll bar width between browsers.
![MicrosoftTeams-image](https://github.com/Esri/solutions-components/assets/50338557/299ec57f-7d37-40be-aa3a-484d702b9228)

@azizaparveen @chris-fox What do you think about placing it below the table and allowing for a small amount of padding there?

**Comment by jmhauck** [comment]
@avezina ready to test tomorrow

**Comment by azizaparveen** [comment]
@jmhauck this looks so much better, can we have a tiny bit of padding on top and left of the count?
![image](https://github.com/Esri/solutions-components/assets/138827632/03acce0d-d7ee-48d7-869d-1fe467e73e54)

**Comment by jmhauck** [comment]
@azizaparveen was trying to keep it as small as possible since all the space to the right is wasted. If I pull it down slightly is that enough to make it not looked scrunched or want more?

![image](https://github.com/Esri/solutions-components/assets/2170893/dd58f2c8-9ce3-4f30-b323-3ab096617c19)

**Comment by azizaparveen** [comment]
@jmhauck this looks good to me

**Comment by jmhauck** [comment]
@azizaparveen not until tomorrow

**Comment by avezina** [comment]
@jmhauck looks better, but I think we should still add a little padding to the left 
![image](https://github.com/Esri/solutions-components/assets/50338557/1d08eedc-3543-4055-995b-867163da02b8)

**Comment by azizaparveen** [comment]
Left padding looks good in devext

![image](https://github.com/Esri/solutions-components/assets/138827632/26d6ae7b-365f-4a5e-a814-4eb67e1d8912)
