### ISSUE TITLE
Move action buttons to overflow when the window width is reduced

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#271]
Move action buttons to overflow when the window width is reduced.
![image](https://github.com/Esri/solutions-components/assets/50338557/0380a274-dc08-442d-9af6-193f60fa148e)

**Comment by jmhauck** [comment]
@avezina on devext tomorrow

**Comment by avezina** [comment]
This is working well! 
![image](https://github.com/Esri/solutions-components/assets/50338557/ec799d3d-043c-4271-bad7-446afbe589af)

@azizaparveen Will let you close this issue after you've also tested it.

**Comment by azizaparveen** [comment]
This looks good

**Comment by chris-fox** [comment]
Could we update this to show more tools if space is available. For example I have a wide monitor and have lots of space to show more buttons from the more menu, but it seems like everything after Show selected is always put in the menu. I would suggest showing every button possible you don't even need to show More if all the buttons fit.

![image](https://github.com/Esri/solutions-components/assets/6796763/95260bd4-b080-4fae-93de-14586db8e6d7)

**Comment by azizaparveen** [comment]
This looks good to me in dev and qa,
![image](https://github.com/Esri/solutions-components/assets/138827632/9decb719-d03b-4a3a-b40e-143637a9e527)
