### ISSUE TITLE
Support batch attribute editing

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#272]
This may or may not make it to the initial release. It is dependent on the batch being implemented in the core Editor widget.

If this cannot be supported in the initial release, hide and disable the options for muli-editing. 
(Note: multi-selection of records in the table is still supported for viewing multiple popups in the Information panel)

Related core issues for batch updates:
- Planning issue: https://devtopia.esri.com/WebGIS/arcgis-js-api-planning-docs/issues/92
- Ongoing design discussions: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/53845

**Comment by avezina** [comment]
I'll move this to the 24.R1 milestone for now.

**Comment by azizaparveen** [comment]
tracking this in https://github.com/Esri/solutions-components/issues/784, closing this issue as duplicate
