### ISSUE TITLE
Evaluate mobile UI/UX for Crowdsource Manager

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#274]
Review current designs for support on mobile and evaluate any needed changes.

@chris-fox Do we have any workflow examples where it would make sense to use this app on mobile?

**Comment by chris-fox** [comment]
I don't have any, we never had needed it for our solutions. But I believe this is more of a expectation of Instant Apps, We didn't really have a use case of Public Notification on mobile, but still added a mobile design to satisfy this requirement.

**Comment by azizaparveen** [comment]
Mobile interface looks as expected, seeing an issue that is being tracked in https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9238#issuecomment-4537259

**Comment by azizaparveen** [comment]
Mobile interface looks as expected in qa
