### ISSUE TITLE
Add support for creating new records in the table

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#275]
> **Request by Chris Delaney:**
> Do you know if we have creating new records on the roadmap? In special event operations, a police/fire special event coordinator would really only need to use one app to both create and manage information about an event. Currently, we use Crowdsource Manager 3x and Survey123 for this and have an HTML button in the info panel that a user can use to trigger a new record via the S123 form, but it’s a little clunky and non-self-evident. Ideally, I'd like to ship only one app that does both - much easier to manage and better user experience.

Currently also supported in ExB, e.g.
![image](https://github.com/Esri/solutions-components/assets/50338557/a9235d46-3e02-4a54-a813-63472b6ecdf8)

Adding support for creating new records within this app would help keep user workflows within one application.

Also maybe we could consider providing support for creating features when the map is in the layout.

**Comment by avezina** [comment]
@jmhauck Questions based on your draft below:
![image](https://github.com/Esri/solutions-components/assets/50338557/be97d177-b95d-4926-b40c-326fba3b40e6)

Are we planning to support both add features and records? Would add features still be available if there are no maps in the layout?

**Comment by cdelaney585** [comment]
@avezina @avezina @chris-fox @jmhauck  It looks like editing from a table has been implemented at the R2 Map viewer release- see video below- Definite implications for Manager app, as pencil icon at end of row now triggers FeatureForm widget, and a floating button in bottom-right corner triggers edit widget to create a new record:

https://github.com/Esri/solutions-components/assets/8235157/11769fd0-cc3a-4343-b78b-dd5749d66cac

**Comment by azizaparveen** [comment]
@cdelaney585 we discussed this with Chris and decided to look into it in R3, regarding creating new feature, Manager have small map, so we need to come up with a design that will work for Manager. 
For Edit button showing up for each row, we also need to think about it in R3, In Manager, first we select a feature, then click Edit then it brings up the form for editing, if we adapt this design, the current workflow is going to change.
