### ISSUE TITLE
Support filtering in Manager Instant App

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#280]
As per the conversation yesterday, I explored the filtering capabilities in Nearby and I think the experience for the configuration and runtime will work well in the Manager app. Below is a configured version of the Nearby app using our example map from our Citizen Problem Reporter solution. 

I configured the 5 most common filters needed for this particular solution and like the way it works. Its nice that the filters automatically the list of valid values in the field and that you can select multiple. There is no ability to do a free text filter, i.e contains type filter. However this might make more sense to do as a search.

https://www.arcgis.com/apps/instant/nearby/index.html?appid=1b418ee720ac42f6b1b8fa0dbdda87d5

@avezina, @azizaparveen, what do you think?

**Comment by azizaparveen** [comment]
@chris-fox, I am also playing with it, I agree with you, In addition, I like that they have predefined filter option as well, we can use that in our solutions wherever needed. Not a big fan of the UI configuration though but I think it will serve our purpose.
We don't have any runtime design for the filter in the figma file, I think it will open in a modal. I will ask Sarah and Lucy to update the design file.

![image](https://github.com/Esri/solutions-components/assets/138827632/f7cf2bf8-2b0b-41e8-bb91-985e39ccbec8)

**Comment by azizaparveen** [comment]
@chris-fox to answer your question regarding date filter, 
**Predefined date filter:** 
It works great, when a date field is selected, it shows various options to set the date filter
![image](https://github.com/Esri/solutions-components/assets/138827632/1ae89c99-8e62-40dc-900b-ab0b6ad69a9b)


**Date field with user input:**
it works with date range only, it shows the calendar for start and end date but it does not allow to set option like the predefined date filter. Will ask Sarah if I am missing something.
![image](https://github.com/Esri/solutions-components/assets/138827632/6d869722-e90e-4208-b5ec-6b2a667cb3ec)

**Comment by avezina** [comment]
I also took a look at the Filter capability provided and it seems this should work well for the initial release. I saw how it was implemented in the Park Location app from the Recreation Outreach solution and it seems easy enough to use from the end-user standpoint given an appropriate configuration.
![image](https://github.com/Esri/solutions-components/assets/50338557/01fdf902-d1aa-49fe-bf52-624014ecdcc7)

With both predefined and user input options available, it should cover most workflows?

Questions: would we need the Filter component to only reflect available filters for the current active layer in the Table? If there are no Filter options for the layer in the table, do we disable the Filter button?

**Comment by chris-fox** [comment]
Yes, i would expect only the filters for the selected layer/table to display and think we should disable the button if no filters are configured for the layer/table

**Comment by azizaparveen** [comment]
As per our email conversation, @jmhauck to work with Kelly for an option to support filtering at runtime for the beta release, the approach would be using the existing filtering option that Nearby app supports but extend it to work with multiple maps at runtime with no configuration experience.

**Comment by jmhauck** [comment]
have added the IA filter component to a modal:

![image](https://github.com/Esri/solutions-components/assets/2170893/907d6a31-4bea-46df-812f-fa7c341920ed)

Thoughts?
 
Please share any IA apps that you may have with filters that may be similar to what we'll use in Manager with me so I can throw some more complex filter configs at it.

**Comment by chris-fox** [comment]
Looks good John. Here is a nearby app I had configured with filters for the Citizen Problem Manager use case:

https://www.arcgis.com/apps/instant/nearby/index.html?appid=1b418ee720ac42f6b1b8fa0dbdda87d5

**Comment by jmhauck** [comment]
Still need to add the config side for this as well as add support for url params.

**Comment by azizaparveen** [comment]
looks good in devext

**Comment by chris-fox** [comment]
@azizaparveen, @jmhauck, I am finding the map is not honoring the filter that is applied. I would expect the map to also honor the filter that is applied.

**Comment by azizaparveen** [comment]
@chris-fox I could not repro this in devext, could you please share your app?

![Image](https://github.com/Esri/solutions-components/assets/138827632/25aa90b5-dc20-43f3-bb8f-1d87d88dff1b)

**Comment by azizaparveen** [comment]
Filtering looks good in qa
