### ISSUE TITLE
highlighting and scroll the row in the table that corresponds to the pop-up you’re viewing

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#282]
Got this following feedback from Mike Dagle during peer review meeting.

- [ ] 1. In the scenario below when more than one row is selected in the table, you’re able to toggle through the corresponding pop-ups. When viewing a particular pop-up I thought it would be helpful to also understand which row corresponds. The suggestion is a second highlight color (or some other visual cue) that shows me which row corresponds to the pop-up I’m viewing. 

- [ ] 2. Chris also wondered if the table should scroll the record viewed in the pop up as you scroll

![image](https://github.com/Esri/solutions-components/assets/138827632/bd86bb1c-1a33-45c7-9fc1-34aa50aa5ce6)

**Comment by avezina** [comment]
> 1. ...a second highlight color (or some other visual cue) that shows me which row corresponds to the pop-up I’m viewing.

Would need John's input, but I think that may be additional custom coding on top of the table. Might be a challenge to preserve this functionality when the Table widget switches to Calcite and if we decide to also swap ours to use Calcite at that time.

> 2. Chris also wondered if the table should scroll the record viewed in the pop up as you scroll

We should discuss this one more before we implement it, I think it could have unexpected impacts on UX depending on the user's workflow. Also if the records are not close together in the table, the scroll could be jumping around a lot.

For both items 1 & 2 I feel we should wait on more usability feedback from users.

**Comment by jmhauck** [comment]
@azizaparveen @avezina  My bad already added an optional prop to turn this on/off before I saw Alixs comments. Will update the demo app later today so you can look. As mentioned the additional highlight would need to be something custom as I don't see anything like this with FeatureTable.

In regards to the scroll to index this is something the table supports. Again you all can take a look and see what you think.

Also set it to zoom to the selected feature as you scroll through.

**Comment by jmhauck** [comment]
To see this you will need to add a url param. Like so:

http://dev0009449.esri.com/solutions-components/solutions-components/demos/crowdsource-manager.html?zoomAndScrollToSelected=true

**Comment by azizaparveen** [comment]
@jmhauck I am noticing that when clicking on a feature on the map the table does not scroll to that record. I used the IA map and selected a road from DOT roads, also see this same behavior in PN map - Tax Parcel Owners layer. it does not scroll to that record in table.

![Managernotscrolling](https://github.com/Esri/solutions-components/assets/138827632/fba33ddf-6985-43f5-96e8-294c6c5ffd18)

but in CS TIL map, it does, is there any reason why it would work for one and not work in another layer?

![Managerscrolling](https://github.com/Esri/solutions-components/assets/138827632/1f9a15bb-d0a1-41a1-b1f2-f8cb23cba3cf)

**Comment by avezina** [comment]
> @azizaparveen @jmhauck Another thought - instead of scrolling to the record, perhaps we could have an option for "Show only selected" ?

Oh sorry, we already have that option. I think this would cover the use case well enough without use having to handle all the weird behavior we are seeing?
![image](https://github.com/Esri/solutions-components/assets/50338557/dfece094-e6c7-4d17-b9be-aa5a98d65bc9)

**Comment by azizaparveen** [comment]
@avezina I like the scroll and zoom function, pop-up (in the info panel) can be different and convey different information than the data itself, so seeing the pop-up and seeing the same data highlighted and scrolled will be helpful for the users. The initial behavior when selecting from table is bit strange but it does not bother me as much. On the positive side, this function will be very helpful when selecting from map and the record is not visible in the table.

**Comment by jmhauck** [comment]
@azizaparveen @avezina let me see if it can be fine tuned at all....basically just occurring whenever the selected index changes on the Features widget so not sure if we can tell if that change comes from interaction with Features next/back buttons vs selection from map or table.

**Comment by jmhauck** [comment]
@azizaparveen scrolling to the record within the table does not work well when you have more than just a few features. This is something that we would need to bring up with JS api team. In order to support this we first call `getObjectIdIndex` on the tables view model. In this and many other cases it returns -1. Even if I scroll all the way down to where this feature is in the table so I can see the checked box after I select the road within the map the index that is returned is not correct.

**Comment by avezina** [comment]
@jmhauck @azizaparveen I think we can bring up any issues we find in the JS SDK featureTable to Jonathan Uihlein; he is the developer. If you have not shared our implementation of the table in Manager yet, it might be an opportunity to share it with him - I'm sure he'll be interested. Feel free to CC me on the email.

**Comment by azizaparveen** [comment]
Adding Jonathan's comment on the issue of incorrect index being returned when using getObjectIdIndex and scrolling not working when we are showing only selected results.

"For 1) I believe the row has to be loaded into local memory to be able to be scrolled to. The table fetches pages of 50 features at a time so if the page hasn’t loaded, we don’t know the feature’s index. This is unlike selection, which is driven by objectId, so it can be virtualized and applied to rows as they load. The store is generally unable to determine what “index” a feature has in the context of the greater dataset, nor the page a particular feature would be on by itself. We would really need some sort of layer query (since it also depends on the sort order) to determine the page/index. Currently, we use pagination to support very large datasets (we don’t want to load 200k features into memory at once) and this was a carry-over from the 3x JSAPI FeatureTable. I think the default value of 50 features per page can be overridden (up to 2000 which is usually the layer/service limit) but there may be performance implications depending on the number of columns/fields.

For 2), this might be a bug, scrolling should work even if only showing a “subset” of features; I can follow up on this, maybe the index is returning incorrect. "

**Comment by azizaparveen** [comment]
Follow up with Jonathan about this and url parameter.

**Comment by azizaparveen** [comment]
Creating 2 issues from this issue. 

1. Tracking the first issue here: https://github.com/Esri/solutions-components/issues/580
2. Tracking the 2nd issue here: https://github.com/Esri/solutions-components/issues/582

In this issue we tried to implement the second enhancement request which is scroll to the record that is being viewed in the pop-up in table. When implementing this, multiple issues were found and communication got confusing,  Right now we have only one issue we are trying to resolve for the scrolling enhancement is scroll to a specific index in the table when only showing subset of features.
