### ISSUE TITLE
When only add records capability is enabled, Manager is showing console error but opens the editing panel

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#295]
When editing enabled in the layer but only add records are permitted, Manager is showing a console error and opening the editing panel

Test app: http://dev0009449.esri.com/solutions-components/solutions-components/demos/crowdsource-manager.html?
Test Map: CS TIL Data

**Reproducible steps:**
1) Launch the test app and change map to use CS TIL Data 
2) Click on a record to show details either from table or from map
3) Click on the Edit button. Notice that the editing panel opens but Update button is disabled

**Note**: I could not repro the console error consistently, only able to see it when I first opened the app and changed the map.

![image](https://github.com/Esri/solutions-components/assets/138827632/9453d86f-9687-40a0-aeff-37054ee967e3)
![image](https://github.com/Esri/solutions-components/assets/138827632/5463f40c-5716-4d8f-b4a9-66a584cbcaa3)
![image](https://github.com/Esri/solutions-components/assets/138827632/0b7eb245-4078-464c-9977-be0179016f95)

**Solution:** In this scenario, we can do the same as we are doing with editing disabled layer, when clicking on the Edit button, it will show a message that.

Updating Disabled
Update must be enabled on the layer.
![image](https://github.com/Esri/solutions-components/assets/138827632/515e75dc-b631-4288-9e31-d1d20621374c)

In some cases we are showing this message in the information panel but I think user should be able to see the pop-up information regardless, in the following scenario, we can't navigate back to the pop-up information

![image](https://github.com/Esri/solutions-components/assets/138827632/48ec522b-69d2-4c3b-8e0a-3cd4048009b3)

**Comment by jmhauck** [comment]
@azizaparveen Was only checking `featureLayer.editingEnabled` but have added `featureLayer.capabilities.operations.supportsUpdate` with the PR above. Will need to check more on "No editable layers found" thats coming directly from the Editor widget when the layer in question has both editingEnabled and supportsUpdate as true.

**Comment by jmhauck** [comment]
@azizaparveen "No editable layers found" comes from the editor widget. Seems like it occurs when the feature is not within a visible scale range. Not sure what we could do other than something like zoom to the feature and/or raise the issue with the api team.

**Comment by azizaparveen** [comment]
I can't repro this anymore, closing
