### ISSUE TITLE
Unexpected behavior when show selected and switch selected are used

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#301]
When Show selected is enabled, and then 
- click Switch selected, only a few features become selected instead of everything else
- if click Switch selected again, then all features are shown and I can no longer see only what's been selected

https://github.com/Esri/solutions-components/assets/50338557/ce1a13df-9505-4c4d-af75-a415bd6fbdac

**Comment by azizaparveen** [comment]
Verified in devext
