### ISSUE TITLE
Asc/Desc sorting isn;t working as expected in table for ObejctID field

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#304]
https://github.com/Esri/solutions-components/assets/50338557/efca1f89-e3a0-4636-883d-291a11ba2d2b

**Comment by jmhauck** [comment]
@avezina seems like its tied to a FT bug

**Comment by avezina** [comment]
@jmhauck just saw your email, thanks for sharing with them! 
![image](https://github.com/Esri/solutions-components/assets/50338557/30ddbb7c-425e-44de-a136-ec2ec1d59b46)

**Comment by azizaparveen** [comment]
Verified in devext
