### ISSUE TITLE
Move map navigation tools outside of the expandable action bar as their own floating buttons on the map

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#309]
Move map navigation tools outside of the expandable action bar as their own floating buttons on the map. In this way, the user can still view the Legend and navigate at the same time.
![image](https://github.com/Esri/solutions-components/assets/50338557/14197506-3287-4a42-8431-8515296fdf1b)
![image](https://github.com/Esri/solutions-components/assets/50338557/89736e33-e2ec-47b8-a312-a4ff03af1f22)

Example:
![image](https://github.com/Esri/solutions-components/assets/50338557/7a14d9d8-8d5a-42e0-93c6-74e440ca7d37)

**Comment by azizaparveen** [comment]
verified in the component.
![image](https://github.com/Esri/solutions-components/assets/138827632/486be427-301b-44f2-9393-7900ab8ddb01)
