### ISSUE TITLE
Change Expand button icon and tooltip (Map widget) to Fullscreen buttons and tooltips

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#313]
In the design file, Map widget has an Expand button
![image](https://github.com/Esri/solutions-components/assets/138827632/a8df6f14-8e40-4347-b9ec-f1278451177c)
This should be a toggle button to enter or exit full screen, which will allow users to view the map in full screen, and exit the full screen

**Action items:**

- [x] Update the icons to show each states
- [x] Update tooltips

Tooltip on hover would be : Enter fullscreen and Exit fullscreen
![image](https://github.com/Esri/solutions-components/assets/138827632/15c92c31-d8b2-467f-b71a-0ad4dc821866)

This will be a configurable option in Interactivity -> Explore/navigate tab
![image](https://github.com/Esri/solutions-components/assets/138827632/e322b435-5328-43fc-9fdb-d4799522ffdd)

**Comment by jmhauck** [comment]
@azizaparveen the calcite icons are different than above but this is in there now

**Comment by azizaparveen** [comment]
Looks good @jmhauck, verified in the component app.
