### ISSUE TITLE
Delete record is failing

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#314]
Test app: http://dev0009449.esri.com/solutions-components/solutions-components/demos/crowdsource-manager.html?id=59004e6e375745abb0914328679901da
Service url: https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=ea9f4de9b42843f1857b443fbaf483f2&view=service
The service has editing enabled with add, delete and update permission
![image](https://github.com/Esri/solutions-components/assets/138827632/7e09251a-56ad-4e66-a8f2-0d581379af09)
**Reproducible steps:**

1) Launch the app
2) Select a record from the table and click Delete button, warning message shows up, then click delete again
3) Notice that the record does not get deleted
4) In the console TypeError: Cannot use 'in' operator to search for 'geometry' in 167 shows up.

![image](https://github.com/Esri/solutions-components/assets/138827632/277b52a2-5511-4155-b8d2-2edb725c3221)

**Comment by azizaparveen** [comment]
@chris-fox 
you mentioned in #324 that we should filter layers out of the layer picker that don't have editing enabled and don't have at least the Update capability on the service. We can delete records in Manager now and feature service can have only delete capability with no add or update capabilities, in this scenario, we won't allow users to only delete? This is a fringe case scenario but wanted to hear your thoughts. 
Right now we are not letting users to delete even though the service has only delete capability
![image](https://github.com/Esri/solutions-components/assets/138827632/7e128be6-2879-4ba3-9bb7-e0c4123928bb)
![image](https://github.com/Esri/solutions-components/assets/138827632/bf63f5e1-fecc-4b93-b10d-96fd9cf39f0e)

**Comment by chris-fox** [comment]
@azizaparveen, thanks. At this point I would lean towards keeping it as is and only showing layers that have at least update available. If they also have delete then we can support delete. If they only have delete then I think we should continue to not show the layer as an option in the map. We can wait on user feedback to decide later if we want to expand this.
