### ISSUE TITLE
Table Styling and Font Size

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#318]
A couple minor things, not sure if its possible:

- [x] Is it possible to set the font size of the text in the table cells to 14px. I am seeing them show as 16px when all the other text in the UI is 14px.
- [ ] Is it possible to have an alternating color for rows in the table? It can be hard to keep track of which row you are in as your scroll horizontally when all rows are the same background color. Example below from the 3.x Crowdsource Manager app:
   
![image](https://github.com/Esri/solutions-components/assets/6796763/1cfc96fa-fefd-4ccd-9b7a-7554e2aa1063)

**Comment by chris-fox** [comment]
Additional feedback:

- [ ] Is it possible to change the column heading colors? The original design had the column headings styled with the same light gray as the map selector menu
- [ ] Can the border around the table be the same width and grey color as the other borders in the app:
![image](https://github.com/Esri/solutions-components/assets/6796763/11ec17ad-7114-4bdb-a669-51ab2f276ae2)

**Comment by jmhauck** [comment]
@chris-fox font size is no problem
header background is no problem but they recently asked me to switch the pickers to white
they recently asked that I remove the extra border that the FeatureTable makes

I've tried several times to figure something out for the rows but have yet to find anything that works.

**Comment by chris-fox** [comment]
Thanks John, font change looks good. I am fine with there recommendation for the column heading color. I am still seeing the double border above the toolbar above the Table. It is most noticeable with the app has a Header enabled. 

![image](https://github.com/Esri/solutions-components/assets/6796763/b828eef4-f076-4bba-a134-9239700f2e01)

**Comment by jmhauck** [comment]
border is removed now

**Comment by azizaparveen** [comment]
Looks good in devext
![image](https://github.com/Esri/solutions-components/assets/138827632/acad22fe-16d0-4e29-97a4-be7afeaa740f)
