### ISSUE TITLE
Remove flicker of Edit Widget when clicking to Edit a record

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#322]
Not sure if this is just a limitation of the Edit Widget right now, but when you click to edit a record, there is a brief time in the UI when it displays the UI from the Edit widget where you can select existing records and then it loads the form to edit the record. If we can't do anything about this now, it would be great if we could get this feedback to the JS team for an enhancement to the widget for a future release.

**Comment by avezina** [comment]
Looked at how they are handling this in the Web Editor right now, as they have this similar "select a feature using a separate select tool to update its attributes" workflow.
Looks like they'd have the same flicker as well, but they have a mask and a loading indicator as well while the attributes are being loaded.
https://qawebgis.esri.com/web-editor/editor-workbench/builds/main/index.html?webmap=56cf45a606484a0188d5f073b133af74
![image](https://github.com/Esri/solutions-components/assets/50338557/8900393e-14c8-4117-ac54-b54197cec06a)

**Comment by azizaparveen** [comment]
Verified in devext
