### ISSUE TITLE
Delete button should not be available if the feature layer does not support deleting records

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#323]
In this [web map](http://dev0009449.esri.com/solutions-components/solutions-components/demos/crowdsource-manager.html?id=ce3dec81bf714d3bb71da9691ab686d1) it is referencing the following feature service:

https://localdeployment.maps.arcgis.com/home/item.html?id=ddcec2246ae14a299a5460475db245f7#settings

This service is configured to support Add and Update, but not Delete:

![image](https://github.com/Esri/solutions-components/assets/6796763/678127dd-1fa0-4fa9-b5ef-0b05895901a9)

We should detect this and not display the Delete button above the table for this layer. This is the behavior of the Edit widget today, If you don't have Delete capability enabled the Delete button doesn't display:

![image](https://github.com/Esri/solutions-components/assets/6796763/a011886f-4575-4f48-951d-5d4bf09e94e1)

**Comment by chris-fox** [comment]
Verified in Dev

**Comment by avezina** [comment]
I've a case where the Delete button is not showing, but Delete is supported for the layer
![image](https://github.com/Esri/solutions-components/assets/50338557/d9ccca4a-b344-4389-999f-a110af15c27c)
![image](https://github.com/Esri/solutions-components/assets/50338557/fcf191d1-a68b-4270-b6c7-7538f951d8ee)
Delete is shown when editing single records
![image](https://github.com/Esri/solutions-components/assets/50338557/ba385b1d-9a80-4a31-a82d-38ce64fcfb97)

web map: https://www.devext.arcgis.com/home/item.html?id=f4ee84a37f57465bbc4f4d27f54bb195

**Comment by chris-fox** [comment]
I see the same when the app first loads. If I change the layer and then change it back then the Delete button is available:

https://devext.arcgis.com/apps/instant/manager/index.html?appid=bd57063681644c4dbda2ec44cbc16823

**Comment by jmhauck** [comment]
this should be fixed on devext tomorrow

**Comment by azizaparveen** [comment]
Verified in devext
