### ISSUE TITLE
We should only show layers that have editing enabled and support the Update capability

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#324]
This is consistent with the experience in the 3.x Crowdsource Manager. This is an editing focused app and there are times where you may have read-only reference layers in the map to help give context in the map to the editable layers. In this scenario we wouldn't want these layers to show in the dropdown for the map. We should filter layers out of the layer picker that don't have editing enabled and don't have at least the Update capability on the service.

On the layer in the web map you can disable editing from the layer properties:
![image](https://github.com/Esri/solutions-components/assets/6796763/09b9e3d0-bb0a-4950-a9da-ffd8cb6022dc)

You can control editing capabilities on the service from the item settings:
![image](https://github.com/Esri/solutions-components/assets/6796763/7e34fadb-161a-4d28-90e9-311665371c2f)

**Comment by jmhauck** [comment]
@chris-fox What is the expected experience if they load a map with no editable layers?

**Comment by chris-fox** [comment]
@jmhauck, probably need some experience similar to if they loaded a map with no operational layers. We displayed a message for the old version of Manager if there were no editable layers. @azizaparveen, could you propose something for this?

**Comment by azizaparveen** [comment]
@chris-fox just had a chat with John, we can tackle this from both configuration and runtime side
1) In the configuration we can add text in the sub header of the Map tab and add a detail info in the information box, then in the map picker showing only the maps that has editing enabled and have delete or/and update capability, this is subject to change depending on IA team's input 
![image](https://github.com/Esri/solutions-components/assets/138827632/245ba99c-a578-4a03-a7e2-b9b41f9692b8)
![image](https://github.com/Esri/solutions-components/assets/138827632/bd7c8c9f-b6fb-4de1-a5f1-faae7ed132ac)
2) At runtime, in cases where a map had an editable layer and some reason editing capability is being disabled or the layer becomes unavailable, we can disable the the map with a warning sign and show a text "No editable layer found" on click
![image](https://github.com/Esri/solutions-components/assets/138827632/c23229f6-f13e-43d1-b620-53c251627d0c)

**Comment by azizaparveen** [comment]
The enhancement is in devext

At runtime, we are loading the map but in the layer picker we are showing a message and elaborated tooltip
At the configuration, we are adding a similar message when user pick a map that has no editable layers, and then in next release we are hoping to filter out maps that has no editable layers
![image](https://github.com/Esri/solutions-components/assets/138827632/d7242ebb-b707-4ff0-acec-3834e8314444)
