### ISSUE TITLE
Update Delete Feature Alert

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#325]
For consistency could we emulate the same Alert that is shown when use Delete in the edit widget.

![image](https://github.com/Esri/solutions-components/assets/6796763/ebdd04e6-8714-4ce6-9b10-23f8bf8fac64)

**Comment by jmhauck** [comment]
@chris-fox they don't use calcite-alert or calcite-notice. The main container is custom div and css and then calcite-icon and calcite-buttons internally. I can just copy their html and css and make ours exactly the same or I can try to make a calcite alert or notice look as close as possible. Mainly bring up to note that we will need to keep an eye on this if we want to keep in sync with JS api if they change down the line.

**Comment by chris-fox** [comment]
@jmhauck, maybe we should go with a calcite modal instead of an alert like below when you attempt to delete an item from your contents:

![image](https://github.com/Esri/solutions-components/assets/6796763/979c3ef7-fb85-485e-8c5e-0c2105bb7b23)

The reason I think a Modal makes more sense is you have to take action and decide right there if you want to delete the feature(s) or not. With an alert you can continue interacting with the app without either confirming or cancelling the alert.

**Comment by jmhauck** [comment]
@chris-fox I should have waited for your response. I can move it into a modal no problem. JS team uses a scrim as a way to prevent other app level interactions if you want it to look the same as the other and prevent other clicks. I'll do whatever you all think is best.

![image](https://github.com/Esri/solutions-components/assets/2170893/d746349b-55a2-4aa2-b9c3-971b6c227dd0)

**Comment by chris-fox** [comment]
Thanks John, lets go with the Modal. I think it will be more consistent with the design patterns for Calcite.

**Comment by jmhauck** [comment]
@chris-fox ready to test tomorrow

**Comment by avezina** [comment]
This UI seems good to me:
![image](https://github.com/Esri/solutions-components/assets/50338557/bf6cceae-694a-48df-9056-0b4c0268d203)

**Comment by chris-fox** [comment]
verified
