### ISSUE TITLE
The number of rows/selected count text is overlapping the table scroll bar

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#326]
![image](https://github.com/Esri/solutions-components/assets/6796763/536b4fc7-a023-4f96-8a17-34eb71c4c7cc)

I think it is good information but I didn't see this in the original design. In the 3.x app it was above the table on the right side near some of the tools. Thoughts on placement?

**Comment by azizaparveen** [comment]
@chris-fox, related discussion #270 can be found
![image](https://github.com/Esri/solutions-components/assets/138827632/9a3a7225-4e95-4769-81d9-127116ebb1a4)

**Comment by avezina** [comment]
Discussing overlap here as well https://github.com/Esri/solutions-components/issues/270#issuecomment-1716736485
