### ISSUE TITLE
Information Panel styling

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#327]
Some minor styling feedback on the information panel section:

- [x] Can we remove the padding on the element containing the pop-up/edit widget and the row containing the back/next buttons? I am not seeing it in the original design and seems like we can get some additional space back:
   ![image](https://github.com/Esri/solutions-components/assets/6796763/b687fc93-1b43-43bd-b4a3-61ac8d4ba166)

- [x] Can we add a little gray border above the row containing the back/next buttons to help separate it from the pop-up content? This is also in the Figma design:
   ![image](https://github.com/Esri/solutions-components/assets/6796763/59ccf499-0a8d-4847-ae64-621f8b7fab42)

- [x] When you edit a record there looks to be a double border between the bottom of the header and the top of the edit form. When you start to scroll down it looks better. Wondering if there is a way to remove the double border between these elements.
   ![image](https://github.com/Esri/solutions-components/assets/6796763/8e368377-abba-4a01-86ef-cb9e3970a5bb)

- [x] Can we make the background of this entire element white? So in cases where the pop-up doesn't fill the area the background is still white
   ![image](https://github.com/Esri/solutions-components/assets/6796763/8835d9a1-194a-4b47-a59f-8ce2cf138f08)

**Comment by azizaparveen** [comment]
@jmhauck looks like there is a bit of gray background showing up in the related table records section as if the width of this section is a bit smaller than the pop-up
Also wondering if we could add a thin border on the top row of the related records and add a bit more padding below comments like the screenshot below

![image](https://github.com/Esri/solutions-components/assets/138827632/1cbe0d1d-e0f8-4b77-b328-007732c4c7f3)

**Comment by jmhauck** [comment]
@azizaparveen where are you testing that shows the gray on the sides? We'll have to keep an eye on all these as they are overrides to the basic design of the Features widget

**Comment by azizaparveen** [comment]
@jmhauck it is in the demo app, with Popup configured map, it starts right below the status bars in the pop-up
![image](https://github.com/Esri/solutions-components/assets/138827632/a54eb5ce-306d-4124-9a3c-358ca52d4efd)

**Comment by jmhauck** [comment]
@azizaparveen added some padding and a border at the top and bottom of related records in Features widget as well as in the Editor widget display. Can be see on the dev demo machine now and devext tomorrow. Let me know if you seen anything else

**Comment by chris-fox** [comment]
@jmhauck. @azizaparveen, My only concern is inserting something into the Features widget display if the team changes the styling of these elements in a future release and it causes it to look weird.  Could i get a little more info on what was causing the grey background to display on the sides of the pop-up. Just curious why we needed to add the padding and border on the related records element.

**Comment by azizaparveen** [comment]
> @jmhauck. @azizaparveen, My only concern is inserting something into the Features widget display if the team changes the styling of these elements in a future release and it causes it to look weird. Could i get a little more info on what was causing the grey background to display on the sides of the pop-up. Just curious why we needed to add the padding and border on the related records element.

@jmhauck had a discussion with Chris, he suggested to not make padding and border changes, instead we should reach out to the map viewer team about these concerns, could you please revert these changes back? So sorry that you had to do extra work for this.

**Comment by avezina** [comment]
@jmhauck  Observed today that the title no longer appears to be centered in the Info panel heading. Not sure if this is a recent change and perhaps that header doesn't need to be so thick?
![image](https://github.com/Esri/solutions-components/assets/50338557/2c94693f-963a-4a32-b021-28d43e39a60d)

**Comment by jmhauck** [comment]
This is due to a change in the JS API 4.28.

**Comment by azizaparveen** [comment]
Verified the changes in devext
