### ISSUE TITLE
Edit Button is overlapping pop-up title

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#328]
![image](https://github.com/Esri/solutions-components/assets/6796763/77be5bd5-aa10-47eb-bf81-049ba68a0e5b)

We can't control how large the pop-up title is and it will grow with the content which can cause the edit button to overlap the text. We could change the button appearance to outline-fill so it displays solid over the text:

![image](https://github.com/Esri/solutions-components/assets/6796763/6a9e14c0-72a6-4036-91fa-58349aa5f24d)

But it still obscures some of the pop-up title. I am wondering if we should go back and consider a design where the edit button is in the bottom bar. This is something that comes to mind to me:

On one side we display the calcite Pagination control to allow you to navigate the records and on the other side we have the Edit button. Another thing we could do in this design is we could make the Edit button a Split Button where the primary action is a single record Edit, and the secondary action is the Edit Multiple or Edit All for batch editing.

Thoughts?

**Comment by avezina** [comment]
@chris-fox Good idea, could align with the map popup navigation: 
![image](https://github.com/Esri/solutions-components/assets/50338557/931a3826-bd13-40d2-b811-c1a14ab7f2c6)

maybe something sort of like this? (debating between side-by-side navigation arrows or having the paging in the middle).
![image](https://github.com/Esri/solutions-components/assets/50338557/f3b90285-66ad-43cf-b932-b83bd0e655c6)
That picker in the middle could work like the popup in the map, where I can open up a feature's popup from the picker without having to navigate the arrows one at a time.
![image](https://github.com/Esri/solutions-components/assets/50338557/054bd8d6-b6bd-4cd7-8ac0-7d2bf53690eb)

My only concern with having the Edit button as a "general/high-level" button is how we'll be able to differentiate between edit 1 single feature vs edit multiple. We can always solve this in the future.

**Comment by azizaparveen** [comment]
@chris-fox @avezina I personally liked the edit button on top, can we use padding like the screenshot below,
We raised our concern about batch editing but IA team didn't discuss that in detail and basically saying they will think about that in future when batch editing will be available and they expect that jsapi team will come up up with some design solution for this. 
![image](https://github.com/Esri/solutions-components/assets/138827632/0726543d-a1f3-4ce4-a18f-a26e261e8aa3)

**Comment by avezina** [comment]
@azizaparveen The more I look at this and the more I wonder if it makes it look like I'll be editing the title?
![image](https://github.com/Esri/solutions-components/assets/50338557/fadd88c2-4dd5-42b7-9947-9a6f5167b226)

**Comment by azizaparveen** [comment]
Yeah I see what you are saying

**Comment by azizaparveen** [comment]
How about something like this? Also we can ask Lucy to look into this as well.
![image](https://github.com/Esri/solutions-components/assets/138827632/8d3e7a73-5471-4804-8b64-f7b1b8fe019c)

**Comment by chris-fox** [comment]
It is also possible for a pop-up to not have a title, in which case the Edit button would overlap with the content of the pop-up:

![image](https://github.com/Esri/solutions-components/assets/6796763/21696d20-a09d-4d8c-b946-9c25af079440)

Another thing I find confusing with the Edit button within the pop-up is if I view a related record from the pop-up it makes me thing the Edit button will edit the related record, when you are actually still editing the feature.

Can we put the Edit button in the Information Bar?

I am also good with the look at the bottom that Alix proposed.

**Comment by azizaparveen** [comment]
Final design, hoping everyone agrees and no major concern with this design.
it will be right on top of the next buttons and have it be sticky that way it's always visible. 
![image](https://github.com/Esri/solutions-components/assets/138827632/d020c245-cbf2-410d-ad17-5e0f8b57d436)

**Comment by avezina** [comment]
Looks good to me!

**Comment by azizaparveen** [comment]
Verified in devext
