### ISSUE TITLE
Table is not honoring field aliases overridden in the web map

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#329]
It is possible to override the field aliases on a layer within the web map, this setting is persisted in the web map and is not written to the service. Here is a sample web map: https://www.arcgis.com/apps/mapviewer/index.html?webmap=5fb9d9f9201747f7b921a37c420c222e

If you open the table in the Map Viewer it will display the overridden field alias coming from the layer in the map 'Map Override Alias" for the column heading.

If you open the same map in Manager it is displaying the field alias coming from the feature service as the column heading "Test Really Long Alias Name"

**Comment by jmhauck** [comment]
Notes: Looks like we can override in the table using TableTemplate > ColumnTemplate label prop. Just need to understand where to get these overridden names from. The Features widget seems to handle this automatically but the FeatureTable and Editor do not. Will still need to look into the editor to see what options we may have. Also seems like the js api widgets should handle this in a specific way.

**Comment by chris-fox** [comment]
@jmhauck, I think the Editor widget is ok. It is possible to change the Form Alias name directly, I did that in the sample map above to give it a custom name and it is honored by the Editor widget.

**Comment by jmhauck** [comment]
Ok...so I see we can find 'Map Override Alias' at:

`layer.popupTemplate.fieldInfos[1].label`

I'll add a check for this

**Comment by jmhauck** [comment]
@chris-fox should this also honor visible setting from popupTemplate?

**Comment by chris-fox** [comment]
@jmhauck, no I don't think we can leverage that property because there is no way to set it anymore in the new Map Viewer, it was the property we used in the old Crowdsource Manager because you could set it in the Classic Map Viewer.  I think for now field visibility will have to be an app config until the Map Viewer team adds back functionality to define which fields are visible.

**Comment by jmhauck** [comment]
@chris-fox ok....will remove the visible check

**Comment by chris-fox** [comment]
Verified in Dev
