### ISSUE TITLE
Add support for URL Parameters

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#330]
In Crowdsource Manager we support the ability to launch the app and open a specific map, layer and select a specified record in the layer. I would like to continue to support this for the new Manager app. I would propose we use the same parameters:

webmap=Item ID of the web map
layer=id property of the layer in the web map. Unique ID of the layer
oid=Object ID of feature

So for example the url would look something like this: appUrl?webmap=ce3dec81bf714d3bb71da9691ab686d1&layer=Requests_681&oid=3

We should also support using the webmap parameter by itself to set the selected webmap and the webmap and layer parameter together to set the selected layer. The oid parameter can only be used with both the webmap and layer parameters.

Additionally I would like to support a globalid parameter in place of an oid parameter.. There are many cases where we can get the globalid from a feature but not a oid, so this would give us more flexibility in setting the selected record.

This feature is not needed for Beta, but would like to have for Final release.

**Comment by jmhauck** [comment]
@chris-fox after this and the supporting PR for the App are merged this will support webmap, layer, oid, and globalid. Should oid be removed? Planning to wait until we are 100% done with patches before merging.

**Comment by chris-fox** [comment]
I am good to keep oid and globalid, although only one will work. Do you have a default if both are specified? I would lean towards globalid.

**Comment by jmhauck** [comment]
Wanted to talk about it first. Right now if both were provided they would both be executed but globalid would happen after so it would seem like its the default. I'll make globalid the default.

**Comment by azizaparveen** [comment]
Consider passing multiple ids

**Comment by jmhauck** [comment]
multiple object ids or global ids are supported:

`?oid=1,2,3`

And same for `globalid`

**Comment by jmhauck** [comment]
available for review on dev0009449

**Comment by azizaparveen** [comment]
@jmhauck  the Share tool in the config will handle the url parameters in Manager, we need to connect your code to this parameter 
![image](https://github.com/Esri/solutions-components/assets/138827632/bd4678b0-9508-4f75-b29f-6e1a07303543)

**Comment by azizaparveen** [comment]
Looks good when using objectid but seeing issue with globalid, it is not working for me in Manager https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=95fbb3d74e914b019a79fffb9235f975&webmap=4fda74bc0da54a19887ce7220f142804&layer=18afca99505-layer-3&globalid=b885a497-ffc4-4a33-a1a6-f23aaa0f9d18&center=-88.162;41.7848&level=13.

**Comment by azizaparveen** [comment]
Verified in devext

**Comment by azizaparveen** [comment]
url parameter is working in devext but not in qa

**Comment by azizaparveen** [comment]
Verified in qa
