### ISSUE TITLE
Field reordering dev work

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#334]
In our meeting today with IA team, Kelly mentioned that she will add the field visibility component in the configuration but she won't probably have time to work on field ordering part, she suggested if John has time, she can guide John to resources so we can have this in beta.

We need to make sure only editable layers are showing up in the layer picker for field visibility and field reorder in configuration since only editable layers will show up in the layer picker at runtime

**Comment by chris-fox** [comment]
@azizaparveen, let's also make sure editable tables show up in this UI as well. Want to make sure standalone tables are fully supported in this app as well.

**Comment by azizaparveen** [comment]
This looks good in qa
