### ISSUE TITLE
Export button keeps spinning when pop-up is configured to use related records

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#351]
Export button keeps spinning when pop-up is configured to use related records and console error is showing up

**Test app**: https://solutions.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=9674bc996ed14b1a97fed42f2f778415
**Test map**: https://solutions.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=59f3c772ed754185b797f39739b0cfa0

All Owners and Occupants layer has a related table, the parent layer pop-up has a related table element and related table has it is own pop-up set up.

**Repro steps:**
1) Launch the test app, Click "Create a new List" button
2) Select All Owners and Occupants as input layer
3) Use the rectangle sketch tool and select a record, click Done.
4) Click on the Export button and notice that the Export button gets unresponsive and console error shows up.

![image](https://github.com/Esri/solutions-components/assets/138827632/00eb25b5-f27a-447f-b5cf-3a752b69a729)

**Comment by azizaparveen** [comment]
cc @HeatherEisan

**Comment by MikeTschudi** [comment]
@azizaparveen & @HeatherEisan, fix is in devext.

**Comment by azizaparveen** [comment]
Verified in devext, @HeatherEisan could you please on your side?

**Comment by HeatherEisan** [comment]
@azizaparveen: Verified in dexext.
