### ISSUE TITLE
When related table it added in the map, it automatically shows up in the input and selection layer dropdown in Public Notification

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#352]
The test map has 4 layers and a related table, In PN app, all four layers and the table are showing up in the input layer dropdown at runtime, even though the related table does not show up in the configuration to be selected as input layer. We should only show feature layers in the input and selection layer dropdown box
**Test map**: https://solutions.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=59f3c772ed754185b797f39739b0cfa0
**Test app**: https://solutions.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=9674bc996ed14b1a97fed42f2f778415
![image](https://github.com/Esri/solutions-components/assets/138827632/9c7d1677-a0ab-4277-947c-e422401015a0)
![image](https://github.com/Esri/solutions-components/assets/138827632/f6d0ca2d-46c8-4d25-bcf6-c013c1fb1049)
![image](https://github.com/Esri/solutions-components/assets/138827632/0779ee84-6521-41c0-a2e8-74a3647fbc98)

**Comment by azizaparveen** [comment]
cc @HeatherEisan

**Comment by azizaparveen** [comment]
This is verified in devext

**Comment by azizaparveen** [comment]
@HeatherEisan could you please check?

**Comment by HeatherEisan** [comment]
@azizaparveen verified in devext.
