### ISSUE TITLE
Address search result is missing the pointer on the map

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#359]
Searching for an address should add a pointer on the map. Right now, it only zooms to the map location.
![image](https://github.com/Esri/solutions-components/assets/50338557/3f0d8eef-27e9-4fb8-a197-ba4580fee16d)

Compare with Map Viewer
![image](https://github.com/Esri/solutions-components/assets/50338557/9b7cf596-06b1-4c3a-a78c-f9261dca8c1a)

Compare with simple JS map: https://codepen.io/avezina/pen/bGOjNrX
![image](https://github.com/Esri/solutions-components/assets/50338557/a085aafd-f27d-4704-add9-5d87143ebcde)

I would not expect a popup to show, but at least the indicator.

**Comment by azizaparveen** [comment]
verified in devext
