### ISSUE TITLE
The Zoom button pans and does not zoom to a single feature

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#360]
When only a single feature is selected, the Zoom button pans to the feature instead of zooming to the feature.
The Zoom behavior is working as expected when 2+ features are selected.

Observe the behavior below:

https://github.com/Esri/solutions-components/assets/50338557/07290059-20fd-489f-83f6-aa2cc0a5d961

**Comment by jmhauck** [comment]
This is leveraging the FeatureTable zoomToSelection function.

**Comment by avezina** [comment]
@previnWong Is this the same issue we're seeing in UNT widget? Do you all think we need to report a bug?

**Comment by avezina** [comment]
Should we hard code a zoom level for single point features?

**Comment by chris-fox** [comment]
The functionality is consistent with the Map Viewer zoom function from the table today, so I would vote to keep it the same for now.

**Comment by chris-fox** [comment]
@azizaparveen, @skrishn, I was testing Reporter today and noticed that when you have a point and you select it in Reporter we are zooming in really close to the point. It looks to be the highest zoom level we have which for me is too close. Could we come up with a consistent zoom scale for points in manager and reporter? I am ok with hard coding it, but maybe we come up with a good compromise on how close.

**Comment by azizaparveen** [comment]
@chris-fox @skrishn 
Played with the zoom level in Experience builder
1) For point features, 1:50000 looks good to me
![image](https://github.com/Esri/solutions-components/assets/138827632/a5f6c558-df9b-4306-a26c-ba2082317279)
2) For other geometries we can get the extent and expand by 1.5 or 2. In Near Me we are using expand factor 1.5 
![image](https://github.com/Esri/solutions-components/assets/138827632/090a964a-b62d-43a3-96ca-4d7b4ca861a7)

Please let me know your thoughts.

**Comment by chris-fox** [comment]
i'm good with that. @skrishn? Would like to keep consistent between Manager and Reporter

**Comment by azizaparveen** [comment]
In our last meeting with Instant apps team,  we decided to use the zoom to scale component used in other IA apps like Sidebar, for the time being it will be map specific not layer, once this is added in the template we need to update the component to work with this option.
![image](https://github.com/Esri/solutions-components/assets/138827632/d2bf1096-69bd-4d07-bab0-88d62f3228e8)

**Comment by sumitzarkar** [comment]
@azizaparveen 

This needs changes in the Instant App, once configration changes are implemented we can implement it in the component

**Comment by sumitzarkar** [comment]
@azizaparveen @skrishn @jmhauck 

If you could share the json data which will be passed to widget. we can configure that in the demo app and work on this functioanlity.

**Comment by jmhauck** [comment]
@sumitzarkar When I configure sidebar and look at what they save they add a searchScale prop:

`"searchScale": 142064`

**Comment by sumitzarkar** [comment]
@jmhauck 

Thanks for the updates, for now we will create a prop zoomScale in both the component.

**Comment by skrishn** [comment]
@jmhauck will this fix fix this issue? https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9806. Sumit mentions zoomScale, and but Brandon added zoomToScale.

**Comment by jmhauck** [comment]
When implemented this will fix the issue you mention above. I added the prop to reporter as `zoomToScale`. Sumit and team will still need to add the supporting implementation for this.

**Comment by sumitzarkar** [comment]
@jmhauck 

As discussed on the call yesterday we have implemented the code for zoomToScale:
- zoomToScale will be optioanl param to highlight method and goToSelection method
- When only one point feature is passed to goToSelection, we will use the passed zoomScale value 

This is working as expected, we will deliver this in today's code drop. 

Please check and let us know if any changes requried.

@FYI - @azizaparveen @skrishn @avezina

**Comment by prachichawande-ct** [comment]
@avezina @azizaparveen 

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impact at runtime Zoom feature functionality|  When the single feature is selected from the layer table and the Zoom button is clicked then the selected feature should be zoomed
||When the multiple features are selected from the layer table and the Zoom button is clicked then the selected features should be zoomed|
||The zooming should be done with the configured zoom scale value|

**Comment by azizaparveen** [comment]
Looks good in Manager
