### ISSUE TITLE
Layer geometry becomes editable when edit button clicked in the information panel

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#369]
After I select a record from the table, when I click Edit button, the feature geometry becomes editable
Test app: https://holistic.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=c1c09555a4d24ab7982293fac9590af8
Test map: https://holistic.mapsdevext.arcgis.com/home/item.html?id=e443af6208f6482d8737c406bdbcb17d
**Note**: Seeing this behavior in polygon layers, not in point layer

![image](https://github.com/Esri/solutions-components/assets/138827632/3c20deac-2be7-42f7-bba8-e5005c9092de)
![image](https://github.com/Esri/solutions-components/assets/138827632/b1b7f8ad-b0a0-4f6b-825d-8a58d032aaad)

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by jmhauck** [comment]
@azizaparveen ready to test tomorrow

**Comment by azizaparveen** [comment]
@jmhauck it is not going to editing mode anymore but the selected polygon turns black, are you seeing the same thing?
![image](https://github.com/Esri/solutions-components/assets/138827632/33b8506a-b3c6-47bf-b4ab-ffb546e94863)

**Comment by jmhauck** [comment]
@azizaparveen yes...that is the default. Could possibly override by setting various defaults on the editors supporting widgets. I can explore that if its desired. What would be a preferred symbol to use if we are going to override?

**Comment by azizaparveen** [comment]
@jmhauck I am thinking of no fill symbol with just cyan outline 
![image](https://github.com/Esri/solutions-components/assets/138827632/8248057f-bc38-4543-9ab1-35c1b019357a)

**Comment by jmhauck** [comment]
@azizaparveen makes sense. Looks like this is a change at 4.28 with 4.27 it was highlighted like we would like. Have followed up with Editor folks. I tried setting various props on the Editors supporting widgets but could not see a workable solution.

**Comment by avezina** [comment]
Related JS bug being resolved: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/56151

**Comment by azizaparveen** [comment]
@jmhauck the black symbol does not go away after unselect the feature or if click the clear selection button
![image](https://github.com/Esri/solutions-components/assets/138827632/8bf6f58f-f465-4080-bce5-6ec87bc3beb8)

**Comment by azizaparveen** [comment]
@avezina even though they said it is resolved in js api, I still see black polygon in Manager, I tried in incognito mode, same result

**Comment by avezina** [comment]
![image](https://github.com/Esri/solutions-components/assets/50338557/a67499c1-60ed-420a-aecf-b2a742ca1d7c)

@azizaparveen While this may be fixed in jsdev 4.28, it has not yet made it to the js 4.28 release candidate build, which is what devext Instant Apps are pointing to.

John pointed out that we can see dependencies here: https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/blob/master/instant/manager/package.json
`"@arcgis/core": "^4.28.0-rc.0"`

Let's test it again later or tomorrow.

**Comment by azizaparveen** [comment]
This looks good in devext

**Comment by azizaparveen** [comment]
@jmhauck I can see the geometry becomes editable again, here is a test app https://webapps.maps.arcgis.com/apps/instant/manager/index.html?appid=3d87d41fe1044985ad938ffedb285bf0. 
@sarahmcdonald7

**Comment by jmhauck** [comment]
@chris-fox @avezina This was enabled again when we decided to go back on the adding of related records. Seemed like it would be weird to be able to add a record but then not modify it? I can turn it back off. What would you like to do?

**Comment by chris-fox** [comment]
@jmhauck, in that scenario could we allow updating the related feature attributes but not its geometry?  I would lean towards this approach if we can and then we can think we want the UX to be for editing and creating geometry of features for the next release.

**Comment by jmhauck** [comment]
Ok, will do

**Comment by azizaparveen** [comment]
Verified in devext
