### ISSUE TITLE
When using group layer Manager is showing error that Map does not have any editable layer but the layers are editable

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#370]
When using group layer, Manager is showing error that Map does not have any editable layer but the layers are editable
Test map: https://sg-em-devext.mapsdevext.arcgis.com/home/item.html?id=92a2b0c8b3f9467aa868925428e3ec87
Test service : https://sg-em-devext.mapsdevext.arcgis.com/home/item.html?id=be53bed2c5e3459cba7c30bb9b7c93ba&view=service
![image](https://github.com/Esri/solutions-components/assets/138827632/919a57ca-7fae-4074-9f47-deba76f77759)

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by jmhauck** [comment]
@kellyhutchins

**Comment by kellyhutchins** [comment]
@sarahmcdonald7  can you create an issue for me in the config panel repo and I'll fix this one.

**Comment by sarahmcdonald7** [comment]
@kellyhutchins yep! I will get something logged

**Comment by sarahmcdonald7** [comment]
@azizaparveen Can you share the map/layer that you mentioned in the issue?

**Comment by azizaparveen** [comment]
@sarahmcdonald7 the map is publicly shared now, but it is in one of our org, will this work?  https://sg-em-devext.mapsdevext.arcgis.com/home/item.html?id=92a2b0c8b3f9467aa868925428e3ec87

**Comment by sarahmcdonald7** [comment]
@azizaparveen Thanks, I actually think I am good. I thought the issue was with all group layers but was confused because all the maps I tested with yesterday used group layers. But I found that the error only appears when maps use group layers that were created in Map viewer. All the maps I was using yesterday had "group layers" because the feature layers were in a feature service.

**Comment by azizaparveen** [comment]
Closing this since this needs to be fixed at the template and tracking it in https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/4058
