### ISSUE TITLE
When Information panel is expanded, clicking on the Edit button does not go to editing mode

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#371]
When Information panel is expanded, clicking on the Edit button does not go to editing mode
Test app: https://holistic.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=c1c09555a4d24ab7982293fac9590af8

**Reproducible steps:**

1) Launch the app, 
2) Select a record
3) Click expand button in the information panel
4) Once the Information panel expanded, click Edit
5) Notice that Editor widget does not go to editing mode and console error shows up.

![image](https://github.com/Esri/solutions-components/assets/138827632/ba57aeaa-3d91-4ca4-aa34-f781e0856f97)

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by avezina** [comment]
Yeah they made a change to the display of the Select button: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/51877

**Comment by avezina** [comment]
Related JS issue: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/56092
![image](https://github.com/Esri/solutions-components/assets/50338557/206f20d7-df60-45b2-a8f8-c57cea07d8ef)

**Comment by azizaparveen** [comment]
This looks good in devext
