### ISSUE TITLE
Update to scroll behavior in edit mode

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#373]
Is it possible to doc the Edit feature header to the top and the Update/Delete buttons to the bottom of the panel and have the scroll before all the content in between?

Currently if you edit a feature and the edit widget is larger then the vertical space available you get a scroll bar. If you scroll down the Edit feature header and back navigation is moved off the screen and you have yo scroll to the bottom to get to the Update and Delete buttons.

Ideally the Edit feature header would always be visible at the top and the update/delete buttons would always be visible at the bottom and you would just scroll through the rest of the form. Not sure if this is possible, but thought it would be an improved experience while editing.

**Comment by jmhauck** [comment]
@chris-fox could I see an example? This should be the way it is already.

![image](https://github.com/Esri/solutions-components/assets/2170893/31aed8a5-2916-4970-9d51-4b086b2fc100)

**Comment by chris-fox** [comment]
I am able to reproduce in this app in devext:

https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=bd57063681644c4dbda2ec44cbc16823

**Comment by jmhauck** [comment]
@chris-fox on devext tomorrow

**Comment by chris-fox** [comment]
verified
