### ISSUE TITLE
Expected behavior when you click Update to edit a feature

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#374]
I was testing this today and expected when I clicked Update that it would take me out of the edit mode and I would see the resulting pop-up. Instead I am finding that it briefly takes me to the select a feature page and then back to the edit feature page.

So question, do we think clicking Update should commit the changes and take you out of edit mode or commit the changes and keep you in edit mode? I find in the Map Viewer it takes you out of edit mode, although I know we have had feedback in other cases where it would be nice to keep you in edit mode.

If we decide to keep the current behavior, I am wondering if it would be possible to not have the UI bounce to the other page and then back to the edit mode. Or if we can't do that we implement a similar loading cursor as we did in #322 so we don't see the other page.

Thoughts @jmhauck, @avezina, @azizaparveen?

**Comment by azizaparveen** [comment]
@chris-fox I personally think it should commit the update, go out of the edit form and show the pop-up info like the screenshot below. IA team has this logged on in their repo as well.
 https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/8801. 
![image](https://github.com/Esri/solutions-components/assets/138827632/6d497cbc-8211-471a-82e5-669268f72146)

**Comment by jmhauck** [comment]
@chris-fox ya..based on how the Map Viewer does it and that issue they logged in the IA repo I switched it yesterday to close the Editor after update. Should be in tomorrow. Happy to adjust if we decide to go another route.
