### ISSUE TITLE
Layers are listed in reverse order in the layer picker dropdown

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#377]
Layers from the web map are listed in reverse order from the web map's TC in the layer picker dropdown.

Example: https://www.devext.arcgis.com/home/item.html?id=f4ee84a37f57465bbc4f4d27f54bb195
![image](https://github.com/Esri/solutions-components/assets/50338557/75e92b5d-31b6-4f58-aa26-8979b9a34fdc)
![image](https://github.com/Esri/solutions-components/assets/50338557/9a8c543f-a7f2-428d-8f94-f8633665a4f4)

**Comment by jmhauck** [comment]
@avezina on devext tomorrow

**Comment by avezina** [comment]
Tested in dev, order looks correct now 
![image](https://github.com/Esri/solutions-components/assets/50338557/69894e22-c109-44ff-9891-99c92ec88b8c)
