### ISSUE TITLE
Review behavior when unselecting a feature loaded in Editor

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#381]
If multiple features are selected and one of the features is being edited, if that feature is unselected the Editor is not cleared and keeps displaying the form for the unselected feature.

https://github.com/Esri/solutions-components/assets/50338557/37c2b2af-a5c5-4d22-908c-6ef6f47324cd

Steps:
1. Select multiple records
2. Edit one of them
3. Unselect the record you are currently editing: the editor is not cleared and still shows the form for the unselected feature.

Suggestion for expected behavior:
- No edits were made: Clear the form and fall back to the information panel for previous selected feature in list.
- Some edits were made: Should unselecting the record currently being edited act as discarding an edit and display the appropriate modal before clearing the Editor?
![image](https://github.com/Esri/solutions-components/assets/50338557/8a6b1a72-3cde-46d4-8a50-4abbd0addea0)

cc @chris-fox @azizaparveen

**Comment by azizaparveen** [comment]
@avezina I agree with your expected behaviors, when some edits are made but update button is not clicked, instead the record is unselected, I think we should display the discard edits modal in this scenario before exiting editing mode.

**Comment by jmhauck** [comment]
Will likely need to talk through more of this. Tomorrow if the editor is open and the selection in the table changes the editor will be closed...the feature just selected will be shown. If edits have been started they will be discarded. I have not been able to get the Discard model to show by calling anything on the editor yet other than clicking its back button. Will likely need to ask JS team about this.

**Comment by avezina** [comment]
@jmhauck If there isn't a way to show the modal right now, we can fall back to the behavior we currently see elsewhere (Web Editor prototype and ExB); edits are discarded, editor is closed, and no modal is shown.

**Comment by jmhauck** [comment]
@avezina We can show a modal...would just have untranslated strings. Modal or no?

**Comment by jmhauck** [comment]
@avezina what do you think...are we doing anything else for this one this release?

**Comment by avezina** [comment]
@jmhauck Modal sounds good, beta app doesn't get translated anyway?

**Comment by jmhauck** [comment]
@avezina Ok, sounds good. Will add it. 

I think its more like we are not "on the hook" for everything to be translated but most of it is.

**Comment by jmhauck** [comment]
@avezina if they choose to continue editing...should the feature be re-selected in the table?

**Comment by azizaparveen** [comment]
Need to reach out to Editor team

**Comment by azizaparveen** [comment]
Suggested behavior:

- [ ] No edits were made: Clear the form and fall back to the information panel for previous selected feature in list.

- [ ] Some edits were made: unselecting the record currently being edited act as discarding an edit and display a modal before clearing the Editor and fall back to the information panel for previous selected feature in list
if user choose to continue editing, that feature will be reselected in the table again.

**Comment by sumitzarkar** [comment]
@azizaparveen 

As discused yesterday, please check and let us know if any changes requried in this as we are not observing any issue

**Comment by azizaparveen** [comment]
@sumitzarkar this issue is not reproducible anymore
