### ISSUE TITLE
Total count shows the actual number of records when web map has filter set up and no record matches the filter conditions.

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#385]
In today's testing session, this preset filter issue came up.  Both Ryan Nosek and and Ryan Cosby deployed solutions and used the maps form the deployed solution to test manager. The maps have filters set up,  so no feature showed up in the map.

In Manager, the table shows no records in the table but the total count shows the actual number of features at the bottom of the table, the count should be 0.

Test App: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=462ee6026e134b99bdbae8824d0ae479
Test Map: https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=4fda74bc0da54a19887ce7220f142804

**To repro**

1) Launch the app and navigate to Road problems manager map
2) CP Roads - Citizen Problems layer has filter set up 
3) Notice the total count value

In Experience Builder and ArcGIS Pro, the practiced behavior is to show 0 as total count in this scenario.

![image](https://github.com/Esri/solutions-components/assets/138827632/614fe468-be7b-4a94-a9b9-05227f819238)

![image](https://github.com/Esri/solutions-components/assets/138827632/e1ab1a9e-f412-4b38-967c-49be7b2be4cc)

![image](https://github.com/Esri/solutions-components/assets/138827632/97610916-363b-448a-9ed3-855099e1bf69)

**Comment by jmhauck** [comment]
@azizaparveen I don't see a way for us to ask the FeatureTable for the count information so it requires an extra query. I set it to honor the layers definitionExpression. Should be good on devext

**Comment by azizaparveen** [comment]
Verified in dev
