### ISSUE TITLE
Restrict related feature geometry editing

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#386]
The JS team implemented the ability to edit feature-to-feature related records. This is available out of the box in the Editor widget, which we are using in Manager.
https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/55676

In Manager, we do not currently support editing features geometries in the map, but the current behavior when adding a related feature in Manager allows you to sketch on the map. It's also possible to change a related feature's geometry when accessing it through the parent layer.
Since we do not support editing the geometry of features for feature layers, we should also block the ability to edit the geometry of features for related feature layers.

For the first release we should:
- [ ] Support creating and updating related records.
- [ ] Support updating the attributes of related features.
- [ ] Not support creating new related features.
- [ ] Not support updating the geometry of related features.

@jmhauck I'm not sure how much flexibility we have in restricting editing related features.

cc @azizaparveen @chris-fox

**Comment by jmhauck** [comment]
@avezina edit geometry is blocked via [LayerInfo](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Editor.html#LayerInfo) object `geometryUpdatesEnabled` when we create the editor

**Comment by jmhauck** [comment]
@avezina looks like we can add a LayerInfo object with `geometryUpdatesEnabled` for all layers in the map when we create the editor and it will handle the no geom edits side of this issue.

However, if I pass `addEnabled = false` with each as LayerInfo the "Add feature" button still shows below the related records. Seems like we will need to discuss this with the Editor folks.

Also seems like it only highlights the related features when you hover over the related records in some situations. I'd guess if the first selection is on the parent it would show the kids but not the other way around.

**Comment by avezina** [comment]
@jmhauck If you have the time, could you put together a code sample to repro the issues you described above so we can easily log issues in the JS repo?

**Comment by jmhauck** [comment]
Got a workaround for the add issue from the Editor team. 

Only remaining issue that I'm aware of is when you are editing a related record and click the back button the editor is closed.

**Comment by jmhauck** [comment]
PR is in and will be on devext tomorrow

**Comment by avezina** [comment]
The current fix watches related record callbacks and sets it to null. Right now it does not distinguish between related records (tables) and related features (feature layer).

This means that we will not support adding related features, but also we will not support adding related records at this time.

@chris-fox @azizaparveen are we OK with this limitation for this release?

**Comment by chris-fox** [comment]
@avezina, no I would rather have support back for both if that is the case. Having support for related table records is critical to most manager workflows today.
