### ISSUE TITLE
When single record is selected, zoom button is panning to the feature instead of zooming

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#389]
When single record is selected, zoom button is panning and centering the feature instead of zooming but it works as expected when multiple records are selected
Test app: https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/manager/index.html?appid=2e5b78ee95b34268ae952daf8ca8fc66
![Managerzoomissue](https://github.com/Esri/solutions-components/assets/138827632/0acc5b50-965d-4678-88fb-e5876d3b5299)

**Comment by avezina** [comment]
@azizaparveen I keep seeing this everywhere too, and it annoys me as well... but it is as designed I believe. The functionality is consistent with the Map Viewer zoom function from the table and the docked popup. We've the same issue in UNT widget. https://devtopia.esri.com/ali10256/utilitynetworktrace/issues/156

**Comment by avezina** [comment]
@jmhauck maybe there's an option to hardcode a zoom scale?

**Comment by jmhauck** [comment]
#360 I thought the plan was to leave it as is for now?

**Comment by azizaparveen** [comment]
Sorry missed that issue, closing it

**Comment by avezina** [comment]
ha yeah looks like we have a duplicated issue and I forgot we discussed this for Manager already, I'm still fine with leaving it.
