### ISSUE TITLE
Export button is not responding in Public Notification

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#391]
In the test map, pop-up is set up to fetch address information from the related table.

Test map: https://sg-em-qaext.mapsqa.arcgis.com/apps/mapviewer/index.html?webmap=cc7ad763cf0e42ea84385539e139dc25
Test App: https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/notification/index.html?appid=08596bd779e7421d9c48b1b3720fb156

To repro:
1) Select a single record
2) Turn on the search distance, default unit is kilometer, looks like it is breaking after I change the search distance.
3) Go to the Export tab and click Export, notice the console error and export button not responding

![image](https://github.com/Esri/solutions-components/assets/138827632/6adc5ffc-fa8a-437e-9250-8e41e75fc0ba)

**Comment by MikeTschudi** [comment]
The first error message in the console is appearing after I click the app's "Create new list" button. The translations are accessed in buffer-tools before the component's `componentWillLoad` method is called, and so the translations are not yet defined.

Mostly repeatable in devext; doesn't occur on local development computer.

**Comment by jmhauck** [comment]
@MikeTschudi also seems like something is off if you test with her data locally. The relationship checking in `_getLabelFormat` is returning no layers and various errors follow downstream. The `layer.popupTemplate.content[0].relationshipId` is the same as the current `layer.layerId`

**Comment by azizaparveen** [comment]
verified in dev
