### ISSUE TITLE
Export button spins after selected a related record

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/solutions-components#393]
The Export button spins after a related record is selected.

1. Go to [Public Notification app](https://solutionsqa.mapsqa.arcgis.com/home/item.html?id=e07911269154414992998129b70f253d)
2. Click View.
3. Click on Create new list.
4. Click the Input layer drop-down menu and choose All Owners and Occupants.
5. Type 1804 N Naper Blvd into the search box.
6. Use the rectangle tool to select the point.
7. Click Done.
8. Click the Export tab.
9. The Export button spins
 
If the app is closed and opened, the issue doesn't seem to exist. It's only appears after I deploy the solution and follow the steps above. The solution isn't in the app yet because I am waiting for the agol branch to be created.

**Comment by azizaparveen** [comment]
Can't repro this anymore @HeatherEisan could you please check this one more time?
