### ISSUE TITLE
Legend and Basemap gallery widgets cannot open from the Map action bar 

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#394]
The Legend and Basemap Gallery widgets cannot open from the Map action bar, instead the Expand menu is collapsed.

https://github.com/Esri/solutions-components/assets/50338557/e1a4a0e8-03d5-4b95-85f0-a7e00e60da51

**Comment by azizaparveen** [comment]
@avezina I am also seeing the same issue, in dev Legend is working sometimes but in qa it is not working at all in both preview or launched mode, posted a comment https://devtopia.esri.com/webgis/arcgis-template-configuration/issues/4041#issuecomment-4393899

**Comment by azizaparveen** [comment]
@avezina could you check now, these are working for me this morning
