### ISSUE TITLE
Placeholder text not being honored in Public Notification app

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/solutions-components#408]
Placeholder text not being honored in the Public Notification app.

**App configuration**
![image](https://github.com/Esri/solutions-components/assets/2781011/1070821f-96c1-45ae-beaf-f21f0f217458)

**App**
![image](https://github.com/Esri/solutions-components/assets/2781011/6f5fa632-7531-4bb4-9cab-4e7b24843052)

**Repo steps**
1. Go to [Public Notification Instant App configuration](https://arcgis4localgov2.maps.arcgis.com/apps/configure-template/index.html?appid=ae821bd7323344a099497eb1a20bdbe8).
2. Click Interactivity>Search.
3. See placeholder text image above (screenshot 1).
4. Go to [Public Notification app](https://arcgis4localgov2.maps.arcgis.com/apps/instant/notification/index.html?appid=ae821bd7323344a099497eb1a20bdbe8).
5. Click Create new list.
6. See the app placeholder text above (screenshot 2).

**Comment by azizaparveen** [comment]
Verified in devext
