### ISSUE TITLE
Related records results in PDF are not correct

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/solutions-components#409]
The related records PDF results is not the same as what appears in the map when the point is selected.

**PDF**
![image](https://github.com/Esri/solutions-components/assets/2781011/ea6ad0cd-60a0-491b-ab7b-ae68b4ed5bc8)

**Map**
Related record 1
![image](https://github.com/Esri/solutions-components/assets/2781011/8ca3c7b2-e273-40b0-822f-140638c56370)
Related record 2
![image](https://github.com/Esri/solutions-components/assets/2781011/3a15e399-ce2b-4c66-a9ff-3e5cb4a2cbe0)
Related record 3
![image](https://github.com/Esri/solutions-components/assets/2781011/0ec2706e-68bb-433a-b386-70ef11f0e9ed)

**Repo steps**
1. Go to [Public Notification app](https://arcgis4localgov2.maps.arcgis.com/apps/instant/notification/index.html?appid=ae821bd7323344a099497eb1a20bdbe8)
2. Click Create new list.
3. Click the Input layer drop-down and choose All Owners and Occupants.
4. Type 1804 N Naper Blvd into the search text box.
5. Use the Draw a rectangle to select the point and click Done.
6. Click the Export tab.
7. Click Export.
8. You'll see the results above (screenshot 1).
9. Go to the [Public Notification map](https://arcgis4localgov2.maps.arcgis.com/apps/mapviewer/index.html?webmap=184679b8ae6c4575830176ba64b9037e). 
10. Type 1804 N Naper Blvd into the search text box.
11. Click on the point.
12. Click the > arrow in the pop-up.
13. Click Show all in the pop-up.
14. Click on each of the related records and compare them with the PDF. The results are not the same.

**Comment by azizaparveen** [comment]
@sarahmcdonald7 we are working on this issue right now, looks like it we will be able to patch it next week

**Comment by azizaparveen** [comment]
Verified in devext
