### ISSUE TITLE
Show a list of selected records for navigation

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#417]
We're moving away from adding the Edit button inline with the navigation and doing the following: https://github.com/Esri/solutions-components/issues/328#issuecomment-1719832961

But I am still wondering if it would make sense to leverage the navigation like below, since it would make it easier for users to navigate the popups without having to navigate through all the features until they find the one they want?
![image](https://github.com/Esri/solutions-components/assets/50338557/307782bb-7807-4206-96b7-ec7d3080c0ba)
![image](https://github.com/Esri/solutions-components/assets/50338557/9dfc4c9d-fb18-4030-9a80-865378ecf0e9)

_Originally posted by @avezina in https://github.com/Esri/solutions-components/issues/319#issuecomment-1719916045_

**Comment by jmhauck** [comment]
available for review on dev0009449

**Comment by avezina** [comment]
I like it. @azizaparveen Do you think obvious enough that you can click here? Or should be make any UI changes that would make this stand out more as a button?
![image](https://github.com/Esri/solutions-components/assets/50338557/ea80977a-f9fb-43da-a887-3de6e86d96dc)

**Comment by azizaparveen** [comment]
I like it too, but I don't think it is obvious that it is a button and would show all the features in a list, we can add Show all text in front of it like map viewer or may be we can change the font color to blue to show it is a button 
![image](https://github.com/Esri/solutions-components/assets/138827632/4494ff6e-14f6-419a-8580-542cb148725c)

**Comment by azizaparveen** [comment]
@chris-fox @avezina @jmhauck, I asked Sarah and Lucy to provide feedback on the List button, and Lucy come up with a different design, in fact they were working on this as well. Here is the figma design file https://www.figma.com/file/NwwYvCoSufP3m1nYTZgpB4/Crowdsource-Manager-%7C-23.R3?type=design&node-id=2018-4983&mode=design

- When one record selected, it looks the same as we have now
![image](https://github.com/Esri/solutions-components/assets/138827632/a6de9ef8-f460-4129-8d14-0a387f9637d0)

- When multiple records selected, the list view will appear, click on a record will take to the detail panel
![image](https://github.com/Esri/solutions-components/assets/138827632/ac8f06b6-94da-4b97-9c2e-805ce20d4e71)

**Comment by chris-fox** [comment]
@azizaparveen, my concerns with the multiple records selected design is related to #321. I think this makes it harder to edit a record in the case where I have selected one record, make an edit and then select a second record to edit it. In the design above I select the 2nd record and then I need to click it in the information panel before I can edit it.

Would it be possible to compromise and keep the current design and add a view all button that displays a list like they have there?

**Comment by azizaparveen** [comment]
> Would it be possible to compromise and keep the current design and add a view all button that displays a list like they have there?
@chris-fox wanted to clarify if I understood correctly, 

1. We will still show the most latest selected pop-up information in the information panel, view all button will appear at the navigation bar, this is the current design
 
![image](https://github.com/Esri/solutions-components/assets/138827632/14c5d120-9133-4df6-8daa-349e24199221)

2. When the View all button is clicked, it will show a ordered list like IA  team shared (no radio buttons to indicate which is the current select feature)

![image](https://github.com/Esri/solutions-components/assets/138827632/94edd030-c481-43b6-84d3-11554cf6b399)

3. When we navigate to a single feature for editing from the list, it will show the same design for individual feature that is no back button and view all button at the navigation bar.

![image](https://github.com/Esri/solutions-components/assets/138827632/0d7f4b39-7f38-431c-968d-7412fc6fd459)

**Comment by chris-fox** [comment]
@azizaparveen, yes that is what I was thinking. thank you

**Comment by avezina** [comment]
While I like the design proposed by the IA team as it looks clean, in my opinion, it might be fine to just keep the current default design and only make these changes as a potential enhancement if time permits? 
Also, as Aziza pointed out, there is nothing indicating which feature was being displayed before going into this list mode. There's also no easy way to just navigate back to it; I would need to just find it again in the list.
![image](https://github.com/Esri/solutions-components/assets/50338557/cd33f810-cf94-47cc-8130-4d167a163437)

**Comment by chris-fox** [comment]
I could see requesting a back button like we have in the current implementation, that would be nice. I agree I also like the IA design for showing the list of records. Another potential benefit of the IA design is from the list of all records, this is where we could add the batch edit button when the batch editing capability is added.

**Comment by azizaparveen** [comment]
![image](https://github.com/Esri/solutions-components/assets/138827632/5578f5b2-12bf-4534-b125-2b32f98411e6)

**Comment by azizaparveen** [comment]
@chris-fox @avezina, IA team has some concerns on adding a button on the navigation panel, since we are going back and forth on this, I suggest that we discuss with them in next meeting (Nov 28th) to resolve difference on this issue

**Comment by azizaparveen** [comment]
We finally decided to keep the current design but make the button more noticeable and in future releases we will work with JS API team to update the feature widget with more customization option. Tracking it here https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9430

**Comment by azizaparveen** [comment]
IA team pushed this to R2

**Comment by azizaparveen** [comment]
@sumitzarkar could you please make the text bold 
![image](https://github.com/Esri/solutions-components/assets/138827632/d7c840cf-e38a-4699-8b03-f74a2591524e)

**Comment by azizaparveen** [comment]
Looking good in devext
