### ISSUE TITLE
If only attachment is added and no other editing is done in the attributes, attachment does not show up in the information panel outside of editing mode

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#425]
If only attachment is added and no other editing is done in the attributes, attachment does not show up in the information panel outside of editing mode

Test app: https://arcgis4localgov2.maps.arcgis.com/apps/instant/manager/index.html?appid=cce4a70f27084767bc78777a7ae79832

**Repro steps:**

1. Select a record from the table, click Edit button
2. Scroll to the attachment section and click Add
3. Select a file and click Add 
4. click back button from the top to get out of editing panel and scroll to the bottom and notice that the attachment you just add not showing up, but If you click edit button now you will be able to see the attachment

If you make any other edits and click update button it works as expected.
![manager attachment issue](https://github.com/Esri/solutions-components/assets/138827632/24ba8c8f-f5d1-4d4a-9056-f5f750659248)

**Comment by azizaparveen** [comment]
Verified in devext

**Comment by azizaparveen** [comment]
@jmhauck I am still seeing this in QA https://solutionsqa.mapsqa.arcgis.com/apps/instant/manager/index.html?appid=c05a0d6c7ee44911a298f58778ef9fe4

**Comment by jmhauck** [comment]
@azizaparveen can you see what my user name is in this org? All the qa user/password combos I have don't seem to get in.

**Comment by azizaparveen** [comment]
> @azizaparveen can you see what my user name is in this org? All the qa user/password combos I have don't seem to get in.

hauck_qa

**Comment by azizaparveen** [comment]
@jmhauck I see this issue only in qa, it is working in dev

**Comment by azizaparveen** [comment]
Verified in qa
