### ISSUE TITLE
Relevant functionality buttons are getting deactivated when clicking on a feature in the map twice

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#427]
Reported by Rachel during yesterday's bug out event
Relevant functionality buttons, zoom, delete, clear selection, show selected are getting deactivated when clicking on a feature in the map twice.
If I select a feature in the map, I see it selected in the table view. The Zoom, Delete, Clear Selection, and Show Selected button are all active at the top of the table. If I click the same feature in the map again, it still appears as selected in the map and table, however the Zoom, Delete, Clear Selection, and Show Selected buttons are no longer active.
![image](https://github.com/Esri/solutions-components/assets/138827632/fd7492bc-68bb-44bf-bcd8-126018f09f0d)
![image](https://github.com/Esri/solutions-components/assets/138827632/0aaa7a8b-ce15-4806-9d15-74a337a582d7)

![twiceselection on map issue](https://github.com/Esri/solutions-components/assets/138827632/f0cd999d-0053-4839-879c-b225c42e1fff)

**Comment by azizaparveen** [comment]
It is still reproducible in devext. here is a test app https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=580af16b1142418bb69c2991008039a7

**Comment by jmhauck** [comment]
@azizaparveen installed this last week...should be good to go.

**Comment by azizaparveen** [comment]
Looks good
