### ISSUE TITLE
Support editing tables layers only

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#428]
> Use case requested by @BrandiRank, where editable Table layers may be present in the map, but not editable Feature layers.

There are two scenarios for supporting editing table layers only:
1. With a map: table layers are added to a web map, and no other editable feature layers are added. (there may be some other reference layers which are also not editable)
    - If this workflow makes sense for Manager, in this case we may still need a way to show the Map in Manager and to configure the table layers as the layers that can be edited in Manager.
2. Without a map: connect Manager to table layers directly without the need for a map.
    - This may present some challenges with the Editor widget and Smart Forms based on the current implementation in Manager and also limitations from the Editor side. We would need to better understand how the ExB Edit widget is doing this (`attributes only` mode for Edit widget) and also what the Editor team is planning for the [Editor refactor in 4.29](https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/56805).

Somewhat related topics:
- https://github.com/Esri/solutions-components/issues/275
- https://github.com/Esri/solutions-components/issues/273

___

cc @azizaparveen

**Comment by chris-fox** [comment]
I was curious on this one and found it seems to be only a config limitation. The config doesn't allow you to add a map w/o any editable layers. However, if I add a map with editable layers in the app config, save and publish and then remove the layers from the map in the map viewer, I am left with just the tables and am able to edit the records in the table.

All that being said, I do like the idea of allowing maps with just tables, no layers, for use in Manager.

**Comment by azizaparveen** [comment]
Logged an issue in IA config repo to allow map with standalone table only https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/4214

**Comment by azizaparveen** [comment]
@avezina we are supporting standalone table in web map now, I created a new issue for supporting editing tables without map in Manager and add it to our backlog. https://github.com/Esri/solutions-components/issues/465
