### ISSUE TITLE
Manager is not showing newly added field in the table but it shows up in the information panel in editing mode

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#432]
Reported during Manager bug out event
I published a Manager Instant app using a basic web map with two layers.  After publishing, I added a field to one of the layers.  When editing a feature in that layer, I see the new field in the Edit feature pane, but it does not appear in the table.  

Test app: https://afmie.maps.arcgis.com/apps/instant/manager/index.html?appid=6db469f8c81844b6b16195c97a3f8fd9

![image](https://github.com/Esri/solutions-components/assets/138827632/df96b1f3-d5c0-4087-9f75-0918faa6eb60)

**Comment by azizaparveen** [comment]
@rachelmitcavish we are tracking this issue here

**Comment by azizaparveen** [comment]
Verified in devext

**Comment by azizaparveen** [comment]
@jmhauck , the new field shows up at the table and once I click on Edit button but in the information panel.
Test app: https://solutionsqa.mapsqa.arcgis.com/apps/instant/manager/index.html?appid=c05a0d6c7ee44911a298f58778ef9fe4
Not showing the new field here, but once I click on the Edit button it shows up

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by sarahmcdonald7** [comment]
@azizaparveen if you us the refresh button in the table tools, does the new field appear?
<img width="1041" alt="2024-02-20_14-06-52" src="https://github.com/Esri/solutions-components/assets/139994064/ec26c07d-5754-4c0b-864e-b589eb82c564">

**Comment by azizaparveen** [comment]
N

> @azizaparveen if you us the refresh button in the table tools, does the new field appear? <img alt="2024-02-20_14-06-52" width="1041" src="https://private-user-images.githubusercontent.com/139994064/306429901-ec26c07d-5754-4c0b-864e-b589eb82c564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NjcxMzMsIm5iZiI6MTcwODQ2NjgzMywicGF0aCI6Ii8xMzk5OTQwNjQvMzA2NDI5OTAxLWVjMjZjMDdkLTU3NTQtNGMwYi04NjRlLWI1ODllYjgyYzU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQyMjA3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDNiZDZhYTkzZmM0OTJmZTA5OTNmOWQ4MmRlNmNiNWYwMjI3OWM4MTYwYmFiMDc3YThlNTdiNjBkMDE3ZDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZAObemsy2H06Sko13LaAWDswUVG7CWgygql9zZTbtbE">

No, it still does not show up in the information panel, everywhere else yes.

**Comment by azizaparveen** [comment]
New field not showing up in the Info panel is a known limitation, This dialog is based on the pop-up definition, right now to see the new field we will need to update the pop-up definition, save the map and then reload the map.
