### ISSUE TITLE
Change multiselect behavior to respond to keyboard shortcuts instead of automatically adding to the previous selection

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#437]
With the current implementation, the default behavior of selection is, when a feature is selected, clicking on another record adds that to the previous selection unless user unselect the first record manually. This creates intended multiple selection where in most cases user just wants to select a single record at a time. To fix this problem , here are the details we discussed about adding  keyboard shortcuts (shift and ctrl) for multiple selection in the Table

- [ ] Select multiple items: Press and hold the Ctrl key, then click the items (they don’t need to be next to each other).
- [ ] Select multiple items that are adjacent: Click the first item, then press the Shift key and click the last item. All items in between should be included in the selection.

**Environment we need to consider**

1. Mac
2. Mobile

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by azizaparveen** [comment]
Verified in devext

**Comment by chris-fox** [comment]
Found a minor issue with this update:

1. Select a row with a single click
2. Unselect the same row with a single click
3. Select the row again with a single click
    -> The pop-up doesn't display and none of the toolbars buttons are enabled
4. Select another row with a single click
    -> Both rows are selected rather than just the most recent row that was clicked

**Comment by jmhauck** [comment]
@chris-fox I noticed that this morning and it will be fixed in the next pr. Will reference this issue again when it goes in.

**Comment by avezina** [comment]
[Comment ](https://github.com/Esri/solutions-components/issues/437#issuecomment-1861781272) is same as https://github.com/Esri/solutions-components/issues/477

**Comment by azizaparveen** [comment]
Looks good in devext

**Comment by azizaparveen** [comment]
Verified in qa
