### ISSUE TITLE
Should we hide the Map and Layer dropdowns if there is only one Map or Layer configured?

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#442]
Often in our solutions we name the map the same name as the app it is used in. In these cases this can create duplicate labels when you have the app header visible as shown below.

![image](https://github.com/Esri/solutions-components/assets/6796763/72f4eb5a-a773-44f9-9c3f-b22b72e25e9a)

I was wondering since the driopdown does nothing for the map or the layer when there is only one if we should just not show the dropdowns in these cases. Gives us back some space in the UI as well. Thoughts?

**Comment by chris-fox** [comment]
Makes sense to me to keep the layer name and just remove the dropdown.

**Comment by azizaparveen** [comment]
This is verified in devext 

![Image](https://github.com/Esri/solutions-components/assets/138827632/89c00487-829c-4749-abad-74aa436e4074)

**Comment by azizaparveen** [comment]
Verified in qa
