### ISSUE TITLE
Add hide field button to column heading more options menu

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#456]
### Describe requirements

Related to #350. When I first tested this out I expected to click the ... More Options button on a column heading to hide the field. This is consistent with the UX of the Table in the Map Viewer:

![image](https://github.com/Esri/solutions-components/assets/6796763/2a78b563-1239-42fb-aeb1-2e25c215ffbf)

**Comment by jmhauck** [comment]
@chris-fox checking with the JS API team. This core issue came up previously when we started to look at putting filter options in column menus. Currently no way to get the column that the menu originated from.

**Comment by azizaparveen** [comment]
Verified in devext 

![Image](https://github.com/Esri/solutions-components/assets/138827632/b31c8cf2-6439-4dea-838d-04ea515a7712)

**Comment by azizaparveen** [comment]
Verified in qa
