### ISSUE TITLE
Update Show Selected button to indicate if active or not

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#466]
### Describe requirements

Currently there is nothing in the UI that indicates that the table is only showing selected records. It seems like there are a couple options.

1. We could show the button as being in a pressed state. I see this in other places in Calcite as having a blue background around the button.
2. We could change the button to a Show All button when Show Selected is clicked. This is what we did in the previous version of Manager.

I kind of lean towards option 1 so the toolbar doesn't jump around when the length of the button changes.

@azizaparveen, @avezina thoughts?

**Comment by azizaparveen** [comment]
Agree with you @chris-fox , we can do this for Select all and Switch selected button as well.

**Comment by chris-fox** [comment]
I am not sure the same would apply to select all and switch selected. To me Show selected is a mode you enter or exit. Whereas select all and switch selected are an action you take on the table, but you don't exit the mode by pressing those buttons again.

**Comment by avezina** [comment]
Changing the button to "Show all" would make sense to me.
![image](https://github.com/Esri/solutions-components/assets/50338557/ed6be5ad-747e-4298-ac61-0766a87904e5)

**Comment by azizaparveen** [comment]
@chris-fox, right now when Manager enters to Show selected mode, the button shows a light gray background with a blue border to show cursor position, but when I click anywhere else in this state, both the border and background goes away, in this state we can still show the gray background like Map Viewer
![image](https://github.com/Esri/solutions-components/assets/138827632/1e2cd269-534d-463a-a587-5733e8720478)
![image](https://github.com/Esri/solutions-components/assets/138827632/fdf6c78b-c0f0-4347-b5f4-03873b523743)

**Comment by jmhauck** [comment]
Just added the little blue indicator to show filters have been applied. Should select all use the same or the gray idea?

**Comment by chris-fox** [comment]
@jmhauck, no I feel Select All is an action, I can unselect records interactively after clicking select all, also clicking select all again doesn't clear the selection which I believe is expected. Show selected is the only mode we have on the table and unclicking it exits the mode.

**Comment by azizaparveen** [comment]
Verified in devext
