### ISSUE TITLE
Add an indication  to the filter icon to show that filter is turned on

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#468]
### Describe requirements

We have the filter support in Manager, both in the configuration and runtime and I am testing the functionality. I am wondering if we can add a blue dot to the Filter icon to indicate that filter is on (when filters are turned on), right now it looks like this 
![image](https://github.com/Esri/solutions-components/assets/138827632/0c64e9cf-fd99-4036-a97e-24149252e34a) and I am proposing like Experience Builder but I like how the map viewer shows blue dot for indication
![image](https://github.com/Esri/solutions-components/assets/138827632/34935539-2b71-484c-aeb1-a7eca2fd5ad9)
![image](https://github.com/Esri/solutions-components/assets/138827632/a01d2347-256e-4ccd-a1e1-1e5f0ae8cbe5)

@chris-fox @avezina @jmhauck please le me know your thoughts on this

**Comment by avezina** [comment]
It looks like the Action component supports this. https://developers.arcgis.com/calcite-design-system/components/action/
![image](https://github.com/Esri/solutions-components/assets/50338557/ba2fd481-2e59-4b66-8a11-e064f3316430)

**Comment by chris-fox** [comment]
I like displaying the indicator, blue dot, when a filter is active.

**Comment by azizaparveen** [comment]
Looks good in qa
