### ISSUE TITLE
Updates to Filter UI

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#469]
### Describe requirements

I would like to request the following 2 enhancement to the filter UI in Manager:

1. Remove the Zoom to button (and row). The button doesn't add much to the app as its in a modal and hard to see what happens when you click it. Also the row adds a lot of white space to the UI, so hiding/removing would improve the spacing,
2. There is a grey box around the Reset and Close buttons that looks weird because there is also white background border around this section. The grey line above also doesn't stretch the full width of the modal window. 

![image](https://github.com/Esri/solutions-components/assets/6796763/5876e7d5-b2a3-476b-935d-4ff6a05bc2ae)

I made the following changes through the browser debugger to hide the zoom to row and to remove the padding around the filter component in the modal. I think it looks better, but it would be nice if we could add a little padding on the left and right side of the elements inside the filter. I am not sure if this would be a change to the Filter component to support it.

![image](https://github.com/Esri/solutions-components/assets/6796763/7ba6ad25-9f0f-4bb2-843d-22cd9b348284)

**Comment by azizaparveen** [comment]
first two issues are fixed, no zoom button is showing and the grey line stretches the full width of the modal window, only issue remaining is adding a bit of padding on the left and right, may be also vertically align the user input dropdowns with the Reset and Close buttons
![image](https://github.com/Esri/solutions-components/assets/138827632/12e5cac8-dcd2-41af-9463-aaf7f6e964e5)

**Comment by sumitzarkar** [comment]
@jmhauck 

It seems like this needs to be fixed in instant-apps-filter-list component, could you please confirm if any changes required from our side

**Comment by jmhauck** [comment]
@sumitzarkar yes...changes for this will need to happen in the instant app component

**Comment by azizaparveen** [comment]
@sumitzarkar is this fixed in the latest code drop? 
![Image](https://github.com/Esri/solutions-components/assets/138827632/1c408233-68c6-45cc-a128-b1896f5c27fd)

**Comment by sumitzarkar** [comment]
@azizaparveen 

We don't have any changes for this in manager component. This needs to be fixed in Instant app component

FYI @jmhauck

**Comment by azizaparveen** [comment]
Logged an issue in IA template repo https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10082

**Comment by azizaparveen** [comment]
Closing this one and tracking the padding issue in https://github.com/Esri/solutions-components/issues/1041
