### ISSUE TITLE
Have to click twice in list to see record in "Information"

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#477]
### Describe the bug

See https://devtopia.esri.com/WebGIS/solutions-web-development/issues/132

### Expected Behavior

I expect to click on the record once.

### Reproduction Steps & Sample

https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=8f514804a9cc475a8a9c0675cab2489e

Click on a record in the list by clicking in the check box.
Uncheck the record.
Check the record again. Now the information is activated in the "Information" screen on the left.

**Comment by jmhauck** [comment]
@avezina not seeing this with the latest PR

**Comment by avezina** [comment]
I can no longer reproduce this issue.

**Comment by azizaparveen** [comment]
No reproducible in qa
