### ISSUE TITLE
Clicking on the filter button in the configuration mode and runtime still shows deleted filter

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#488]
### Describe the bug

In my app, I configured one filter, then delete that filter and added a new one. then if I click on the preview of the app (config mode) it still shows the old filter. Also, I published -> confirm and launch the app and at runtime, it still shows the old filter after clearing out caches.
![image](https://github.com/Esri/solutions-components/assets/138827632/a7328498-9457-48cc-8ee9-b1ba5f34496c)

### Expected Behavior

Manager should show the newly added filter both in preview and runtime mode

### Reproduction Steps & Sample

Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=580af16b1142418bb69c2991008039a7
1) Launch the test app
2) Click on the Filter button and notice that the filter name is "Adam elementary before April 22nd" this is the deleted filter, it should show "Adam elementary" instead

### Other Relevant Info
**Note**: I cleared caches, use private window in a different browser, still seeing the old filter

**Comment by jmhauck** [comment]
@azizaparveen I made several updates for this. Ready for review on devext

**Comment by azizaparveen** [comment]
This looks good in devext
