### ISSUE TITLE
Layer title is not updated when interacting with feature on map 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#502]
### Describe the bug

When a map has multiple layers, and if the feature details is opened, but user interacts with another feature on the map from a different layer, the feature detail is updated but not the layer title.

### Expected Behavior

Update the layer title when the feature is not from the same layer

### Reproduction Steps & Sample

1. Open the map > click a layer 
2.  Click on a feature to view its details
3. Interact on the map with a feature from a different layer
4. Notice the layer title is not updated. 

https://lgtest.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=7dd9949b10e847198052f1387fb0daef

**Comment by sumitzarkar** [comment]
@skrishn 

We have fixed this and will deliver it in the next code drop

**Comment by skrishn** [comment]
Great! Thanks, Sumit!
