### ISSUE TITLE
Feature rendering issue

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#503]
### Describe the bug

I've a map with one layer and one feature, and when viewing feature details, it appears the feature renders twice. Please see the snip. 

I'm wondering if the issue is with reporter app or core?

### Expected Behavior

Render feature properly

### Reproduction Steps & Sample

![image](https://github.com/Esri/solutions-components/assets/3836616/c30ff41e-31dd-43dc-a3b0-a42b29a8f731)

Click layer > feature > feature detail
See the feature tries to render twice. 

(Note: behavior maybe inconsistent sometimes)

**Comment by sumitzarkar** [comment]
@skrishn 

Could you please share the webmap to reproduce this issue

**Comment by skrishn** [comment]
@sumitzarkar https://lgtest.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=b8839d4c68f248399a5df09c8cdc2ae3

I noticed this with some of my other maps too.

**Comment by sumitzarkar** [comment]
@skrishn 

In the screenshot you shared above we don't see any base map, seems like if we don't have any base map then it is reporduced?

We are not able to reporoduce it now:
![image](https://github.com/Esri/solutions-components/assets/9443956/89193c3a-e4e1-40ad-90fa-7c601ca42e0c)

**Comment by skrishn** [comment]
@sumitzarkar It happens 8/10 times for me. Let me try with other maps and send it along. Thanks for looking into it.

**Comment by skrishn** [comment]
maybe related https://github.com/Esri/solutions-components/issues/360#issuecomment-1922243102

**Comment by sumitzarkar** [comment]
@jmhauck
 
We are using an info-card component to show the details, and it is handling the highlight and zooming to the feature.

Should this be handled in any of the utils files so that it is reflected in both the manager and reporter?

Please let us know your thoughts on this

**Comment by skrishn** [comment]
@jmhauck Please share your thoughts. Thanks.

**Comment by jmhauck** [comment]
@sumitzarkar yes...please do. Currently manager leverages the FeatureTables zoom functionality and we should swap to use the util function so it's consistent across the components.

**Comment by skrishn** [comment]
@sumitzarkar whats the status of this?

**Comment by sumitzarkar** [comment]
@skrishn 

We have updated the zoom functionality in #360 , this should have fixed.

please check and let us know if you see any issues
