### ISSUE TITLE
Font of table widget is different from the rest of the app

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#505]
### Describe the bug

The font of the table widget (column headings and rows) is now different than the rest of the app and the beta version. It is not Avenir like the rest of the apps in Online. The table in the map viewer also is showing this different font so it seems like an issue with the widget, but I am unclear if this was an intentional change or not. It seems weird to change this to me. Could we investigate if this was intentional?

### Expected Behavior

I would expect the font to match the rest of the app

### Reproduction Steps & Sample

Use the browser debugger to inspect the table elements to see the different font.

**Comment by azizaparveen** [comment]
This issue in not reproducible in devext anymore.
![Image](https://github.com/Esri/solutions-components/assets/138827632/c7c76478-13ff-4f9a-8452-034332cd1308)
