### ISSUE TITLE
Labels are cut off sometimes

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#507]
### Describe the bug

I've a webmap with labels enabled and at times it's cut off

https://lgtest.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=38b7b73ee28d45c4a1976335e0219c94

 

### Expected Behavior

Label should be rendered fully. 

### Reproduction Steps & Sample

Click on the Layer with attachments > Click on feature 88

![image](https://github.com/Esri/solutions-components/assets/3836616/c459158a-09af-4d36-8186-e1ab1012902d)

**Comment by sumitzarkar** [comment]
@skrishn 

This is JS API's map behavior we don't have any control over it
