### ISSUE TITLE
When you add a related record the edit form does not update

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#508]
### Describe the bug

If you edit a record and add a related record, when you are taken back to the edit form for the original selected feature the related record added does not display. I can reproduce the same issue in the map viewer so this may be a bug in the edit widget. This is not reproducible in production, so it appears to be a regression for this release.

### Expected Behavior

The newly added related record displays in the edit form.

### Reproduction Steps & Sample

1. Go to https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=bd57063681644c4dbda2ec44cbc16823
2. Select one of the rows and edit it
3. Add a related comment, fill out the form and create it
4. This takes you back to edit the original selected feature. The form does not show the new added related record

**Comment by azizaparveen** [comment]
Submit a bug in the JS API repo https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/59171

**Comment by azizaparveen** [comment]
Fix is installed, should be in devext after the next build https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/59171#issuecomment-4559060

**Comment by azizaparveen** [comment]
Update 
![image](https://github.com/Esri/solutions-components/assets/138827632/c207344d-f58c-4100-ba31-874b772ba92f)

**Comment by azizaparveen** [comment]
This issue is fixed in devext.
