### ISSUE TITLE
Export CSV with field aliases instead of field names in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#512]
### Describe requirements

We would like Manager to export the CSV with field aliases rather than the field names in column headings. Experience Builder Table widget does that
![image](https://github.com/Esri/solutions-components/assets/138827632/891ff34b-c88d-4e82-b3d9-c559c4d4e635)

**Comment by jmhauck** [comment]
Ready to test after next build

**Comment by azizaparveen** [comment]
verified in devext
