### ISSUE TITLE
If you select a feature from the list and go back the feature remains selected required an extra click to view it again

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#521]
### Describe the bug

If you select a feature from the list and go back the feature remains selected. If you click the row again it unselects the record and then you need to click it again to select and view the record

### Expected Behavior

I would expect when you go back that the feature is either unselected or for a click on the feature again to open its details even though it was previously selected

### Reproduction Steps & Sample

1. In Reporter select a layer and then a feature from the list. This will open the details for the feature
2. Click the back button to return to the list and the feature remains selected
3. Click the feature again and it will unselect the feature
4. Click the feature again and it will select and show the details.

I would expect to not have to make the multiple clicks to view the feature.

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impact on Feature List | On select of feature from the feature list, should open the feature details.
||On the back click, the highlighted feature from the feature list should be unselected, and clicking on the feature again should show the feature details.|

**Comment by skrishn** [comment]
@sumitzarkar I'm seeing inconsistent behavior, when I select a feature the first time it's not highlighted but going back to the feature list and selecting the same feature highlights it. Often seen with point and line. 

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=8383f3808b314a9ba531beae8ae763e2

**Comment by sumitzarkar** [comment]
@skrishn, @jmhauck 

>I'm seeing inconsistent behavior, when I select a feature the first time it's not highlighted but going back to the feature list and selecting the same feature highlights it. Often seen with point and line.

This is due to the layerview is not having the feature to highlight, need more analysis and also if requried we can discuss with JS API team regarding this.

**Comment by skrishn** [comment]
@jmhauck please share your input on how to approach this. Thanks!

**Comment by skrishn** [comment]
Cant repro after r2. closing the issue
