### ISSUE TITLE
Hide create new features window

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#522]
It appears for a split second when adding a new feature, could we hide it please for a better user experience?

**Comment by sumitzarkar** [comment]
@jmhauck 

- As discussed on the call earlier, we are hiding the header and footer elements of the Editor widget using querySelector as we are not able to override it using CSS.
- As this needs to be done in timeout sometimes the header and footer elements are visible and then it is hidden.
- If we reduce the timeout it not hiding as those elements are not rendered yet.

Do you see any alternate approach for this or could we check with the API team if any alternative to this?

**Comment by skrishn** [comment]
I notice sometimes, we can see the window for a split second just like before the fix.  https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=da6b995935114761a3c2fafc928435bf

In this sample. you'd see the feature template size adjusting when the create feature window gets hidden https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=235b73e06533467892268a5fe8d3a20a

@jmhauck is looking for an other approach for this issue.

**Comment by skrishn** [comment]
@jmhauck Did you find any alternate approach? Thanks

**Comment by skrishn** [comment]
@sumitzarkar We're seeing this again when the comments button is clicked. Is there a way to not show create features window?

**Comment by sumitzarkar** [comment]
@skrishn 

This is known limitation, we need inputs from JS API team if they have any workarounds for this.

**Comment by jmhauck** [comment]
Hey @sumitzarkar put in an approach that we could use. Just made it so we could hide the editor until all of the startCreate code and its timeouts are done. Please take a look and let me know if you see any issues.

**Comment by sumitzarkar** [comment]
Thanks @jmhauck - will check and keep you updated.

**Comment by sumitzarkar** [comment]
@jmhauck - We are observing one issue when we have multiple templates in the layer, we have fixed it and will test and deliver it tomorrow.

Also, we will add similar code for create-related-feature component

**Comment by chris-fox** [comment]
@sumitzarkar, @jmhauck, I tested this out in DevEXT today and it looks good for creating a request. Could we do similar for creating a comment?
