### ISSUE TITLE
Report button still visible upon turning off the reporting layers in config

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#523]
### Describe the bug

I checked the features to report, and then unchecked it, but the reporting button was still visible and I'm to submit reports.

### Expected Behavior

If layers are turned off, hide the report button. 

### Reproduction Steps & Sample

![image](https://github.com/Esri/solutions-components/assets/3836616/20fc1689-e45c-4af4-9d68-da0b7496a81e)

**Comment by debjitp452** [comment]
@skrishn 

- As per our previous discussion we had decided that by default we would show all reporting layers.
- And if specific layers are configured for reporting then we will honour those layers to be shown in reporting list. 
- The same message is shown in the tooltip as well. 
- Currently in the default behaviour of the application all layers remain unselected. So even if we first check all the layers and then again uncheck all, application is returning back to the default behaviour of select reporting layers configuration and all layers are shown for reporting. 
- So this is as per design and not a bug. 
- To resolve this issue, all layers should be selected by default for reporting.

![image (9)](https://github.com/Esri/solutions-components/assets/101550505/f4169dff-c16a-4fde-9d99-2653490e19a2)

Please let us know your thoughts on this. Thank you.

**Comment by skrishn** [comment]
Let's discuss how to handle this for the next release.

**Comment by sumitzarkar** [comment]
@skrishn As discussed updated milestone for this

**Comment by sumitzarkar** [comment]
@skrishn 

Please let us know how would you like to handle this, if we would like to do cahnges as suggested in https://github.com/Esri/solutions-components/issues/523#issuecomment-1933414272, this needs to be implemented in instant app.

**Comment by sumitzarkar** [comment]
@skrishn 

For this we don't need any changes in the Component, only instant app needs to be updated

**Comment by skrishn** [comment]
@sumitzarkar Thanks, I'm closing it then.
