### ISSUE TITLE
Fields visibility and order  are not being reflected after changing their visibility and order in the preview mode (configure template mode)

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#534]
### Describe the bug

I turned off a few fields in the configuration and change their orders, but the preview window still shows those fields and previous orders until the page is refreshed, 
It saves (saving to draft) after changing visibility and order but the changes are not being reflected in the preview window.
it works as expected at runtime.
![image](https://github.com/Esri/solutions-components/assets/138827632/4ad8970c-5db6-45fa-a946-eed452afcda2)

### Expected Behavior

Changing fields visibility and order should be reflected in preview

### Reproduction Steps & Sample

1) Open a Manager app in Configuration mode
2) From Interactivity tab, click on the Table option and Click on the Field button
3) Change visibility and order of a few fields and notice that the changes are not being reflected in the preview.

**Comment by azizaparveen** [comment]
still seeing this issue

**Comment by azizaparveen** [comment]
@jmhauck thanks for the update, I also see that the columns are refreshing but can't say for sure because of the column names going blank, lol, I will verify both the issues once the js api fix will make it to devext

**Comment by jmhauck** [comment]
@azizaparveen you will see that the changes to the fields and their order under More > Show/hide columns.

And if you toggle on/off one of the fields it will cause the table to update after that grid.js error has occurred so columns will be drawn.

**Comment by azizaparveen** [comment]
Verified in qa

**Comment by azizaparveen** [comment]
I am seeing this issue again in both qa and production

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by azizaparveen** [comment]
Verified in devext

**Comment by azizaparveen** [comment]
Looks good in qa
