### ISSUE TITLE
Move the 'Add' button to top when adding media

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#540]
### Describe requirements

When adding multiple media when submitting reports, the images and videos appear on top and users have to scroll down to click the add button to continue adding it. For a better user experience, let's move the add button to the top and the images below it. 

current UI
![image](https://github.com/Esri/solutions-components/assets/3836616/a9d9df18-627a-4c29-ada8-bb5c3de41cbd)

**Comment by sumitzarkar** [comment]
@skrishn 

This is the default behavior of the Editor widget, we don't see any option to change this.

**Comment by skrishn** [comment]
Thanks, @sumitzarkar
