### ISSUE TITLE
Application font is not honored

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#541]
### Describe the bug

The application font set in the configuration is not being honored in the app. 

### Expected Behavior

App should honor the fonts set in config.

### Reproduction Steps & Sample

In config, go to Theme & Layout tab

1. Choose a 'Header font'. It gets updated.
2. Choose an 'Application font', and notice it doesn't get updated

![image](https://github.com/Esri/solutions-components/assets/3836616/498d45e6-ea79-4782-a440-4c0039f1795c)

**Comment by sumitzarkar** [comment]
@skrishn 

Seems like, this should be handeled in Instant app.

@jmhauck - Please let us know if we need to do any changes for this in reporter component

**Comment by jmhauck** [comment]
I'll add some logic for this

**Comment by jmhauck** [comment]
@skrishn Should be available on dev today
