### ISSUE TITLE
Filter button is not showing up when Manager app loads for the first time

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#542]
### Describe the bug

I have two filters set in the layer, but the filter button is not showing up in the preview or at the runtime when the app loads for the first time, it shows up when I resize the browser window at runtime or placed in the More button both in the preview and runtime, when a record is selected, the button shows up at the top menu as expected
![image](https://github.com/Esri/solutions-components/assets/138827632/6e39897c-0ada-4910-acf7-d3598c0725b5)
![image](https://github.com/Esri/solutions-components/assets/138827632/da09b8a4-5397-4880-badf-a8e2b69b95e0)
![image](https://github.com/Esri/solutions-components/assets/138827632/44801115-8be5-4db7-a22f-b8302712ceb2)

### Expected Behavior

if there is any filter configured, filter button should show in preview and runtime, I am noticing this issue for the first time. it should be placed in the top menu.

### Reproduction Steps & Sample

Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/configure-template/index.html?appid=580af16b1142418bb69c2991008039a7

**Comment by azizaparveen** [comment]
Couldn't repro it in any other app, closing

**Comment by azizaparveen** [comment]
We still seeing this issue @jmhauck 
cc@sarahmcdonald7

**Comment by sarahmcdonald7** [comment]
I think this might be okay, will check again once devext is pushed to qa.

**Comment by azizaparveen** [comment]
I am still seeing this issue in both devext and qa, in new apps, as if the app is not registering the filter added, @sarahmcdonald7 could you please check on your side.

**Comment by sarahmcdonald7** [comment]
@azizaparveen On apps that I previously set up filters on the filter is showing. But in new apps if I try to set up filters, they aren't appearing.

**Comment by azizaparveen** [comment]
Thanks @sarahmcdonald7 , I am closing this for now, since it is working for you and John (locally), I will keep an eye on this Wednesday night in production and if needed will reopen this.

**Comment by azizaparveen** [comment]
Reopening this issue, since John found a fix for this and the fix will be in Patch A, cc @sarahmcdonald7

**Comment by azizaparveen** [comment]
This looks good in qa
