### ISSUE TITLE
Revisit designs for like, dislike and comment

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#545]
When the popup is long, users will have to scroll down to like, dislike, and comment. Sometimes, this could make new users unaware of the functionality available. The suggestion is to move to a three-dot menu on top. 

We'll discuss with IA team before proceeding with the implementation

**Comment by skrishn** [comment]
@sumitzarkar could you share the designs you had with 3-dot menu?

**Comment by sumitzarkar** [comment]
@skrishn Here is the sample screenshot:
![image](https://github.com/Esri/solutions-components/assets/9443956/2644824f-9526-43e4-a9b0-f534db83b02f)

**Comment by skrishn** [comment]
@sumitzarkar we'd like to follow the existing designs.

**Comment by sumitzarkar** [comment]
@skrishn 

Just to confirm, we will be following the designs in figma

**Comment by skrishn** [comment]
@skrishn Yes

**Comment by sumitzarkar** [comment]
@skrishn 

We can close this ticket and track the like dislike implementation in https://github.com/Esri/solutions-components/issues/591
