### ISSUE TITLE
Review designs for the location of search widget

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#546]
With editor widget implementation to create features, we will need to revisit designs for search  widget

**Comment by skrishn** [comment]
@sumitzarkar designs will be updated, we would like to show an intermediate screen when the layer has a feature template, and upon choosing the template a full map screen shows up as in the designs. Let me know if you've any questions.

**Comment by sumitzarkar** [comment]
@skrishn 

Please share the designs for further analysis

**Comment by sumitzarkar** [comment]
@skrishn 

Any updates on this

**Comment by skrishn** [comment]
@sumitzarkar I've shared the designs, please review this https://github.com/Esri/solutions-components/issues/590. Please take a look and let me know if you've any questions.

**Comment by sumitzarkar** [comment]
@skrishn 

As discussed on the last call we will add the search widget only on the screen where we see a msg from editro widget to complete the drawing

| ![image](https://github.com/Esri/solutions-components/assets/9443956/3be14d16-c20a-4963-bb8b-65eecc11c70f) | ![image](https://github.com/Esri/solutions-components/assets/9443956/27b642c7-1371-4183-b338-c80021c93b02) |

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
|Impact at runtime|The search widget should only be displayed on the feature creation panel|
||If Locator is configured then it should show in the search widget else by default it should take the World Geocoding Locator |
||On search of location <br><br>  1. If the geometry type is the point <ul><li>The map should be zoomed and the point should be plotted on the searched location </li><li>User should be directed to the feature form panel</li></ul>2. If the geometry type is a line or polygon, the map should be zoomed and panned to the search location |
