### ISSUE TITLE
Review mobile designs for reporter

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#547]

**Comment by skrishn** [comment]
Designs are updated and tracked in the issue. Closing this issue.
https://github.com/Esri/solutions-components/issues/590

**Comment by skrishn** [comment]
We got some feedback, and I'm reopening this issue

"I think we need some work on our mobile design. I find it hard to view and submit reports when the map takes up 50% of the screen. I think we need to get closer to the mobile design put together below:
 
https://www.figma.com/design/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?node-id=2123-559

 For example, when submitting a report I like the design where the form takes up the full screen. I like when you get to the page to set the location we show and embedded web map in that screen to assist with it. In addition, when viewing a report and commenting, I like the panel taking the full screen."

**Comment by skrishn** [comment]
@sumitzarkar, will update you after getting designs.

**Comment by sumitzarkar** [comment]
@skrishn @chris-fox 

As discussed on the call, for this relase we will only focus on the Create Report workflow:
https://www.figma.com/design/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3

![image](https://github.com/user-attachments/assets/56f48f77-f783-412e-a97e-7af9444a4c3d)

**Comment by sumitzarkar** [comment]
@skrishn 

## Solution
- Update the UI structure to incorporate mobile designs
- In the case of mobile create a new map view in the side panel after the editor widget
- Bind the editor widget and Search widget to work with the new Mapview
- Update the code to emit the panel to be shown full/half based on workflow. E.g. once enterd in the Create workflow, always show full panel in mobile
___
## Dev Checklist

Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | Yes  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on Runtime (In mobile mode) |  On clicking the 'Report an Incident' button:-
|| The layer selection page and Template picker page should always shown in full height
|| After selecting the layer/template Map should shown in the panel for adding geometry
|| Searching using the in-panel search should navigate user to the selected location in the panel map
||_While creating the feature if switched to desktop mode then the user should redirected to the previous page (to maintain the active map)_
|| On submitting the report the user should redirected to the home page with the default split panel

**Comment by skrishn** [comment]
@sumitzarkar I notice that "Click on the map to add a point" message takes up half of the space and the map takes the rest. The map needs to take up most of the space.

![image](https://github.com/user-attachments/assets/74e3d3ae-e1c0-4097-b4c8-20e8f7ded5a4)

**Comment by chris-fox** [comment]
@sumitzarkar, @skrishn, I am guessing the area would be filled with the feature templates if the layer had more than 1 available feature template. I was thinking about this and was wondering if we might want to provide the option to select the feature template prior to this screen? This way the map could have the full space like Suba describes. 

So in the design below we would have an additional screen between screenshot #3 and #4. If the layer only has one feature template it skips this page.

![image](https://github.com/user-attachments/assets/f0230a9c-6fb4-4f94-928a-2d81cd1165ef)

Related, do we need some kind of back experience? As you progress through the different pages an ability to go back an change the selection. I know there is a back button at the top, but believe this exists the create report mode completely.

**Comment by skrishn** [comment]
@chris-fox we get the feature template screen in full page 

![image](https://github.com/user-attachments/assets/5300fdf7-dd2f-44b1-8a09-f77767241e3f)

![mobile repoter](https://github.com/user-attachments/assets/96b21e07-c5a1-4774-a386-542a56e59458)

**Comment by chris-fox** [comment]
ok looks good, I would agree with you that then on the map page it should take up more of the screen. I don't think we need the 'Click on the map to add a point' text. We should update the info messages at the top of each section to be more applicable to each page.

**Comment by skrishn** [comment]
Depending on the geometry we get "Click on the map to start drawing." or "Click on the map to add a point' text. Since there's search bar too on the page,  "Please provide the details." tooltip can be replaced with "Enter an address or click on the map to create a feature". 


![image](https://github.com/user-attachments/assets/6723ba64-6125-4af4-b17a-215814f2b003)

"

**Comment by sumitzarkar** [comment]
@skrishn 
- **Click on the map to start drawing** This message is shown from Editor widget
- We are rendering the map below the editor widget.
If we would like to show the full map, we may have to overlap the editor widget with the map and show the editor widget's message in the calcite notice, as mentioned above.
- In the case of point feature creation 
    ![image](https://github.com/user-attachments/assets/3e498b0a-e6cc-43ca-8eee-a2e958de7be0)
- Please let us know what should be the message in case of line and polygon

Also, please let us know if any changes required in this

**Comment by skrishn** [comment]
@sumitzarkar Implement hiding the text with full map view. I've created another issue for replacing the texts https://github.com/Esri/solutions-components/issues/854

**Comment by sumitzarkar** [comment]
@skrishn 

Please provide the mesages to be shown in case of polygon and polyline
https://github.com/Esri/solutions-components/issues/547#issuecomment-2338421479

**Comment by skrishn** [comment]
@sumitzarkar It's the same, I used the 'feature' for all geometry types.

**Comment by chris-fox** [comment]
Could we just say "Enter an address or click on the map"? Feature is a specific term to GIS that I don't think will be intuitive to non-gis users.

**Comment by skrishn** [comment]
I thought so too, but I felt click on the map is a bit vague. 

@sumitzarkar Let's use "Enter an address or click on the map" for all geometry types. Also, Aziza mentioned she was seeing this text in manager too, you're probably handling this separately for manager. Just wanted to say that this text is only for reporter app.

**Comment by chris-fox** [comment]
@skrishn, @sumitzarkar, will the "Click on the map to add a point." still show in the Desktop mode? It would seem to be a little redundant with the tip at the top. My understanding is this is coming from the editor widget:

![image](https://github.com/user-attachments/assets/568a211c-eee5-4ffc-9fb5-0174435a76db)

I also noticed in the Editor widget the text is "Click on the map to start drawing." for line and polygon layers.

What if we did something more like the original design. Where the tip at the top says something like "Please specify the location.". Then below the search bar we have the Edit widget text "Click on the map to add a point." or "Click on the map to start drawing."

![image](https://github.com/user-attachments/assets/1aaa94cf-2914-4a42-96b9-213f207b0c09)

**Comment by sumitzarkar** [comment]
@chris-fox @skrishn 

Here are the screenshots as per the above changes, please let us know if any changes are required in this:


Template Picker​​ | Drawing​ | Form
-- | -- | -- |
![1](https://github.com/user-attachments/assets/cccbce2a-9061-42f1-8033-6fa3a650273f)​ |  ![2](https://github.com/user-attachments/assets/54dc17e1-aa05-4ed5-b0c5-2249f7e54107) |  ![3](https://github.com/user-attachments/assets/03777fcf-279e-4468-9997-524b2144fb17) |

**Comment by chris-fox** [comment]
@sumitzarkar, that looks great. Thanks.

**Comment by skrishn** [comment]
@sumitzarkar I still see the same behavior as mentioned here https://github.com/Esri/solutions-components/issues/547#issuecomment-2333049630

**Comment by sumitzarkar** [comment]
@skrishn 

>  I still see the same behavior as mentioned here https://github.com/Esri/solutions-components/issues/547#issuecomment-2333049630

- We can reproduce this in the Instant app only
- The Map nodes position which we are overriding is not getting applied
- We will update the CSS and deliver it in the next code drop
