### ISSUE TITLE
Buttons in the share widget is not working

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#550]
### Describe the bug

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9567

When you create a report and select the share option, the links don't work or do anything.

@jmhauck are you going to fix this or CT?

### Expected Behavior

All the buttons should work

### Reproduction Steps & Sample

Open reporter app (https://holistic.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=b87b7fce130148fd9f20f3550610356c)
Create report or open existing report
Select the share option > select any of the options and notice none respond
Test App
https://holistic.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=b87b7fce130148fd9f20f3550610356c

**Comment by sumitzarkar** [comment]
@skrishn @jmhauck 

We tested with the copy link URL and it is working, the only issue we are observing is that when the copied link is accessed we are not navigated to the selected feature.

We will look into this and will update you with our findings

**Comment by jmhauck** [comment]
@sumitzarkar The layerid from the url was going to the oid prop on the component. My bad. I had them reversed. After fixing that the app loads the and selects the correct feature but doesn't center and zoom to it. The url also has `center` and `level`. Once you add these we can pass them in from the IA app as well.

**Comment by skrishn** [comment]
@sumitzarkar I noticed an issue with Facebook and LinkedIn sharing, but Twitter works. Is this an issue with the widget itself?

![image](https://github.com/Esri/solutions-components/assets/3836616/6159154d-8347-42bd-a1a8-be0411d85465)

![image](https://github.com/Esri/solutions-components/assets/3836616/ecc7ad20-a3de-425d-aefc-5629fc1114a5)

![image](https://github.com/Esri/solutions-components/assets/3836616/6e52a5f6-f433-45a5-95ad-538cd1443dda)
