### ISSUE TITLE
Allow user to create feature without having to click Next after choosing a layer. 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#551]
Holistic feedback:

"I wish when you selected a category, it brought you to the next page without having to choose "Next" like it does when you add a point on the map."

**Comment by chris-fox** [comment]
I agree, i thought the same.

**Comment by avezina** [comment]
I was just thinking the same too!

**Comment by sumitzarkar** [comment]
@skrishn 

OK, we will implement this.
Just to confirm, when user clicks on 'Submit Report' button, list of layers will be shown and when user selects the layer user will be navigated to feature creation directly.

**Comment by skrishn** [comment]
@sumitzarkar That's correct.

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
|Impact at runtime|On click of the 'Report an incident' button, <ul><li>The list of layers should be displayed</li><li>On click of any layer it should be navigated directly to the feature creation/feature template panel</li></ul>|
||On the layers panel, the Next and Cancel button should be hidden|
