### ISSUE TITLE
Share and More buttons overlap

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#554]
### Describe the bug

Share and More buttons overlap on all window sizes
![image](https://github.com/Esri/solutions-components/assets/50338557/d9ab7df2-ddd5-450c-8974-f10748261fdd)
![image](https://github.com/Esri/solutions-components/assets/50338557/11497f33-e5da-48e2-86c0-ec3c12cfbe71)

### Expected Behavior

Buttons should not overlap

### Reproduction Steps & Sample

Create a new app and enable the sharing option 
![image](https://github.com/Esri/solutions-components/assets/50338557/b24b8f53-b382-4bd6-afd2-baeed064b414)

cc @azizaparveen

**Comment by azizaparveen** [comment]
@avezina I could not repro this, could you please share your app?
![image](https://github.com/Esri/solutions-components/assets/138827632/aed7ada3-0cd2-4561-b362-c3c10b82475a)

**Comment by avezina** [comment]
@azizaparveen I believe you'll see it here if you click the More button that these two actually obverlap 
![image](https://github.com/Esri/solutions-components/assets/50338557/3a743d66-7fc8-4978-8ee0-6ca0b8ac2f14)

**Comment by azizaparveen** [comment]
@avezina thanks, so the background of the More button overlaps with Share button in iPad pro dimensions, we will see if we can squeeze this in if other issues are are resolved.
![image](https://github.com/Esri/solutions-components/assets/138827632/4dc04a0c-50c4-41e3-b36e-4d307269abd8)

**Comment by sarahmcdonald7** [comment]
@azizaparveen @avezina I tested this morning on my ipad and wasn't running into this. Do you still see this on devext?
<img width="986" alt="2024-02-23_10-58-24" src="https://github.com/Esri/solutions-components/assets/139994064/c2f8c8d3-499a-4158-a399-8d11b93fb067">
<img width="984" alt="2024-02-23_10-58-01" src="https://github.com/Esri/solutions-components/assets/139994064/c4aee429-4143-45cb-8aaa-a86c4d160df7">

**Comment by azizaparveen** [comment]
It looks good me in iPad 
![image](https://github.com/Esri/solutions-components/assets/138827632/5d3f6b72-3f79-404e-8a03-118cdc8fa470)

**Comment by avezina** [comment]
I did not test this on iPad, just Edge browser, but I can see the issue in the builder
![image](https://github.com/Esri/solutions-components/assets/50338557/bec2a707-f17f-4f66-bc92-89b07b49aa66)

Once app is launched, it seems fine.

**Comment by jmhauck** [comment]
Just to chime in...I couldn't make this happen locally when testing. Currently a function runs after the table component renders that is supposed to make sure this doesn't happen but just in case I did add an explicit check when share is enabled/disabled that will hopefully get it for whatever leads to what @avezina is seeing.

**Comment by avezina** [comment]
If it's only occurring in the builder I think we probably don't need to be too concerned with it
