### ISSUE TITLE
Data is not loaded in the table for other layers in the map

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#556]
### Describe the bug

Data is not loaded in the table for other layers in the map. The map contains a large feature service.

![image](https://github.com/Esri/solutions-components/assets/50338557/669be22e-c10f-455f-8ec5-6338ab354458)

### Expected Behavior

Rows should be loaded in the table if there are features in the layer.

### Reproduction Steps & Sample

Use this web map: https://devext.arcgis.com/home/item.html?id=fa9cf987a08e42018b3756b73f392fae (vpn connection required)

> _Username: admin_
> _Password: esri.agp_

_Please do not edit the data._

1. Add the web map to a new Manager app
2. Use the layer switcher to change which layer is loaded in the table
3. Observe: only the first layer (Electric Device) can be loaded in the table, the other layers remain blank although there are features in the layer.

### Other Relevant Info

cc @azizaparveen 
I am not sure this is a critical workflow, it will depend on the reason why loading the rows fails.

**Comment by avezina** [comment]
Note: these layers have many fields, and I've observed the same issue for other layers with lots of fields.

**Comment by jmhauck** [comment]
Not sure this is related to the number of features. Especially since we have basically disabled the new logic now. I have seen this but have not been able to make a trimmed repro case yet. @avezina look at your scroll bar...for some reason the focus shifts to the very bottom and in the cases I've seen all the data is there but you have to scroll up to see it

**Comment by jmhauck** [comment]
This seems like it has something to do with sorting on the oid field. If I remove the sort I can't seem to repro. But in a trimmed case it only happens very intermittently. If I put a delay on the sort it seems to work fine but we see the rows not sorted for a brief moment.

**Comment by azizaparveen** [comment]
@jmhauck to me, a little bit of delay is better than data not loading at all.
So if we go with this solution, are we going to see delay in sorting every time we switch layers?

**Comment by jmhauck** [comment]
@azizaparveen I hear you.

I have submitted this to dev. It's intermittent at best.

What I'm seeing sometimes it sorts most times it doesn't and sometimes it displays the table and its forced the scroll bar all the way to the bottom and you can't see any of the data unless you scroll up.

https://codepen.io/jmhauck/pen/ExMrOwK

Have not seen this occur if I switch it back to 4.28

**Comment by avezina** [comment]
@jmhauck I guess we should log an issue for this in the JS repo as a regression for the table in 4.29?

**Comment by azizaparveen** [comment]
@avezina I don't see the issue in John's code pen sample anymore, so this might be fixed but not seeing the fix devext yet, I reached out to Jonathan for update, will update once I hear from him

**Comment by azizaparveen** [comment]
Jonathan fixed the issue and the pr will go today https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/59726
pr link https://devtopia.esri.com/WebGIS/arcgis-js-api/pull/59676
![image](https://github.com/Esri/solutions-components/assets/138827632/dec08f68-81aa-403a-8106-51e01bc423a4)

**Comment by jmhauck** [comment]
I was awaiting table.when in our component but they mentioned we should also be checking for the table.state to indicate its fully loaded. I will add that as well today.

**Comment by azizaparveen** [comment]
This issue looks good in devext, @avezina could you please check on your side?

**Comment by avezina** [comment]
Yes the data appears to be loading as expected now
