### ISSUE TITLE
Map and table is not loading correctly in Manager when there are SGL in the web map

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#558]
### Describe the bug

This web map cannot be loaded in Manager in desktop view: https://devext.arcgis.com/home/item.html?id=886725f10b7d48c9b81ffa922d6f5189
![image](https://github.com/Esri/solutions-components/assets/50338557/96da2600-a47a-4989-9975-4fbf4ba8f4a1)

But it displays when the browser size is reduced:
![image](https://github.com/Esri/solutions-components/assets/50338557/1f8364bc-8bce-4f95-b461-32bde462c654)

You'll also notice that the layers are not listed in the layer picker
![image](https://github.com/Esri/solutions-components/assets/50338557/ae637c94-5251-4170-a390-d69935fc2a5e)

### Expected Behavior

The map should be displayed in Manager for both Desktop and Mobile views and the editable feature layers should be listed in the layers dropdown.

### Reproduction Steps & Sample

Sample web map with SGL: https://devext.arcgis.com/home/item.html?id=886725f10b7d48c9b81ffa922d6f5189
Hosted feature layer: https://devext.arcgis.com/home/item.html?id=e334785d5f3c40c58c43ab2bc406064a

### Other Relevant Info

My suspicion is that this is caused by the Subtype Group Layers in the web map.

cc @azizaparveen this may not be critical for the current release, but we should evaluate why this fails in the next release.

**Comment by sarahmcdonald7** [comment]
@avezina Do you still see this on devext? I have a map with group layers and haven't run into this behavior.
Map - https://holistic.mapsdevext.arcgis.com/home/item.html?id=bb7ea879169948bf971cdde58754477e
App - https://holistic.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=2425162d619944e18980ada06572f7be

**Comment by avezina** [comment]
@sarahmcdonald7 Yes I still see the issue with Subtype Group Layers

**Comment by avezina** [comment]
Looping in @previnWong

**Comment by previnWong** [comment]
@sumitzarkar 
what do you mean Also, _We cannot get the queryObjectIds() method in the group's feature layers due to this we are not able to see any features in the table._

what error are you getting?  You should be able to query for objectids on both the subtype group layer and the subtype group sublayer layer.  both supports that method. difference is sublayer already applies the filter in the result.

**Comment by sumitzarkar** [comment]
@previnWong 
In Manager we are getting all ids using this method
![image](https://github.com/Esri/solutions-components/assets/9443956/1c8ad08b-903e-42b0-a3b2-81b382d5da32)

We see following error on subgroup layers for queryObjectIds() method
![image](https://github.com/Esri/solutions-components/assets/9443956/794beb77-55f4-4a67-ac0f-c3e17a94c415)

**Comment by previnWong** [comment]
@sumitzarkar the error you are seeing is correct.  Currently, that method does not exists in SubtypeGroupLayer-SubLayer, only queryFeatures.  
https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-support-SubtypeSublayer.html#methods-summary

For now, you need to stay at the parent Group Layer and query ObjectIds there with an additional where clause on SubtypeCode so you have a count on each subtype.

**Comment by prachichawande-ct** [comment]
@avezina 
## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impact on runtime |If the configured web map has the subtype group layers or normal feature layers then the map should be displayed in Manager for both Desktop and Mobile views and the editable feature layers should be listed in the layers dropdown
||On change of layers, should display the features in the table|

**Comment by azizaparveen** [comment]
This looks good to me, @alix could you please check?

**Comment by avezina** [comment]
Looks good now.
For some reason, asset types are not showing the description on the Table but maybe that's not on us.
![image](https://github.com/Esri/solutions-components/assets/50338557/c91b1a5f-8054-4989-99c7-7272c3d1d85a)

**Comment by azizaparveen** [comment]
Verified in devext
