### ISSUE TITLE
Need to click twice to show fields list from Show/hide column button

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#560]
### Describe the bug

Need to click twice to show fields list from Show/hide column button. I see this behavior in both config review and runtime 
Test App: https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/manager/index.html?appid=2c438154e72c469b842d6098986f8864
![Showhidecolumn_btnissue](https://github.com/Esri/solutions-components/assets/138827632/50fada5c-c3a5-4a71-9a5c-90c91c54c95d)

Note if happens when you first load the app, after that it seems to be working as expected

### Expected Behavior

Should show the list on first click.

### Reproduction Steps & Sample

1) Launch the test app
2) Click on More button
3) Then click on Show/Hide Columns button and notice that list do not show up, click again and it shows up.

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by sarahmcdonald7** [comment]
@azizaparveen I just checked this on devext and no longer can reproduce it. Do you still see this?

**Comment by azizaparveen** [comment]
@sarahmcdonald7 can't repro this anymore in devext
