### ISSUE TITLE
Can't sort object Id in ascending order after the app loads for the first time

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#564]
### Describe the bug

After the app loads, if I try to sort using the object id arrow button it does not work but if I sort any other field using the arrows and come back to object id it works, we sort the table in descending order by default but it shouldn't have prevented users to change the sort order , the object id field do not show ascending order arrow at the beginning. it works in production, so must be a regression
Clicking on the ... button and using Sort ascending button works as expected
![image](https://github.com/Esri/solutions-components/assets/138827632/78ce89c1-cc68-43c4-a49f-0ea96b7cd57e)

### Expected Behavior

The object id field should be able to be sorted by ascending order

### Reproduction Steps & Sample

Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=4847a3a938de4aa3b1390b68d8325329
1) Launch the test app
2) Click on the arrow button and try to sort the Object Id field by ascending order
3) Notice that it does not change the sort order.

**Comment by sarahmcdonald7** [comment]
@azizaparveen do you think we can look at this for R2? Or do you think this should be fixed for R1?

**Comment by azizaparveen** [comment]
> @azizaparveen do you think we can look at this for R2? Or do you think this should be fixed for R1?

@sarahmcdonald7 it is a regression, that's why I thought it should be fixed, but if things get really busy I am ok pushing it to R2, it is a minor issue and there is workaround

**Comment by jmhauck** [comment]
@azizaparveen @sarahmcdonald7 Seems like an easy fix. Looks like the FeatureTable changed what is returned when you click that up/down button. At 4.28 it would return an object with the field name and a direction value. The direction would be "asc" "desc" or null. At 4.29 up/down still return an object with the field name and direction value but when it's cleared it just returns an empty array.

**Comment by azizaparveen** [comment]
looks good
