### ISSUE TITLE
Total number of features is not displayed

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#565]
### Describe the bug

Total number of features is not displayed
![image](https://github.com/Esri/solutions-components/assets/50338557/aff2a105-2b60-4d63-b1ce-930db45ad1e0)

### Expected Behavior

Total number of features should be displayed displayed

### Reproduction Steps & Sample

Use this web map: https://devext.arcgis.com/home/item.html?id=fa9cf987a08e42018b3756b73f392fae (vpn connection required)

> Username: admin
> Password: esri.agp

_Please do not edit the data._

1. Create a new Manager app using the web map above
2. Observe the total count of features below the table once it's loaded

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by sarahmcdonald7** [comment]
@avezina @azizaparveen do you know if there are any specific settings like filters or a certain amount of features in a layer that need to be present in order for the count not to appear? I see the count work fine in some of my apps.
<img width="231" alt="2024-02-23_10-53-03" src="https://github.com/Esri/solutions-components/assets/139994064/6c59d848-e124-4d73-b882-9a81003b826b">

**Comment by azizaparveen** [comment]
@sarahmcdonald7 I don't think so, I see this issue when I first load the app, but if I select a record, the count shows up as expected

![Image](https://github.com/Esri/solutions-components/assets/138827632/20b350e5-409b-442b-97d9-7dc13af4d7e0)

**Comment by jmhauck** [comment]
I've not been able to repro. Any console errors when this occurs?



![Image](https://github.com/Esri/solutions-components/assets/2170893/f0ffbaac-e3e0-450d-80d8-d8130bb8dbbd)

**Comment by azizaparveen** [comment]
Both me and Alix are seeing this issue, for me, when I first load the app, it works, the if I switch layers for the first time it works, then if I switch back to the first layer again, I see this issue, it is random for Alix.
Test app: https://arcgis4localgov2.maps.arcgis.com/apps/instant/manager/index.html?appid=cce4a70f27084767bc78777a7ae79832
@john could you please take a look, cc @sarahmcdonald7 

![Image](https://github.com/Esri/solutions-components/assets/138827632/f455ab5b-f0c6-4678-bcf8-b24693591170)

**Comment by avezina** [comment]
@jmhauck Looks like some kind of timing issue? Does the count know when the layers are loaded? How does it work?
Also wondering, aside from on load, does the count refresh along with the refresh interval?

**Comment by azizaparveen** [comment]
This looks good in qa
