### ISSUE TITLE
Exported labels are empty in Public Notification when the labels are coming from related tables

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#567]
### Describe the bug

This is a regression issue
Not sure if this is related to this issue https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9632, but I am still seeing the empty pop-up
Exported labels are empty in Public Notification when the labels are coming from related tables. Also the duplicate records are populating (I think this because all the pop-ups are empty, if that's the case, I am wondering if we can add validation to check and remove empty pop ups for showing up in the duplicate count)
![image](https://github.com/Esri/solutions-components/assets/138827632/894a1a16-9d55-4c09-b068-fa89a298ecc5)
![image](https://github.com/Esri/solutions-components/assets/138827632/e38ba9e4-d583-4eb1-ac9d-a211f9ec7b7e)

### Expected Behavior

The labels should be exported, the paret layer pop-up has a related record element and the related table has the label configured in it's pop-up
![image](https://github.com/Esri/solutions-components/assets/138827632/23daa42e-7878-4aaf-a982-3b7ef0ef00f6)

### Reproduction Steps & Sample

Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=cb0c9aca35e345b78a89730a4a248b7
Test map: https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=be3f58213d4c43a3be1eab52b81a6b40

**Repro steps:**
1) Open the test app
2) Select record.
3) Click on the Export tab, click Export and notice the empty label

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by sarahmcdonald7** [comment]
@azizaparveen @jmhauck Are you looking at this for today or patch A?

**Comment by MikeTschudi** [comment]
Test app added: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=71f4c0493f9248b7b08617af02eacb0a

**Comment by jmhauck** [comment]
@sarahmcdonald7 just submitted a fix in solutions components will publish later today and submit PR for the app this evening

**Comment by azizaparveen** [comment]
This looks good in devext, closing
