### ISSUE TITLE
Reporter layers need to update in the Reports and Report an incident panel when changed in the config

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#573]
### Describe the bug

The Reporter layers need to update in the Reports and Report an incident panel when changed in the config. Right now, if I change which layers have reports from the config, the panel at runtime is not refreshed until I navigate to another panel.
![image](https://github.com/Esri/solutions-components/assets/50338557/099f5d81-80d9-4f84-bdb3-ec2bfaa2cfca)

### Expected Behavior

If the selection of Reports layers is changed in the Reporter config, the Reports panel and the Report an incident panel should be refreshed programmatically to reflect this change.

### Reproduction Steps & Sample

1. Create a new reporter app using a web map with multiple layers
2. Disable Express config
3. From the Reporter config panel, check the box for some Report layers
4. Observe: all layers are still listed in the Reports panel while only the selected ones should be listed

https://github.com/Esri/solutions-components/assets/50338557/b0239eb5-d992-48e9-9b49-a0ba18793d8e

**Comment by bcree11** [comment]
@chris-fox I made an update in the app to refresh the component whenever there's an update that deals with the crowdsource-reporter. It's on dev now.

**Comment by skrishn** [comment]
@sumitzarkar Please look into this issue, if a layer checkbox is off, it should turn off the layer in the config side panel and in the runtime.
