### ISSUE TITLE
Filters are not working and multiple console errors are shown

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#578]
### Describe the bug

Filters are not working and console error: Cannot read properties of null (reading 'tagName')

### Expected Behavior

COnfigured filters should be available for a given layer

### Reproduction Steps & Sample

1. Create a new app using this web map https://arcgissolutions.maps.arcgis.com/home/item.html?id=56cf45a606484a0188d5f073b133af74
2. disable Express mode
3. setup an attribute filter on the Manhole layer and choose User input for Asset type and use dropdown
4. when you're done adding the filter, notice that the filter button does not appear in the UI above the table when you switch to the Manhole layer and see console errors

![image](https://github.com/Esri/solutions-components/assets/50338557/242bd98a-d610-4af7-a0ef-f3808e0b972c)

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by azizaparveen** [comment]
This is fixed
