### ISSUE TITLE
Secondary highlight the record that is showing in the info panel when multiple features are selected

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#580]
### Describe requirements

Got this following feedback from Mike Dagle during peer review meeting.

In the scenario below when more than one row is selected in the table, you’re able to toggle through the corresponding pop-ups. When viewing a particular pop-up I thought it would be helpful to also understand which row corresponds. The suggestion is a second highlight color (or some other visual cue) that shows me which row corresponds to the pop-up I’m viewing.

![image](https://github.com/Esri/solutions-components/assets/138827632/d3fdb5da-8ecb-4620-9a0a-1499f242cc66)

**Comment by azizaparveen** [comment]
Primary color will be blue, should be reflected in map (Web Editor), need to be implemented in Reporter as well.

**Comment by sumitzarkar** [comment]
@azizaparveen 

Could you please share the sample app for Web Editor

**Comment by azizaparveen** [comment]
We can make yellow secondary color, both in map and table

![Image](https://github.com/Esri/solutions-components/assets/138827632/6e5c510b-35ba-4ca4-91ba-da44207aefa1)

**Comment by azizaparveen** [comment]
JS API team is adding an enhancement to support for secondary highlight color,  the idea is that when hovering over a feature on the map, the associated table row could also "highlight" (without being "selected"), so it will be a matter of passing specific objectIds to a property on the table widget (basically how 'FeatureTable.highlightIds' already works) and the this highlight would also work against rows that are currently selected as well. the blue selection color they use now is semi transparent, and they might go with a light yellow/orange or similar for "highlight" (really depends on accessibility concerns and design feedback) so we would ideally see a mix of the two if a row was both selected and highlighted (and there won't be a limit on the number of rows you can "highlight" either, since it's just a Collection of objectIds). 
There are two enhancements planned that are relevant to this  issue:
![image](https://github.com/Esri/solutions-components/assets/138827632/3bdbf3bc-a21b-4a51-b5fe-04d943c1b7a9)

**Comment by sumitzarkar** [comment]
@azizaparveen 

Any updates from JS API team on this

**Comment by azizaparveen** [comment]
@sumitzarkar this is installed , I shared the installed version of the JS API in [Teams channel](https://esriis.sharepoint.com/:u:/r/sites/CybertechEsriDevelopment/Shared%20Documents/General/JS%20API/arcgis-js-api-4master.zip?csf=1&web=1&e=On9XIq)

As of now, the property is named rowHighlightIds​ and it is a Collection that accepts Object Ids (numbers).

You can simply add/remove objectIds values to the collection and the associated row(s) will appear a different color when visible in the viewport.

e.g.

table.rowHighlightIds.add(1) or 
table.rowHighlightIds.addMany([1,2,3])

**Comment by jmhauck** [comment]
@sumitzarkar we should be able to use the public next release. This would need to be imported in the demo html file that is going to be used.
 
`<link rel="stylesheet" href="https://js.arcgis.com/next/esri/themes/light/main.css" />`
`<script src="https://js.arcgis.com/next/"></script>`

@azizaparveen can you find out if we can control this secondary highlight color? It's there but I suspect we'll get asked if we can make it more prominent:

![image](https://github.com/Esri/solutions-components/assets/2170893/cd9ae1fa-d59e-4a59-88dd-dcaf50f92852)

**Comment by azizaparveen** [comment]
@jmhauck @sumitzarkar heard back from Jonathan about customizing secondary color, here is his response
"Unfortunately, this is not currently supported. Current color(s) use transparency in different scenarios to help differentiate selection/hover/highlight and varying combinations of these so one single color takes "priority", which makes the API a bit trickier"
We can wait for feedback from users and if this is something our users need, we can submit an enhancement request in the JSAPI repo.

**Comment by sumitzarkar** [comment]
@jmhauck , @azizaparveen 

- As discussed on the call, we have implemented the code to show secondary highlights.
- Currently, only the behavior is when multiple features are selected and we see them selected in the map  and on the table
- When the feature is changed using the info-card(Feature details) then that row is highlighted with a different color in the table.
![CSM-580](https://github.com/Esri/solutions-components/assets/86304626/413aada5-246e-4576-890a-b64d0abf3566)
___
## Pending items
- We need more analysis on whether we can change the highlight color of the current feature on the map, as we are using the default highlight options we need to find a way to show only one feature with different highlight options.
- Also, this code is only working on the build shared in the https://github.com/Esri/solutions-components/tree/test-latest
- We tried using 4.30 and 4.31 but it is not working and we see the errors in the console
  ![image](https://github.com/Esri/solutions-components/assets/86304626/504713ba-536d-4dc8-9cfa-30bc6435230d)

Could you please check with the JS API team if this feature is installed in the dev version or not

**Comment by sumitzarkar** [comment]
@jmhauck @azizaparveen 

> We tried using 4.30 and 4.31 but it is not working and we see the errors in the console

This is resolved and we are able to see the expected result with 4.30.

@jmhauck 
- Only one thing to notice in the below code is that to avoid the lint error on using rowHighlightIds we need to use the table as **"any"**. Once the JS api lib is updated for solutions component we can remove this **as any**
![image](https://github.com/Esri/solutions-components/assets/9443956/0b4c61db-a0e5-482e-8760-7f5d483fef46)

**Comment by azizaparveen** [comment]
@sumitzarkar highlight row with secondary color looks good, did you have a chance to looks at highlighting features in map as well?

**Comment by sumitzarkar** [comment]
@azizaparveen 

>did you have a chance to looks at highlighting features in map as well?

Is it ok if we plan this for next release, so that we can check all possible cases and solutions for this?

**Comment by azizaparveen** [comment]
> Is it ok if we plan this for next release, so that we can check all possible cases and solutions for this?
yes, I will close this one and create a new issue for map.
