### ISSUE TITLE
Highlight feature in the map when hover over feature in the list

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#583]
### Describe requirements

The new Web Editor has a nice feature when viewing the list of selected features you can hove over the record in the list and it highlights in the map. This would be a nice addition to Reporter.

**Comment by sumitzarkar** [comment]
@chris-fox @skrishn 

Could you please share a sample app for the web-editor

**Comment by chris-fox** [comment]
@sumitzarkar, you can go here and login with your AGOL credentials:

https://www.arcgis.com/apps/webeditor/?webmap=f270f3b668534c26bfdc4ab38dfae86e

Select some features and then open the selection pane:

![image](https://github.com/Esri/solutions-components/assets/6796763/6fca0cdb-ed28-4702-8ce2-886bb6d0b8b1)

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact at runtime | On hovering over the features in the feature list, the hovered feature should be highlighted on the map with the secondary color (yellow)
||Highlighted feature should be removed from the map when hovering out from that feature in the feature list|
