### ISSUE TITLE
When only a single reporter layer is configured in the app we should automatically display the list of features

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#584]
### Describe requirements

If the app is configured and only a single layer is selected as a reporter layer we should skip the initial screen on load and just show the list of features. For example we should not show this view:

![image](https://github.com/Esri/solutions-components/assets/6796763/8eaac13a-7f2d-49f2-a5e1-3392d3efb348)

We should just go to this view for the layer, but remove the back arrow:

![image](https://github.com/Esri/solutions-components/assets/6796763/4f009729-24dd-444f-a7ea-564e48b1fea8)

### Impact

Simplifies the UI and reduces clicks for the user.

**Comment by skrishn** [comment]
We have an issue for this here https://github.com/Esri/solutions-components/issues/520

**Comment by chris-fox** [comment]
lol...forgot i logged that before.
