### ISSUE TITLE
Reporter R02 Features

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#590]
Planned for out to Beta, June 2024.R02 release in ArcGIS Online

**Product name**
Reporter

**Priority 2 Features**

- [x] Sign in capability - AGOL and Guest
  - [x]  Allow for anonymous usage/comments - config option
  - [x]  Support and disable likes/votes - config option
  - [x] Commenting - config option
    - [ ]  Allow for anonymous usage/comments - config option (add warning when no features exist)
    - [x]  Field picker option
    - [x]  Add an option to support images in the comments
    - [x]  Use the form in the related table (what if it's form, will it be a new screen?)
- [x]  Sort capabilities (newest/oldest, highest voted)
- [x] Filter/Attribute filters
- [x]  Splash/Cover page with sign-in capability - indicator in app header that user is signed in or not
- [ ] Language switcher 

 Mobile Design
https://www.figma.com/file/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?type=design&node-id=238-138&mode=design

Desktop Design
https://www.figma.com/file/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?type=design&node-id=676-590&mode=design&t=64K1tSCFuxGpeAec-0

App Planner - https://tasks.office.com/esriIS.onmicrosoft.com/en/Home/Planner/#/plantaskboard?groupId=bf4bf1e7-5061-4835-b42e-9702388b0d6c&planId=GHwbgM9q5UelCOTOx8PPpWQAD0KV

**Release checklist:**

 Sample app (Home page)
 thumbnail
 test suite (TestRail)
 Documentation
 Item details
 Onboarding
 Intro blog
 App example to Gallery (Nilakshi) or more for social media (marketing)
 Holistic testing
 Include in build/item copier
 Update Matrix with new app/tools

**Key Dates**

String Freeze - Thursday, May 16, 2024
Release - Wednesday, June 12, 2024

**QA tasks**

 Accessibility review
 Automate core set of test cases

**Comment by skrishn** [comment]
@sumitzarkar 

Updated designs:

https://www.figma.com/file/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?type=design&node-id=2123-559&mode=design
 
https://www.figma.com/file/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?type=design&node-id=2125-18032&mode=design

1. We've added a progress bar ( mobile and desktop)
2. Coverpage Sign In ( Similar to splash screen page in 3.X version)

  1.     Sign in on the top right corner of the app
  2.     When users enable sign-in from app details, they'd have an option to sign in to the app and eventually sign out.
  3.     In the cover page, provide an option, when the cover page is enabled. (instant app team)
  4.     Toggle button: Enable sign-in on the cover page
  5.     In this case, the current configurable button 'Enter' could be configured as say: 'Guest', and another additional button would appear next to it with the text 'Sign In'.
  6.     If users click Enter, they enter as a guest
  7.     If users click Sign in, they'll see the oAuth sign-in dialog.
3. Comments header text will show the related table name instead of string 'Comments. '
4. Configuration changes in the Reporter tab ( Designs are not updated yet) 
5. Users would see a list of layers, and for those layers that are checked, they'd see options: Like, Dislike, Show Reporting Layers. For each of the enabled options, the user will configure the appropriate field. The UI would look similar to the CountDown Instant app. https://localgovdev.mapsdevext.arcgis.com/home/item.html?id=0125d213b027409b8d549e0295832e71
6. In mobile figma designs - we've added a feature template screen before adding a point. 

Let me know if you've any questions.

**Comment by skrishn** [comment]
@sumitzarkar  here are the designs for the config panel (reporter tab). It has a sticker 'almost done'
https://www.figma.com/file/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?type=design&node-id=837-1367&mode=design

**Comment by prachichawande-ct** [comment]
@skrishn 

As discussed on the call, we can show the menu for the sort options.
Below is the updated UI for the sort

Desktop Mode | Mobile mode
-| -
![image](https://github.com/Esri/solutions-components/assets/86304626/0d4917a9-45c8-46e5-9abd-96dc148a21ce) | ![image](https://github.com/Esri/solutions-components/assets/86304626/a9af353a-b3a1-4797-b3ea-06410d5f1023)

Please let us know if any changes are required

**Comment by sumitzarkar** [comment]
@skrishn 

Here is our understanding about all the features we will be covering in this release
-  Sign in capability - AGOL and Guest - **This will handled by the instant app team** and we don't need any changes from our side
	
- Filtering - Will be covered in #593 
 
- Sorting - Will be covered in #606 
 
- Progress bar in creation workflow 
- Like dislike count - Will be covered in #591
- comments  - Will be covered in #592 
   - count
   - list
   - comments details
   - New comments
- Search Widget #546
- Show features list when only one layer - #520
- Show popup for non-editable layers - #525 
- remove next cancel - #551
- Highlight on hover - #583
- zoom scale - #360
- #598 
- #599

Please let us know if we are missing anything

**Comment by skrishn** [comment]
@sumitzarkar this list looks correct for R02

**Comment by prachichawande-ct** [comment]
@skrishn 

> * Progress bar in creation workflow
## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impact at runtime | The Progress bar should be shown as per mockups in the following panels with the respective progress:
||<ul><li>On the Create a Report button click, the layer list should be displayed with the 25% progress bar</li><li>On click of layer <ul><li> If the layer contains the template then the template panel should be displayed with the 50% progress bar</li><li>If the layer does not contain the template then the add location panel should be displayed with 75% progress</li></ul></li><li>After adding location, the editor should be displayed with the 100% progress bar </li></ul>|
||On the back click of any panel should maintain the progress of the progress bar|
