### ISSUE TITLE
Support for like, dislike functionality

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#591]
Add support for users to 'Like', 'Dislike' a report. This is a config option. User will have to select a layer and select a numerical field to store the Like and dislike values.

**Comment by sumitzarkar** [comment]
@skrishn 

We would need how the configuration will be passed for this

**Comment by skrishn** [comment]
@sumitzarkar I'm still waiting on the app configuration designs. 

Users would see a list of layers, and for those layers that are checked, they'd see options: Like, Dislike, Show Reporting Layers ( Report button shows up on the layers with this capability). For each enabled option, the user will configure the appropriate field. The UI would look similar to the CountDown Instant app. https://localgovdev.mapsdevext.arcgis.com/home/item.html?id=0125d213b027409b8d549e0295832e71 

(https://github.com/Esri/solutions-components/issues/590)

I'll keep you posted

**Comment by sumitzarkar** [comment]
@skrishn 

Could you please ask the Instatn app team to share the json structure for this configuration

**Comment by sumitzarkar** [comment]
@skrishn 

Here is how the behavior of the like/dislike icons will be implemented:
- By default, everything will be in neutral color as per mockups and only Like and Dislike will be clickable
  ![image](https://github.com/Esri/solutions-components/assets/9443956/d629ab07-7b79-41d7-821b-e130fdd94351)

- Once the user clicks like button. The like count will be increased by one and the like button will be shown in theme color to represent that the user has liked it and both the like and dislike buttons will now be disabled
 ![image](https://github.com/Esri/solutions-components/assets/9443956/aa0a5938-afc4-4a8d-a226-4358fcf6a50d)

- Similarly, if the dislike button is clicked, the dislike count will be increased by one and the dislike button will be shown in theme color and both buttons will be disabled
 ![image](https://github.com/Esri/solutions-components/assets/9443956/e1fb2b1a-5a8f-4b43-b312-28a5eb9b7a0c)

_Note: Just like the old reporter app here also users can like/dislike the same feature again and again when it is reopened._

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist

Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | Yes  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impact on feature details panel | The Like or dislike button should be displayed below the feature details panel in the following cases:
|| <ul><li>The like or dislike field should be supported by the selected layer</li><li>Like or dislike field option should be enabled and respective fields should be chosen in the configuration</li></ul>|
|| Like, dislike functionality |
||<ul><li>On clicking the like button should increment the count of a button by 1 and the button should be highlighted</li><li>If the like button is already clicked (button highlighted) then on clicking the button again should decrement the count of a button by 1 (button highlight should get removed)</li><li>If like button is already clicked(highlighted) <ul><li>On dislike button click should decrement the count of a like button by 1 (like button highlight should get removed)</li><li> Count of dislike button should be incremented by 1(dislike button should be highlighted)</li></ul>|
||On click of the like or dislike button should update the feature info's like or dislike field values by the count of like or dislike field|
||If the user goes back from the feature's details panel and selects the same feature then the like or dislike clicked button state should be maintained |

**Comment by skrishn** [comment]
@jmhauck could you merge this
