### ISSUE TITLE
Support for commenting functionality

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#592]
Let users add comments to the report if the layer has a related table. This is a config option. User will have to select a layer and select a text field to store the comments.
 

- [x]  Allow for anonymous usage/comments - config option (add warning when no features exist)
- [ ]  Field picker option
- [ ]  Add an option to support images in the comments
- [x] Show the first five comments, and users will click a view more button to show the next 5.

**Comment by sumitzarkar** [comment]
@skrishn 
- As mentioned above we need to support only one field comment? 
- Confirming this, as in the previous version we had an option to comment using the configured popup i.e. 'Display comments using the popup configuration of the related table layer'. If we need to support this then we can make use of FeatureForm in 4.x and directly use the editor widget to add the comments

Please confrim.
___
> Select a layer and select a text field to store the comments
 - Previously we used to select a single field for commenting for the whole application, now we will choose a comment field for individual related table layers - Please confirm if our understanding is correct.
 - Also, this selected field will be used to show the comments in the list
   ![image](https://github.com/Esri/solutions-components/assets/9443956/0bd06621-8bc1-40a1-ab0a-488d2b4be745)

 ___
>Add an option to support images in the comments
- Will this option be configurable or do we need to support attachment if the table hasAttachments
- Also do we need to support multiple images with comment? 
- If we are using Editor widget this will be handeled easily
___
- Comment order - by default comments will follow same order as reports i.e. reverse order of Object ID. 
- Also similar to report submission message we also need comments successful submission message and error message
___

**Comment by skrishn** [comment]
@sumitzarkar 

- Previously we used to select a single field for commenting for the whole application, now we will choose a comment field for individual related table layers - _Yes comment field is configured through app config, but we would like the feature form if layer is configured._
- This selected field will only be used to show the comments in the list - _I'll confirm_
- Support _if layer hasAttachments_
- Show _images in comments_
- Also similar to the report submission message we also need comments successful submission message and error message:__Will update you next week on this._
- Show the first five comments, and users will click a view more button to show the next 5: _Your understanding is correct_
-   Comment UI - _Will get back._

**Comment by skrishn** [comment]
@sumitzarkar I talked with Chris, and here are a few additional details on the commenting functionality. Please let me know if you've any questions. 

We'd like to show the configured pop-up. Although it can take up a lot of space, what if we show it so it is similar to the list of reports, where you see the pop-up title of the comment and then you can select it to view the full pop-up.  Also w/ regard to this, config option in the app to select a comment field doesn't makes sense anymore, so I will request the designer to remove it. If commenting is enabled, and it would need to check that the layer has a related table and that the related table is in the map.

Strings to use after submission:  "Comment submitted" and "Comment not submitted."

**Comment by sumitzarkar** [comment]
@skrishn 

We will check the feasibility and let you know.

**Comment by skrishn** [comment]
From sumit

"Regarding comment functionality, you mentioned about showing logged in user images. 
of showing list of comments using popup title we will not have this option, please confirm

![image](https://github.com/Esri/solutions-components/assets/3836616/32a0754a-2dd4-4cd2-8203-c96e178604c0)

when we get any feature we just get created by info, we are not sure if we will be able to get images for each user. using Arcgis portal api we can get details of the loggedin user in which we can get the loggedin users image but not sure about getting images of the users using just the username.
 
It would be helpful if we get any thoughts of API team on this"

@sumitzarkar I'm waiting to hear from the API team

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | Yes |   | 
Required Backward compatibility | No  |   | 
Required 508 | Yes |   | 
Need Sanitize? | No  |   | 
___
 
 
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impact on feature details panel | If the comment option is enabled in the config and the related table is present in the map then comment functionality should work as follows: |
|| <ul><li>Comment icon should be displayed with present comments counts below the feature details and beside the like and dislike buttons</li><li>Comment list should be shown below the comment, like and dislike buttons</li><li>If comments count is more than five then pagination should be displayed below the comments list</li><li>Comment button should be shown below the feature list to add the new comments</li></ul>![image](https://github.com/Esri/solutions-components/assets/86304626/aaeb48a6-bce9-4d2f-a875-2d42805a7395) |
|| Comment Functionality
|| <ul><li>On clicking an individual comment from the comment list, the comment details panel should be displayed</li><li>On click of the comment button, the comment form should be displayed with fields from the related table</li><li>After filling mandatory fields and clicking the submit button<ul><li>If form submitted successfully then <ul><li>The success message should be displayed</li><li> The feature-details panel should be displayed with the updated comments</li></ul></li><li>If form submission failed then failed message should be displayed</li></ul></ul>

**Comment by skrishn** [comment]
@sumitzarkar I noticed that the comment popup displays all the fields instead of honoring the ones that are configured in popup. Once a comment is submitted, it displays only the configured fields in the popup. 

https://crowdsource.mapsqa.arcgis.com/apps/instant/reporter/index.html?appid=fd3796ced02d483d9fa6b6a39971a44f

![image](https://github.com/Esri/solutions-components/assets/3836616/68932ed4-ae95-4c50-b972-1eaaa7c58afe)

Map https://crowdsource.mapsqa.arcgis.com/apps/mapviewer/index.html?webmap=47df7cc3aa46499aa2c51c2b627ceae7
![image](https://github.com/Esri/solutions-components/assets/3836616/2ed4a470-66cf-4838-b556-e012cf8d5d3b)

**Comment by sumitzarkar** [comment]
@skrishn 

- The fields while editing are controlled using the Form and not the popup.
- Fileds listed in the popup are only to show the popup details where as the Form needs to be configured to control any fields visibility while editing.

![image](https://github.com/Esri/solutions-components/assets/9443956/7a4a99fc-08b9-49b2-8c07-555f4aaaf1fc)
