### ISSUE TITLE
Support Filter for fitlering reports 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#593]
Support attribute filtering for filtering reports.

The app will honor the attribute filter setting configured on the layer through the app config.

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | Yes   |   | 
Required Backward compatibility | No  |   | 
Required 508 | Yes  |   | 
Need Sanitize? | No  |   | 
___
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impact on runtime| The filter icon in the feature list header should be shown in the following cases:
||<ul><li>If the configured map is the same as portal item map</li><li>If the configured filter layer expression should include the selected layer's layer expression</li></ul>|
|| On click of the filter icon should open the filter modal |
|| If the filter is applied <ul><li>The filter icon should show the indicator (indicate that the filter is ON)</li><li>The map and feature list should be refreshed with updated filtered features </li></ul>
||If the filter is removed <ul><li>The filter icon should not show the indicator  (indicate that the filter is OFF)</li><li>The map and feature list should be reset with all features</li><ul> |

**Comment by skrishn** [comment]
@jmhauck could you merge this
