### ISSUE TITLE
Report submit button overlaps with the map window

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#598]
### Describe the bug

(Int holistic testing )
After a report is submitted, the successful dialogue falls behind the frame of the map if user has quickly returned to interacting with the map

![image](https://github.com/Esri/solutions-components/assets/3836616/06a567c8-bc69-4e61-a907-41a1136b1be9)

### Expected Behavior

It should not be overlap. 

### Reproduction Steps & Sample

Submit a report, and quickly interact with the map feature to reproduce this issue.

**Comment by sumitzarkar** [comment]
@skrishn 

- This is the outline offset of the map.
- this can be overrided using css in Insatnt app. However, could you please confrim with Instat app team if this is the correct way.

![image](https://github.com/Esri/solutions-components/assets/9443956/84789916-2f8a-43b2-b5f5-d159527e7033)


@jmhauck  - please suggest

**Comment by jmhauck** [comment]
@sumitzarkar We don't want to eliminate the border...just make sure it doesn't overlap. Please adjust the z-index of the alert.

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
|Impact on runtime UI|On submitting a report, the report submitted success dialog should not displayed behind the map, especially if the user quickly returns to interacting with the map|
