### ISSUE TITLE
Suport for sort capability to sort reports

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#606]
https://github.com/Esri/solutions-components/issues/590#issuecomment-2049247027

sort options : newest, oldest, highest voted, lowest voted

**Comment by skrishn** [comment]
https://github.com/Esri/solutions-components/issues/590#issuecomment-2049247027


As discussed on the call, we can show the menu for the sort options.
Below is the updated UI for the sort

![image](https://github.com/Esri/solutions-components/assets/3836616/90be2ea1-0a52-4ff0-945f-e0b8d805f7e7)

![image](https://github.com/Esri/solutions-components/assets/3836616/8ad2abd4-c867-452a-ac42-337ddc16dad7)

**Comment by skrishn** [comment]
@sumitzarkar @prachichawande-ct 

Looks good. How are we handling the scenarios?

1. When like is not enabled in the layer - I'm expecting we don't show the options (Highest and lowest vote) in that case
2. When like was once enabled but disabled - In this case, there would be values in the like field, but it would be confusing to sort the reports based on the values. So, we wouldn't display it.

**Comment by sumitzarkar** [comment]
@skrishn 

> 1. When like is not enabled in the layer - I'm expecting we don't show the options (Highest and lowest vote) in that case
> 2. When like was once enabled but now disabled - In this case, there would be values in the like field, but it would be confusing to sort the reports based on the values. So, we wouldn't display it.

In both the scenarios we will not show the **Highest voted** and **Lowest voted** options for sorting
