### ISSUE TITLE
Add a floating info icon at the bottom right of the app when Cover page or Introduction window option is on

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#608]
### Describe requirements

In this release, Instant App team added Cover page or introduction window parameter in About  -> App Introduction tab, when this option is on but the cover page or Introduction window is closed, we would like to show an info icon so users can access it from this icon button
![image](https://github.com/Esri/solutions-components/assets/138827632/2c3ed8a5-bc94-4e02-b6d3-8c223d143d40)
![image](https://github.com/Esri/solutions-components/assets/138827632/8435ed11-bd8b-433f-beaf-5d341ce682f1)

**Comment by sumitzarkar** [comment]
We have some questions on this:

@azizaparveen 
- Do we need to show the info icon only when Introdution window is selected in the config?

@jmhauck
 - Is this Introdution controlled from Instat app or will it be created in Manager
 - If it is from instant app, how can we open it from the floating info button in the app. 
 - Do we have any mechanism in place for this, Or this needs to be done in the instant app?

**Comment by jmhauck** [comment]
@sumitzarkar we should emit an event when that button is clicked. They should be able to listen for the event and trigger the opening of the cover page.

**Comment by prachichawande-ct** [comment]
@azizaparveen 

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | Yes  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | Yes
Impact at runtime | The Floating info icon should be displayed at the bottom right of the app
||The icon should be displayed according to the theme (light/dark)|
||On click of info icon should emit an event|

**Comment by azizaparveen** [comment]
@sumitzarkar the floating icon is showing even if the Cover page or introduction window option is off , both in config preview and runtime
![image](https://github.com/Esri/solutions-components/assets/138827632/a2069da5-fd6d-4f78-a726-6fae73c6b0de)

**Comment by sumitzarkar** [comment]
>the floating icon is showing even if the Cover page or introduction window option is off , both in config preview and runtime

@jmhauck 

Please add pass the boolean value to the manager component, we will add the condition to show the info button when this boolean value is true

**Comment by azizaparveen** [comment]
@sumitzarkar. clicking on the floating icon is not opening when the floating icon is clicked here is a test app https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=d30ffa4fcdde411f8ced045a26d72030
I have the Introduction window parameter on, 
**To repro:**

1. after launching the app, click Enter, the window will go away , 
2. Then click on the floating icon and notice that it does not open it back

![image](https://github.com/Esri/solutions-components/assets/138827632/77b4cbef-f849-48ff-b08a-3ad28fc2c1eb)

cc @sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen @jmhauck 

- We have added the code to show the coverPage/InformationWindo icon
- UI For Information Window 
   ![image](https://github.com/Esri/solutions-components/assets/9443956/7052c8d1-b503-44f9-903e-3f1f06a848c5)
- Event or information window clicked will  be **showIntroductionWindow**
- UI For CoverPage
   ![image](https://github.com/Esri/solutions-components/assets/9443956/884ee8e0-994a-4bb1-8665-2d0fcf355b0d)
- Event or cover page clicked will  be **showCoverPage**

**Comment by azizaparveen** [comment]
This looks good in qa
