### ISSUE TITLE
Expose/update some light bulb text in the 'Create Report' panel

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#623]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9948
"I have had two requests to edit the lightbulb message when submitting reports with categories. Two areas of feedback are they don't like categories and reports. I am wondering if we should expose this so it can be edited. Or change it to be something more generic like make a selection

![image](https://github.com/Esri/solutions-components/assets/3836616/b48fa1c3-48fe-4d70-a861-be4a992ac249)"

Discussion with Beth

Option 1 We can hide the light bulb message as the app is intuitive without the message.
Option 2 Rename it to a generic term as " Make a selection from the list below" 

Also, we may have to rethink the terms such as reporter, and categories we have used across the app. Instead of providing several configuration options, we can think of an approach to configure it once, and it's applied throughout.

**Comment by chris-fox** [comment]
I agree with making it not specific to Reporter, I asked to update the strings to remove references to reports. See: https://github.com/Esri/solutions-components/issues/599#issuecomment-2037306002

As a result we removed report from the text in devext. It just says 'Please choose a category'. I am good with changing it to Make a selection from the list below.

**Comment by chris-fox** [comment]
The strings referenced in #599 to my understanding are all of our non-configurable strings so we should be good to not having any report terms in the strings, but i would be interested if there are other strings that were missed.
