### ISSUE TITLE
Nothing happens when a layer or report button is clicked. 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#627]
### Describe the bug

When a layer or report button is clicked the future list doesn't open. It throws a console error too. This behavior is noticed after the latest code drop for the Like, dislike functionality

### Expected Behavior

The feature list should open

### Reproduction Steps & Sample

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=68df99390ba1483caf917741bb3ae353

![image](https://github.com/Esri/solutions-components/assets/3836616/99aa71fb-876e-4e48-96cd-3107741840dd)

**Comment by skrishn** [comment]
@sumitzarkar looks like its working now.

**Comment by sumitzarkar** [comment]
@skrishn 

OK, please let us know if any action required form our side on this

**Comment by skrishn** [comment]
Closing this issue as its not reproducible anymore
