### ISSUE TITLE
Cannot hide fields in Manager, console error is being generated in devext

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#632]
### Describe the bug

Hide fields from Field column or from the main menu ->Show/ hide column is not working , clicking on these buttons are generating console errors. This is a regression issue.
![image](https://github.com/Esri/solutions-components/assets/138827632/cae6bd2c-e2c9-421e-abeb-c77cd9cf1430)

### Expected Behavior

We should be able to hide/show column

### Reproduction Steps & Sample

Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=d30ffa4fcdde411f8ced045a26d72030
1) Launch the test app, 
2) Click on the more button from any column and notice the console error
3) Similarly from main menu, click on More ->Show/hide column and and notice the behavior.

**Comment by sarahmcdonald7** [comment]
@azizaparveen I haven't been able to reproduce this on my end either.

**Comment by azizaparveen** [comment]
I can't reproduce it anymore, thanks for checking this
