### ISSUE TITLE
Coded value shows in popup in app instead of display value 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#640]
### Describe the bug

The popup in the app will show the coded (stored value) instead of the label (displayed value)

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10050

### Expected Behavior

The display value is shown in the popup in the app, matching the map

Screenshots
map:

![image](https://github.com/Esri/solutions-components/assets/3836616/bae79213-cbfb-4b3e-a861-f98f7b71f6ac)

app:
![image](https://github.com/Esri/solutions-components/assets/3836616/300961f7-f026-48db-ba6c-de987a681772)

### Reproduction Steps & Sample

To Reproduce

Use a map with a feature that contains a list
Configure the popup to use the field with a list in the title of the popup
Create a reporter app
Notice in the panel the code value is shown
If you click on a feature the popup of that features is correct, it's just in the panel
Test App
map: https://nw-brews.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=c52f8dbcbbdc42949abbc512a9a6408f
app: https://nw-brews.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=70daf6a1396d4953b1c4b33ff6e4f68b

**Comment by sumitzarkar** [comment]
@skrishn 

This is known issue for now please check  - https://github.com/Esri/solutions-components/issues/611#issuecomment-2069095905

We are analysing if we can enhance the popup-utils in this relase to resolve the issues mentioned in https://github.com/Esri/solutions-components/issues/611#issuecomment-2069095905
