### ISSUE TITLE
Increase the font size of comments text

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#641]
The font size appears too small, and can we increase the size?
![image](https://github.com/Esri/solutions-components/assets/3836616/1520762a-1a4c-45e1-8f42-72414b7d2a86)

**Comment by sumitzarkar** [comment]
@skrishn 

Is this about the font size of comments in the list?

**Comment by skrishn** [comment]
@sumitzarkar yes, it appears smaller than the rest of the text.

**Comment by sumitzarkar** [comment]
@skrishn 
- We had kept the font size x-small(10px) when showing the list of comments as, comments could be longer and we could see more text.
- However, we can increase it to match the other contents and update it to small(13px)
- We have updated the font-size will deliver it in the next code drop

| Font x-small (Current delivered) | Font small (Updated)|
| ------------- | ------------- |
| ![image](https://github.com/Esri/solutions-components/assets/9443956/235ee6df-bad8-4f8e-b36b-feceac6ace40) | ![image](https://github.com/Esri/solutions-components/assets/9443956/18aa0548-ce56-47c6-8555-2cad034a1644)  |
