### ISSUE TITLE
Hide zoom button when Map is hidden

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#642]
### Describe requirements

Zoom button is visible and active when map is hidden and if I select a record.Since Zoom button is relevant when map is visible, I think we should hide it when map is collapsed.

![image](https://github.com/Esri/solutions-components/assets/138827632/8e991d0a-01d9-4dbc-9e83-4562dda1cf5a)

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen 

As discussed, lets push this to next release
