### ISSUE TITLE
Manager is not showing delete button and not sorting in descending order even though Delete capability is enabled in the layer when the app first load

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#645]
### Describe the bug

We are seeing an issue with Manager in devext, it is not showing Delete button when it first loads and also sorting in descending order using ObjectID. Refresh the browser fixes the issue.

### Expected Behavior

it should show Delete button in disabled state and Table should be sorted using ObjectId descending order.

### Reproduction Steps & Sample

Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=f69be4bf902e4494a8827b13c12ff769

Launch the app and notice that Delete button is missing and Table is not sorted using ObjectId in descending order
![image](https://github.com/Esri/solutions-components/assets/138827632/84c480fe-0239-426c-9526-7002dfe8fad6)

**Comment by sumitzarkar** [comment]
@azizaparveen 

We are not able to reproduce this in the above app.
![image](https://github.com/Esri/solutions-components/assets/9443956/f76ca4fe-ed27-4e53-b1ae-d807d8e43ab0)

**Comment by jmhauck** [comment]
@azizaparveen merged the potential workaround...ready to review tomorrow

**Comment by azizaparveen** [comment]
Looks good in devext
