### ISSUE TITLE
Add an icon to indicate the location when using search for creating features

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#653]
### Describe requirements

Currently, it only zooms and centers into the searched location when searched during the create reports functionality and doesn't indicate where to add the feature. Let's implement the behavior we have reporter 3.x that adds an icon in that location for point features

![image](https://github.com/Esri/solutions-components/assets/3836616/37aa0b41-b7f9-4285-9630-db25dc375ec6)

**Comment by sumitzarkar** [comment]
@skrishn 

This functionality is in place. However, this will work only for point features, could you please check and let us know if you see any issues

**Comment by skrishn** [comment]
I'm not able to reproduce it anymore. So, I'm closing it.
