### ISSUE TITLE
Pop-up title it doesn’t show the line breaks when viewed in the list

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#657]
### Describe the bug

If you have a text field that has line breaks/paragraphs and use it as the pop-up title it doesn’t show the line breaks when viewed in the list, it does show the line breaks when you click into the comment and view the pop-up.

### Expected Behavior

It should show the line breaks/paragraphs

### Reproduction Steps & Sample

https://solutions.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=8714150a87274607a9164cda19d82c2f

Select the first Animal report and view the most recent comment.

**Comment by sumitzarkar** [comment]
@skrishn 

## Cause
 - Styles to consider the line breaks were not added. 
___

## Solution
- Added css - **white-space : pre-line**

___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | No
Impact on RTL | No
Impact on runtime |   When Popup titles has any line breaks those should be shown in the UI
___
