### ISSUE TITLE
Increase the size of Like, Dislike and Comments button

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#658]
The buttons appear small, so we'd like to increase them to the next size (medium) like the image below.

![image](https://github.com/Esri/solutions-components/assets/3836616/4f857dd7-29e9-456a-a61f-b33077aee5fa)

**Comment by sumitzarkar** [comment]
@skrishn 

- In the above image only the comment icon is enlarged, do we want to increase the scale only for comments or all three items?
- Out of the three items Comment is just an icon whereas Like and Dislike are calcite buttons.
- If we want to increase the scale for the buttons, please let us know which of the following sizes should be used
 ![image](https://github.com/Esri/solutions-components/assets/9443956/48e23680-0eea-4830-a985-7599bc401fc9)
- If we want to match with the above image we need to use the medium for comments and large for buttons
 ![image](https://github.com/Esri/solutions-components/assets/9443956/7e5062ba-61bd-4789-a516-8ccd757dcfd7)

**Comment by sumitzarkar** [comment]
@chris-fox 
Here is how it will look after the changes:
- Like & Dislike button scale - m
- comment Icon scale - s

![image](https://github.com/Esri/solutions-components/assets/9443956/b58b2b66-0d81-46bd-947e-dc89a7d6c45e)

**Comment by chris-fox** [comment]
@sumitzarkar, i was just playing around with it and the buttons-container class has a padding of 10px which is quite large for that space. Is this a calcite standard or could we go smaller like 4px or 6px so the bar isn't so large with the buttons?

![image](https://github.com/Esri/solutions-components/assets/6796763/79c29fee-2ad3-46d5-a31a-caf31ec8d263)

**Comment by sumitzarkar** [comment]
@chris-fox 

Yes, we can reduce the buttons-container padding to 4px. 
Here is the screenshot after updating padding to 4px
![image](https://github.com/Esri/solutions-components/assets/9443956/f0e6024c-03bc-4611-b72f-c29c0814cf60)
