### ISSUE TITLE
Change this label when specifying the location of the report to ‘Please provide the location’.

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#659]
Change the following label to 'Please provide the location’.

![image](https://github.com/Esri/solutions-components/assets/3836616/464dab98-a2ef-4372-89f9-3f5110e0630d)

**Comment by sumitzarkar** [comment]
@skrishn 

## Solution
Add calcite-notice to the create-feature components
 
 
Add the required functions, files required to show the messages
 
 
While creating new feature Show 'Please provide the location' while specifying location
___
## Dev Checklist
 
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | Yes   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impacted Component |  Create-feature
Impacted Areas | While specifying the location show 'Please provide the location' message

**Comment by sumitzarkar** [comment]
@skrishn 

The solution provided above is implementd but the string is used from https://github.com/Esri/solutions-components/issues/547#issuecomment-2335033187

Hence, now we are seeing below message
![image](https://github.com/user-attachments/assets/0c6434e5-27b8-4d55-8890-57b1f8657749)
