### ISSUE TITLE
Sharing a report throws console error

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#660]
### Describe the bug

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10052#issuecomment-4796253

When sharing a report, (I tried copy link option), there's a console error in the copied link app.

@sumitzarkar Comment from IA team "This is a problem in the crowdsource component. The getFeatureDetailsFlowItem function is running before this._currentFeature is set and there's no check for this._currentFeature"

### Expected Behavior

User should be able to share a report.

### Reproduction Steps & Sample

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=08ff09b203e546eea46d62a4ab7ddef5

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=08ff09b203e546eea46d62a4ab7ddef5&layerid=Polling_9868&oid=15&center=-88.221;41.7214&level=16&hiddenLayers=Polling_1544;Polling_6916

![image](https://github.com/Esri/solutions-components/assets/3836616/d749979d-44c4-41b3-978e-c16ff7116ede)

**Comment by sumitzarkar** [comment]
@skrishn 

We have identified the fix and will deliver it in the next code drop
