### ISSUE TITLE
Adding/viewing comments jumps

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#662]
Adding or viewing comments jumps, and we'd like to avoid it. 

![2024-05-29_19-13-24 gif](https://github.com/Esri/solutions-components/assets/3836616/4cadccc5-32c1-4f5b-9434-9abadb8b1239)

https://lgtest.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=f27c3ff257fc4f7281f370a04561188b

**Comment by sumitzarkar** [comment]
@skrishn 

This is because when we open the comment/feature details the details are renderd again.

We don't see any control over this.

**Comment by chris-fox** [comment]
This loading/jumping doesn't concern me for the reason mentioned above.
