### ISSUE TITLE
Add find current location button next to search

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#665]
### Describe requirements

When the ‘Find current location button’ is enabled in the configuration, we should provide this button next to the Search for an address or place box in the screenshot above. This would allow mobile users to use their current location to set the report location.

![image](https://github.com/Esri/solutions-components/assets/3836616/01a05024-94e1-409a-8fbc-9fdf480efab0)

**Comment by sumitzarkar** [comment]
@skrishn 

- Currently, we use the Search widget and it shows the option to **Use current location**. (This is the default functionality of search)
 ![image](https://github.com/Esri/solutions-components/assets/9443956/0add93b5-964b-401d-834c-22843c25cc4d)
- The ‘Find current location button’ in the configuration controls the visibility of the locate tool on the map.
- Currently, this configuration is not considered in the Reporter component and it is used for the map tools only by the instant app
![reporter665](https://github.com/Esri/solutions-components/assets/9443956/60e707db-d341-49c7-881d-95c8fffbc406)

**Comment by chris-fox** [comment]
Thanks @sumitzarkar, i didn't previously see the use current location option from the search dropdown, that works well. I think we can close this issue.
