### ISSUE TITLE
Title is blank when field has domain on it. 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#673]
This app there are some blank values in the titles:
https://solutions.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=eb1ec6c86e7e427db37bda43bf93ffec

If you click one of them you will see the title display correctly. The issue is occurring because I am using a field from the layer and that field has a domain on it, but the values for that feature are not defined within the domain of the field, so our list is not displaying them, but the pop-up can display them.

**Comment by sumitzarkar** [comment]
@skrishn 

This is becase the attribute value is not found in the layers domian
for example: reqcategory = Land Use 
![image](https://github.com/Esri/solutions-components/assets/9443956/ea0874b0-a008-4c0d-8f5a-78884c5d9bb2)
![image](https://github.com/Esri/solutions-components/assets/9443956/b039fcf7-2bb7-4dae-9376-25cd2d307966)

We have updated the code to handle this case. In such cases we will show the attribute value instaed of the fomatted attribute value
![image](https://github.com/Esri/solutions-components/assets/9443956/de8f3946-ed55-46db-9224-8d7d62b9b47f)
