### ISSUE TITLE
Text appears in the top when commenting 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#674]
In this app, comments is configured as the title, and it has multiline text, and when entering a value in the comments, the same text shows up in the top.  In this app, I still see it when changing it to single-line text. I'm noticing this after this fix https://github.com/Esri/solutions-components/issues/654. 

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=39657e1adb434f9086823b993c70057f

![image](https://github.com/Esri/solutions-components/assets/3836616/553457d7-6255-4b2d-a76f-203a654b9bbe)

Also, I'm not able to repro it in this app - https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=22861dc390674183a89f7ddd4edfd974

**Comment by chris-fox** [comment]
@skrishn, I believe you can configure that in the form, you can specify a field as the title of the form

**Comment by sumitzarkar** [comment]
@skrishn 

This is expected because the formInfo has Comments as the title of the form

![image](https://github.com/Esri/solutions-components/assets/9443956/2897cb28-0935-4f5e-8725-839f2faa1d45)
![image](https://github.com/Esri/solutions-components/assets/9443956/2bca3602-3aca-4c77-a8ee-28e6b57713c0)

**Comment by skrishn** [comment]
@sumitzarkar I find it distracting when submitting a comment. Can we avoid it?

**Comment by chris-fox** [comment]
I don't think we should change the behavior, users can configure the title of the form to whatever they want. They can remove it as well if they don't want a title.

**Comment by skrishn** [comment]
I agree with Fox, but the behavior of the text appearing as you type in the field isn't the best user experience and we should change it. 

![comments](https://github.com/Esri/solutions-components/assets/3836616/5237d89b-613a-47f9-8286-973b1e5f970f)

**Comment by chris-fox** [comment]
its the same in the map viewer, this is just coming from the edit widget. I don't think we should override the behavior.
