### ISSUE TITLE
Multi-select using shift is not working as expected

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#676]
### Describe the bug

Seeing two issues, these are reproducible in production
1) If I press shift and then select one record, it is selecting additional/all records 
2) If I select a record then press shift and click to select the rows in between, it is selecting additional records that are not adjacent rows.

**Note**: I am seeing the 2nd issue particularly when it is sorted by other field except ObjectID

### Expected Behavior

it should select rows between the first and last selection

### Reproduction Steps & Sample

Test app: https://solutionsqa.mapsqa.arcgis.com/apps/instant/manager/index.html?appid=4156582eafb649a88bcf97ec3c745443

**Comment by jmhauck** [comment]
@azizaparveen can you check this on dev today and let me know if you are still seeing anything?

**Comment by azizaparveen** [comment]
It looks great John, can't repro any of the two issues we were seeing.
