### ISSUE TITLE
Make editable and non-editable features distinguishable in form

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/solutions-components#709]
### Describe requirements

It's hard to distinguish which fields are editable and which ones are not in the Edit feature panel, unless you configured it.

### Other Relevant Info

Map Viewer form, you can see which fields are read-only.

![image](https://github.com/Esri/solutions-components/assets/2781011/9e1b1427-16ff-4a77-92cf-fa5538add8e6)

Edit feature form, you can't see which fields are read-only.

![image](https://github.com/Esri/solutions-components/assets/2781011/7785f87c-d87e-4ee8-85d8-17faeed1f1b2)

### Impact

For someone who didn't configure the form, they would know because as soon as they tried to edit a field the text wouldn't update.

**Comment by azizaparveen** [comment]
We can ask the JS API Editor widget team for this enhancement, Manager uses Editor widget. Right now map viewer shows this in the Form only.

**Comment by azizaparveen** [comment]
submitted an issue in JS API repo: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/63994

**Comment by azizaparveen** [comment]
JS API team is not going to add this enhancement in editor widget, but suggested that we can use description property of the field elements to indicate if a field is read only.
![image](https://github.com/user-attachments/assets/2a313168-66fa-4f65-bdba-5d281590070b)

**Comment by chris-fox** [comment]
@azizaparveen, I think there is something going specific to Manager and how we are showing this in our widget, maybe we are overriding some CSS?

If you compare Manager to Map Viewer and Reporter the readonly fields are really difficult to see the difference. For example in the screenshots below, both Map Viewer and Reporter readonly fields have a grey background and looks a little more clear they are not editable. Manager, I don't really see any difference between the editable and non-editable fields.

I think 

Map Viewer:

![image](https://github.com/user-attachments/assets/1d2baa31-72a2-4f48-941d-965c3274a22f)

Reporter:

![image](https://github.com/user-attachments/assets/2e4020b1-8933-4868-9b67-fc284fa1a62b)

Manager:

![image](https://github.com/user-attachments/assets/fd874d0d-44b7-4f76-b4a5-4c74bbc8ba62)

Looking in the browser debugger it looks like we have overriden the calcite-color-background variable and set it to none (transparent). This is changing the background color of that read-only element. When I change it to #f8f8f8 which is the default in Reporter and the Map Viewer it looks like this in Manager:

![image](https://github.com/user-attachments/assets/dcb27428-ece9-43b8-b696-485674e00f68)

![image](https://github.com/user-attachments/assets/df2cf255-39d2-4343-b81e-3307d2c80c3f)

This looks like something that would be pretty easy to resolve for R3.

**Comment by sumitzarkar** [comment]
@chris-fox @azizaparveen 

- To resolve this instead of changing the color to #f8f8f8 we need to remove the override completely. As it is causing issues in dark theme.
- We have removed this override completely and it is working as expected in both darm and light theme.

We will deilver this in the next drop, please check and let us know if any changes required

**Comment by azizaparveen** [comment]
This looks good in devext
