### ISSUE TITLE
The Reporter Instant App in ArcGIS Online is not adhering to the pop-up configurations in the Web Map

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#731]
### Describe the bug

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10357

Pop-ups will show up even though they are disabled on the WebMap itself.

### Expected Behavior

If popup are disabled in webmap, app should honor it.

### Reproduction Steps & Sample

1. Create a web map with 2 (or more layers) > in the example provided, we have two polygon layers
2. Disable pop-ups for all layers in the web map > right-side > Pop-ups > turn off the radio button
3. popupsdisabled.jpg
4. Save the web map
5. Create an instant app using this new map > Select the Reporter Instant app
6. Configure the application to only query one of the layers in the map > Publish
7. Notice how we can click on the other layers (polygons) in the map and the pop-ups will show up even though they are disabled on the Web Map itself.
8. popupsdisabled2.jpg

Reporter Instant App: https://essorg.maps.arcgis.com/apps/instant/reporter/index.html?appid=0df4c13d275e433a869ef91c3f7c479c
Web Map: https://essorg.maps.arcgis.com/apps/mapviewer/index.html?webmap=7fb3fa5427f741068e5d527f19509653 

devext test case: https://nw-brews.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=ddb4b97df89b4bc4b7a4fcb43f5466ca gray street lights have popup disabled

**Comment by skrishn** [comment]
Another customer reporter the same issue from Tucson

**Comment by sumitzarkar** [comment]
@skrishn @chris-fox 

- Currently, we are not checking for the layers property **'popupEnabled'**. 
- However, we can consider this property to show the feature details.
- We show feature details in two ways 
     1. For reporting layers in the side panel
     2. For non-reporting layers on the map popup
- Do we want to consider this for both or only for the non-reporting layers popups shown on map?
- If we want to consider this for reporting layers we have to render the list without the right arrows and have to disable its click.

**Comment by sumitzarkar** [comment]
@skrishn 

 
## Cause
- We were not checking the state of popup is enabled/disabled from map
- Popup was showing for non-reporting layers even when disabled from map 
___
## Solution
Added condition to show popups for non-reporting layers only when the popups are enabled from the  map 
___
## Dev Checklist
 
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impacted on non reporting layers | If popup is disabled from map popup should not shown
|| If popup is enabled from map popup should shown on the map
