### ISSUE TITLE
Allow signed in users to view their submissions through My reports button

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#732]
### Describe requirements

We'd like to add the 'My reports' functionality similar to Crowdsource reporter template where signed in users would see their report submissions. We'll get the designs in.

**Comment by skrishn** [comment]
@sumitzarkar Updated designs are here https://www.figma.com/design/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?node-id=2123-7961

**Comment by skrishn** [comment]
@sumitzarkar Once the user clicks or toggles (we're waiting on designs for a toggle option) on my reports from the user profile dropdown, we'd only filter out user reports that belong to the layer and display them in the panel as they're clicking through the layer. There will be no changes in the report panel UI. Once the user toggles off, all the reports will be displayed. The map also updates to show only those reports.

**Comment by jmhauck** [comment]
@sumitzarkar this sounds good to me

**Comment by sumitzarkar** [comment]
@skrishn 

___
## Solution
 - https://github.com/Esri/solutions-components/issues/732#issuecomment-2278209804
___
## Dev Checklist
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on Layer/Feature list | If layer supports creator field and user clicks or toggles on my reports from the user profile dropdown
|| Layer list count should be updated to show the count of my reports only
|| Map view and feature list should  show only those features which are created by logged in user
|| The Features list should support the filters and sorting option applied at runtime

**Comment by skrishn** [comment]
@sumitzarkar Toggling the My Reports button on is not filtering the reports. Could you take a look.

**Comment by sumitzarkar** [comment]
@skrishn 

We added boolean property showMyReportsOnly in reporter, this needs to be updated when the switch is toggled from instant app.

@jmhauck could you please check if this code is added in the instant app?

**Comment by skrishn** [comment]
@sumitzarkar this is info I got from IA team when they added the toggle button "There's an issue with the component though, it doesn't watch for changes in the prop showMyReportsOnly so when toggled nothing happens. It only works if showMyReportsOnly is initially true. I could reload the component when it changes or they could watch for changes in the component. Not sure what approach the other team wants to do."

**Comment by sumitzarkar** [comment]
@skrishn  We will add watch on the property and share in next code drop
