### ISSUE TITLE
Display symbology in the layer list 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#738]
### Describe requirements

From customer (Department of Transportation and Mobility from City of Tucson, AZ) "Can symbology be placed in the layer list as opposed to having it separately located in the legend?
The images used to appear on the older version of the citizen problem reporter solution. "

![image](https://github.com/user-attachments/assets/d941ffc6-e6bf-4431-a592-f0d60eb7291d)

Another user requested this enhancement from Douglas county too.

**Comment by skrishn** [comment]
@sumitzarkar We'll have an internal discussion and get you designs if this goes in this release.

**Comment by sumitzarkar** [comment]
@skrishn 

- Crowdsource Reporter works with group/webmap when group is configured in the application. The list of webmap is shown and the images shown in the list are the Webmap thumbnails.
- Reporter Instant app works only with a webmap and shows the layer list. 
- It would be not easy to show the symbology of the layer in layerList as the layer could have multiple symbols defined. 
- However, we can show feature symbology in featuresList just like nearme
![image](https://github.com/user-attachments/assets/ec0fb27e-01fb-4423-b5a5-3acbbec9fe6d)

**Comment by chris-fox** [comment]
I received the same feedback at the user conference. They were not interested in the symbology at the feature level. They wanted the symbols at the layer level. There is not a web map property to support this. We might need an app configuration that would allow us to add an image per layer in the web map.

**Comment by skrishn** [comment]
They're adding this option at the config level https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10377

**Comment by sumitzarkar** [comment]
@skrishn 

Please let us know your thoughts on this

**Comment by skrishn** [comment]
@sumitzarkar  Implement to display feature symbology as done in Nearme.

**Comment by sumitzarkar** [comment]
@skrishn 

___
## Solution
- Generate the feature render symbol using [symbolUtils in ArcGIS Maps SDK for JavaScript](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-support-symbolUtils.html#renderPreviewHTML) 
- Render the generated feature symbol in feature list, and adjust the styles 
___
## Dev Checklist
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impact on Feature list | If 'Show feature symbology' is enabled from configuration then display feature symbol in feature list

**Comment by skrishn** [comment]
@sumitzarkar symbology doesn't display when there are no features. I added one feature to one of the layer and it still doesn't show. I created another map, with only the layer and it displays.

![image](https://github.com/user-attachments/assets/a477db0b-b692-47a4-a518-bf5cccda3361)
![image](https://github.com/user-attachments/assets/e19ae279-aedd-4e1d-8714-6d18ba523476)

![image](https://github.com/user-attachments/assets/166fc3bf-affc-48ab-b74c-6ff2e5a1f0ac)

**Comment by sumitzarkar** [comment]
@skrishn 

- Symbology is shown in the featureList and not in  the layerList 
- In the first screenshot the we see layerList, if we navigate to the features list of the Animal layer we should be able to see the symbols
- Whereas when we have only one layer we directly show featureslist hence you can see symbols in the last screenshot
