### ISSUE TITLE
Make comment icon clickable

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#739]
### Describe requirements

From customer "
Can the text of the "Comment" button be altered? Or, can the comment bubble icon become interactive?

In the test, some people were confused because they clicked on the comment bubble icon without success, thought there was no way to add a comment, and gave up. Crowdsource Reporter had the interactive bubble icon, so maybe they were simply used to that format, but the “Comment” button was not intuitive either because of its location or text. My sense that the Comment button is not intuitive is based on two of the six people who tested the demo app saying they weren't able to leave a comment. If I had to guess why, I'd say it is the location and the text itself. The button is somewhat low and out of the way, and maybe if it were directly below the feedback, it would be easier to recognize. Also, in Crowdsource Reporter, the comment icon text when hovering was something like "Leave a reply," which connotes a reaction to the existing feedback, whereas "Comment" is more neutral and does not necessarily imply a response to what has already been written "

![image](https://github.com/user-attachments/assets/444fb8d7-dfa4-4155-9c81-795cb43d025e)

**Comment by skrishn** [comment]
I have also clicked comment button accidentally and expected it to work. Since this is placed next to two interactive buttons, this seems like a valid enhancement. We may also need to add tooltips to the icons.

**Comment by sumitzarkar** [comment]
@skrishn 

Do we want to open the new comments form on click of the comment icon?

**Comment by skrishn** [comment]
> @skrishn
> 
> Do we want to open the new comments form on click of the comment icon?

We'll have an internal discussion and get back.

**Comment by chris-fox** [comment]
I like the idea of making the comment button clickable to open the comment form.

**Comment by sumitzarkar** [comment]
@skrishn @chris-fox 

Please let us know your thoughts on this.

**Comment by skrishn** [comment]
@sumitzarkar The icon will be clickable. And we're keeping at the bottom for backward compatibility

**Comment by sumitzarkar** [comment]
@skrishn 

As discussed on the call, we will make the comment icon clickable and it will function same as the comment button shown at the bottm to add new comments.

**Comment by sumitzarkar** [comment]
@skrishn 

## Solution
- Emit an event when comment button is clicked
- Listen the event and open the comments form
___
## Dev Checklist
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on feature details component | Open comments form on comment icon click
