### ISSUE TITLE
Add config option to disable creating new features.

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#756]
### Describe requirements

Instant App team add a new config option to allow app users to create features when enabled
![image](https://github.com/user-attachments/assets/1507e71b-3c51-46b1-855b-5172c861a554).

The Pr is created, once merged we can add logic into Manager component. Prop name is CreatFeatures in the config panel. John added a placeholder prop for now.

**Comment by azizaparveen** [comment]
https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/4725#issuecomment-4901120

**Comment by sumitzarkar** [comment]
@azizaparveen 

- As per our understanding currently, the Manager App can only edit the features, we cannot create new features in the manager.
- With this ticket, do we want to allow users to create new features in the manager?
- If that is correct we need some more info on this ticket to understand how the workflow will be initiated and also need the designs

**Comment by azizaparveen** [comment]
> @azizaparveen
> 
> * As per our understanding currently, the Manager App can only edit the features, we cannot create new features in the manager.
> * With this ticket, do we want to allow users to create new features in the manager?
> * If that is correct we need some more info on this ticket to understand how the workflow will be initiated and also need the designs

@sumitzarkar yes we are going to support creating features, IA team is working on finalizing the design, once it is done I will share it with you

**Comment by azizaparveen** [comment]
This looks good in devext
