### ISSUE TITLE
New App Layout settings in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#769]
### Describe requirements

We are going to add a new layout setting option in the config for Manager, this option will provide more flexibility for our users to choose appropriate layout when creating new features/records .

here is the setting details.
![image](https://github.com/user-attachments/assets/0aa42b20-777b-465c-b7d5-6c598a83c9af)

When the Pr is created and merged, we can add logic into Manager component. 
### Other Relevant Info

https://github.com/Esri/solutions-components/issues/756

**Comment by azizaparveen** [comment]
@sumitzarkar, We are adding two new layout options in Manager, so all together we have 3 layout options that users can pick from.

- [ ] Add logic in Manager to reflect the selected, 

1. Split view (the default option)
![image](https://github.com/user-attachments/assets/1d46f77e-f414-421c-a6bc-45a80e48edad)
2.Table view (map will be hidden)
![image](https://github.com/user-attachments/assets/da8a56a0-7adb-498e-b894-39f770389d6c)
3. Map view (Table will be hidden)
![image](https://github.com/user-attachments/assets/adb501a4-21cd-4206-8abf-6c2701a20843)

- [ ] Add tooltips for Split view, Table view, Map view
- [ ] Add icons for these layouts
![image](https://github.com/user-attachments/assets/e13ffa19-09a5-4f15-be4a-daec9a9f1759)
- [ ] When layout changes from Split view to Map view or Map view to Split view, make sure the map center and scale remains same.

**Comment by azizaparveen** [comment]
This config option is added under Theme & Layout -> Theme -> Layout 
This will be available in a day or two
![image](https://github.com/user-attachments/assets/1243efd5-6292-4a8d-b841-ca73eba0f7a7)

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by jmhauck** [comment]
@sumitzarkar I just added the appLayout prop and IA team has added the config options for this.

**Comment by azizaparveen** [comment]
@sumitzarkar 
The new layout looks and working great. just couple of issues

- [ ] When switching layout the tools bounce around in the toolbar, is there anything we can do about it?
- [ ] from the split and table view can we make the separator bar (between toolbar and table) thinner, we like the width of it in map layout

![Image](https://github.com/user-attachments/assets/cb6f22a2-1631-4b5d-a1a1-10be4a85225b)

![Image](https://github.com/user-attachments/assets/8de77591-a251-4954-a09b-a6ab9c53b3d8)

**Comment by sumitzarkar** [comment]
@azizaparveen 

> When switching layout the tools bounce around in the toolbar, is there anything we can do about it?
-  For this we had a discussion with @jmhauck , and seems like this is known limitation for now

> The split and table view have a separator bar between toolbar and table, it is a bit thicker, and the map view do not have any, can we have single width separator for all the layouts
 - We will update the code to reflect this seperator, we will deliver this in next code drop

**Comment by azizaparveen** [comment]
@sumitzarkar I am still seeing thick separator
![image](https://github.com/user-attachments/assets/920d470c-3f3c-4e75-8ad8-007ac2400bab)

**Comment by azizaparveen** [comment]
After discussing this with John, it looks like we do not have option to change the border thickness right now since it does not leverage any css variables that can be overwritten. It is associated with the internal calcite-progr4ess component to the table and  
its where they indicate when the table is loading new data. So we will keep it as is.
cc @jmhauck @sumitzarkar
