### ISSUE TITLE
Create new feature/record  in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#770]
### Describe requirements

Design file:https://www.figma.com/design/NwwYvCoSufP3m1nYTZgpB4/Crowdsource-Manager-%7C-23.R3?node-id=2703-5759&t=wusuQEQCH68CFO7M-0

- [ ] Add a Create feature/record button in the Info Panel, the label text will be dynamic, we already have logic in the app that detect only table is viewing or Table and map is viewing. If only table (without geometry) is visible, it will say Create record otherwise it will say Create feature.
- [ ] **When Create feature button is clicked** 
   - [ ] and layout is Split view and a feature layer is selected, Manager will switch the layout to Map view, make sure the scale and map center do not change during switching
    ![image](https://github.com/user-attachments/assets/6045ae1d-c7fe-4d10-b59e-077129e38a74)
   - [ ] Manager will go to Editing mode, it will show the editing template, users will be able to create a feature on the map and populate its attribute values. In this state, user will also be able to select a feature and update attribute values
   ![image](https://github.com/user-attachments/assets/fea6b003-35a8-47ab-95d3-5c490e802a17)
   ![image](https://github.com/user-attachments/assets/768e618e-3ef8-4187-95fa-3d3f795d886e)
   - [ ] Once a feature is added, it will go back to the Editing mode like Map Viewer. From this state using the back button user's should be able to navigate to the initial state
   ![image](https://github.com/user-attachments/assets/d08e1f2c-30d7-4ded-9c3b-a4228238f965)

- [ ] **When Create record button is clicked**,
   - [ ] It will open the editor form where users will be able to add a new record.
     ![image](https://github.com/user-attachments/assets/02bc7674-46a4-4243-8abb-a583ce50386c)
   - [ ] Once done with creating record, it will remain in the same state, so users can add more records.   
    ![image](https://github.com/user-attachments/assets/aecd6888-a0d9-4c3d-afbd-8bfcbcfedc4f)

   - [ ] Users will be able to go back to initial state using back button.

### Relevant Issues

https://github.com/Esri/solutions-components/issues/756
https://github.com/Esri/solutions-components/issues/769
https://github.com/Esri/solutions-components/issues/275

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by azizaparveen** [comment]
Create features config option is added in the map section.
![image](https://github.com/user-attachments/assets/4d08dfd5-829d-472b-b571-ddfcb40b4a5f)

**Comment by sumitzarkar** [comment]
@azizaparveen @jmhauck 


## Solution
- Get the createFeature boolean value from configuration
- Show Create Feature/Record button based on the configuration **createFeatures** 
- Use the create-feature component to create a feature
    - On clicking the create-Feature button
       - Switch the layout to map-view layout
       - Hide the information header of the card-manager
       - Show header on the top of the card-manager component with back action
       - On clicking the back action close the create-feature component and go to initial stage
       -  If back button is clicked close the create-feature component and show the information header
       - After submitting the form redirect the user to Editing mode to add/edit more features
    - If Table is selected from Feature table then 
       - Use create-related-feature component to add reocrd in table
       - Show create 'Create record' button at the bottom of card-manager component
       - On clicking the create record button open the editor form where users will be able to add a new record
       - If back button is clicked close the create-related-feature component and go to initial stage
       - Once done with creating record, it will remain in the same state, so users can add more records.

___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | Yes   | | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | Yes  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | No
Impact on RTL | No
Impacted Components |  1. create-feature <br/> 2. card-manager <br/>  3. crowdsource-manager
Impacted Areas | - Test new functionality for Creating features <br/> Editing features when in create mode <br/> Layout changes on create button click 
___
