### ISSUE TITLE
Add support for editing tools/editing feature geometry

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#774]
### Describe requirements

We have heard requests for being able to edit geometry of features in Manager. This would also include adding the editing tools in the app too.
Now that we will have map based layout available I think adding support for editing geometry makes sense.

https://community.esri.com/t5/arcgis-instant-apps-questions/editing-geometry-in-new-manager-app/m-p/1392824#M2353

We used to have this functionality and  we disabled that in https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9018#event-23104403 in this issue and in this PR https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/pull/9034

**Comment by azizaparveen** [comment]
Instant App team added a config option for allowing Editing geometry in the app.
![image](https://github.com/user-attachments/assets/a2371d21-1bc3-49c5-aa04-0cefda59f449)
![image](https://github.com/user-attachments/assets/ccca371e-09d9-4a53-9610-a23eb511393f)

**Comment by jmhauck** [comment]
@azizaparveen in terms of edit tools...do we have some design on where they would be displayed?

**Comment by azizaparveen** [comment]
> @azizaparveen in terms of edit tools...do we have some design on where they would be displayed?

@jmhauck no, not for this release, I discussed this with Sarah and we are ok with how it used to work before in R3, if I selected a record from the table or map it used to show the controls in the map for geometry editing, we think that should be enough for this release. Next release we are planning to add some selection tools and may be we can revisit this in R1.
![image](https://github.com/user-attachments/assets/a597aa0a-2652-471b-a946-193e7f477282)

**Comment by azizaparveen** [comment]
This looks good in devext
