### ISSUE TITLE
App doesnt recognize editing changes made in the map

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#782]
### Describe the bug

I created an app with a map with editing enabled on all layers, later I disabled editing on one of the layers. The app still shows it in the layer list and lets me view the popup details. When I click to report an incident, it only shows the layer with editing enabled. I've to open the config which then removes the non-editable layer from the list. 

### Expected Behavior

App should only display only editable layers and be aware of the changes made to the map.

### Reproduction Steps & Sample

https://localgovdev.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=4003be1c6b5e4264b1834b8854b7192e
https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=3fca24b4b3384735bb61ec770cc66780

![image](https://github.com/user-attachments/assets/103cdeb2-7771-4563-9719-3cf361ac1746)

![image](https://github.com/user-attachments/assets/03b01dcf-f506-47ae-9656-34b9a509b7d8)

![image](https://github.com/user-attachments/assets/d9ce2164-a872-4129-9ba0-97b223c1d8af)

**Comment by sumitzarkar** [comment]
@skrishn 

If we remove the layers from map which are not editable, then we may face issues in Polling app configuration.
Consider if the layer is set to uneditable and we need only comments from user on the features then we will not able to show such layers in the app.

Please let us know your thoughts on this, if this case is not valid we can check for the layer editingEnabled property and remove the layer from reporting layers

**Comment by skrishn** [comment]
@sumitzarkar My understanding is that for both reporter and polling, the layer has to be editable to show in the report panel. I created a reporter for polling capability with the same map, and the non-editable layer doesn't appear in this list

![image](https://github.com/user-attachments/assets/c037e24f-968c-461d-a291-e82966a50008)

So, removing the non-editable layer from the list shouldn't affect polling.

**Comment by sumitzarkar** [comment]
@skrishn 

___
## Cause
- We were not checking if editing of the feature layer is enabled/disabled from the map
___
## Solution
- Update the code to show layers in the layerlist only when editing is enabled from the map
___
## Dev Checklist

Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on layer list | If any feature layer editing is enabled then only show the layer in the layer list
|| If editing is disable then don't show the layer in the layer list
