### ISSUE TITLE
Add support for bulk attribute updates

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#784]
### Describe requirements

There will be support added for batch editing with the new bulk attribute update component. The JS API team is working on building the new component.
The new bulk attribute updates component will require that the app provides the ability to select multiple features to edit. We are able to support that in Manager by using the multi-select ability in the table.
The design is ready 

- [ ] In Split view and Table layout the tool will be in the main toolbar, it will show when multiple records are selected and layer has atleast update capability enabled.

![image](https://github.com/user-attachments/assets/a5eaf9db-eb27-4323-8af1-99bfc15adb94)

- [ ] In Map view layout, it will be in the More menu

![image](https://github.com/user-attachments/assets/c33e1c01-981f-40dd-bc66-4b3eeb1299b4)

**Comment by azizaparveen** [comment]
@sarahmcdonald7

**Comment by azizaparveen** [comment]
@sumitzarkar if you could work on adding the button that will be great, once the component it ready, hopefully we will be able to connect it without much effort.

**Comment by sumitzarkar** [comment]
@azizaparveen 

We have added button for 'Edit Multiple', whenever the component is ready we can use it

**Comment by azizaparveen** [comment]
This is pushed to R1 next year.

**Comment by azizaparveen** [comment]
@sumitzarkar could you please hide this button for R3?

**Comment by azizaparveen** [comment]
Looks good in devext
