### ISSUE TITLE
BUG-000169079 The ArcGIS Instant Apps Public Notification template search bar result selects all the adjacent features touching the main feature if the search source layer is duplicate of the input layer in ArcGIS Online.

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#789]
### Describe the bug

The ArcGIS Instant Apps Public Notification template search bar result selects all the adjacent features touching the main feature if the search source layer is duplicate of the input layer in ArcGIS Online.
Salesforce ID: [BUG-000169079](https://desktopqa/SFTriage?sfid=BUG-000169079)
Salesforce Submitter: Sanat Shetye
Salesforce Submit Date: 7/11/2024 4:22 PM
Salesforce Bug Type: Usability
Salesforce Severity: Medium
Steps to Repro:
Steps to Reproduce:

·      Create a web map with any data ideally with Polygons with common boundaries.

·      Create a duplicate of the same layer in the web map.

·      Layer1 will be used as the Input layer and Layer2 used as the Search source layer. Both have the same feature layer with the same source.

·      Create a public Notification Instant app from the web map.

·      Enable layer1 under layers to include option for Public Notification and keep the layer2 toggled off.

·      In Search Configuration, click on Add Source and use the layer2 as the source. ArcGIS Online Geocoding service can be removed.

·      Configure the search/display fields and click on Done.

·      Publish and launch the app. Click on create new list.

·      Search for any attribute with input layer as layer1 and search source as layer2.

### Expected Behavior

It should select only the searched feature

### Reproduction Steps & Sample

Test App: https://arcgis4localgov2.maps.arcgis.com/apps/instant/notification/index.html?appid=74e2864b51084609a03013ceb4b047ce
Test Map: https://arcgis4localgov2.maps.arcgis.com/apps/mapviewer/index.html?webmap=b6ec0d8093964c54b03184f1609d2ec0

1. Launch the test app.
2. In the search box, select TaxParcels-Copy as search source. search for parcelid 0710202003, notice that two records are showing in the suggestion

![image](https://github.com/user-attachments/assets/ec3e0915-73a8-483a-9e94-6caa4473f0e5)

3. Notice that adjacent parcels are selected.

### Other Relevant Info

@jmhauck are we using spatial query in this scenario? If yes and if we are not doing any geometric comparison, can we switch to use OID instead? reference issue : https://github.com/Esri/solutions-components/issues/148

**Comment by jmhauck** [comment]
@azizaparveen this should be ready to test

**Comment by azizaparveen** [comment]
@jmhauck the fix looks good, noticed another unrelated issue though, the image is not loading in the preview or at runtime 
Here is the app: https://solutions.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=bdbd9a4587cd4e2d95bfae2c09b783bb
![image](https://github.com/user-attachments/assets/b09eaa34-38ff-47f7-9021-97c9d3f26eb6).

**Comment by jmhauck** [comment]
@azizaparveen this should get that icon issue:
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/pull/10513

**Comment by jmhauck** [comment]
@azizaparveen finally got to the bottom of the icon/assets issue...should be good now.

**Comment by azizaparveen** [comment]
Icon and the bug fix looks good in devxet
