### ISSUE TITLE
Add logic to show/hide layer features, search distance and selection tools in PublIc Notification app

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#790]
### Describe requirements

Instant Apps team is going to add few new config options to show / hide layer features, search distance and selection tools. The request came from users who wants to simplify their app. Here are the details, once these are added we need to add logic in the component.
![image](https://github.com/user-attachments/assets/9b7e2475-adef-418b-b6e2-087843f40ff5)

**Comment by azizaparveen** [comment]
https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/4766

**Comment by jmhauck** [comment]
@azizaparveen should be good now

**Comment by azizaparveen** [comment]
This is implemented
