### ISSUE TITLE
URL param doesn't open the feature details in the panel

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#802]
### Describe the bug

The URL param zooms and dispaly popup on the map but it doesn't open the feature details on the panel.

This is a critical workflow in special events permitting solutions

### Expected Behavior

Zoom to the feature on the map and open the popup details on the left panel.

It works in polling 3.x https://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=031495f7c0ba4b07b25fb78c63f38cfc&test=987.90

### Reproduction Steps & Sample

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=77a64a967cc64605b98050c0aa7b0c33&&test=sarah

![image](https://github.com/user-attachments/assets/393a59c4-acf9-4072-81ad-7d2bd1d15dc9)

![image](https://github.com/user-attachments/assets/781bc964-ad37-4ed9-b9ed-0daa4ac95351)

**Comment by sumitzarkar** [comment]
@skrishn  

- We analyzed this and found we have not implemented this functionality(URL parameter name) for reporter-component
- However, currently, if you set the URL param configuration the popup for the feature is opened, it seems like this functionality is implemented in the reporter instant app @jmhauck please confirm
- The reporter component supports opening the feature details if the following props are set on the component
     - layerid 
     - oid

- Please check comment for more details - https://github.com/Esri/solutions-components/issues/550#issuecomment-1947755353 

@jmhauck 

Please let us know if this will be handled by the instant app or do we need to support this in component

**Comment by skrishn** [comment]
@sumitzarkar IA fixed this issue, but I notice the following

1. Clicking back to feature list doesn't display all the features
2. When going to layer, doesn't update the map because its zoom into the location of the previous feature,  I have to click on a feature to render it on the map.

![reporter issue url param](https://github.com/user-attachments/assets/fba3a644-1c00-4467-a371-ebe68cc5d347)

**Comment by sumitzarkar** [comment]
@skrishn 

As discussed on the call, we only fixed the issue discussed in https://github.com/Esri/solutions-components/issues/802#issuecomment-2321888306
