### ISSUE TITLE
Type error on clicking comment button

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#810]
### Describe the bug

Layer has two tables related to it, when I create an app with both the tables it works. 

When I remove one of the tables, i.e; the first table, and create an app, I get this console error

![image](https://github.com/user-attachments/assets/497eb831-425b-46e1-9e48-56c28bde8e36)

When  I remove the second table, the app works.

### 

### Expected Behavior

App should work when it has multiple related tables and in this case it considers the first table, but even when one is removed it should work.

### Reproduction Steps & Sample

Both tables in the app
https://localdeployment.maps.arcgis.com/apps/instant/reporter/index.html?appid=d270b35efc394118ba4c0bf0c1e6c1a2

One table is removed with error
https://localdeployment.maps.arcgis.com/apps/instant/reporter/index.html?appid=f457244d79de418a92dd0d519b17a651

Second table is removed and it works

https://localdeployment.maps.arcgis.com/apps/instant/reporter/index.html?appid=98be6752135143c4866fe38386e6719b

@sumitzarkar I'll share the creds separately.

**Comment by sumitzarkar** [comment]
@skrishn 

We analyzed this ticket and here are our findings:
 - The reporter component checks for the relationships on the layer and uses the first relationship to show and add comments
 - In this case, we get the relationship information in the layer. However, the table used in the relationship is removed from the map and hence the code is breaking.
 - We will add the additional check to see if the related table is present in the map or not based on that the comments will be shown and can be added from the app
 - In this case, as the table is not present and hence we will not be able to see the comments button in the app 
 ![image](https://github.com/user-attachments/assets/ab67fe97-9b9e-4e71-ad55-270a09075e64)

Please let us know if any changes are required to this

**Comment by jlindemann** [comment]
We have a relationship with two tables related to one feature layer.  It seems that both these tables need to be in the webmap in order for the app to work.  We likely will not want the other table to be shared so would be ideal if we could have just the one layer in the map.

**Comment by skrishn** [comment]
@sumitzarkar per Jer's comment, the layer has two related table and if one is removed i.e; the first one from the map, can we use the second table from the map to use as a comment table?

**Comment by sumitzarkar** [comment]
@skrishn 

- We support commenting on only one related table(the first one if the layer have multiple tables) - https://github.com/Esri/solutions-components/issues/592#issuecomment-2024391415
- If required we can enhance the code to check for all the relationships and see whichever table instance is found in the map then we can use that as the first valid relationship for commenting
- This may require low-medium efforts and need retesting of the commenting functionality

Please let us know your thoughts on this

**Comment by skrishn** [comment]
@sumitzarkar Yes, I remember it takes the first table when there are multiple tables, and with more solutions adopting reporter, we may encounter this scenario a lot. So, to accommodate the needs,  let's go ahead with the implementation. In case it takes a high-effort, we can move it to the next. So, please keep me posted. 

cc @jlindemann

**Comment by sumitzarkar** [comment]
@skrishn 
___
## Cause
- If layer has multiple tables, we were always considering the first table for adding the comment
- But if the first related table is removed from map it was throwing error
___
## Solution
- If layer has multiple relationships, look for all the relations ships and consider it valid only when it's table is present in the map
- https://github.com/Esri/solutions-components/issues/810#issuecomment-2311565165
___
## Dev Checklist
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact while adding comment | If first related table is deleted from the map then use the another table for adding and showing comments
|| Check with different combimantions for related tables and if removed from the map.
