### ISSUE TITLE
Map view layout feedback in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#819]
### Describe requirements

With the new map view layout,  we would like to make the following changes

- [x] If related table is present in the map, disable the layer because we can't really navigate to related records by selecting records from map.
- [ ] Tools to show in the toolbar first, if overflows then go to More menu
- [ ] Add Clear selection button

we can select features from map but there is no way to clear the selection unless we change the layout, could we please add Clear selection button in the More menu?

  - Add Clear selection button in the More menu
  - If no feature is selected it will be disabled just like the split and table view
  - It will be enabled when there is selection.

![image](https://github.com/user-attachments/assets/d2950538-b5cf-41ea-a174-bddfe10872f3)

- [ ] Change initial icon and instruction in the Information panel to map icon and the text would be "Select a feature from map to get started. Click while pressing the Cntrl key to select multiple features".

![image](https://github.com/user-attachments/assets/da5cb328-298f-4505-9bee-222fbf1881fe)

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen 

>If related table is present in the map, disable the layer because we can't really navigate to related records by selecting records from map.

If related tables are present in the map do we want to disable them from the layer picker shown in that mapview?
![image](https://github.com/user-attachments/assets/8a69047b-dc83-4e96-840c-b55416ae6cc2)

Could you please confirm if our understanding is correct if not please add more details on this - which layer to be disabled when we have related table in the map

**Comment by azizaparveen** [comment]
> Could you please confirm if our understanding is correct if not please add more details on this - which layer to be disabled when we have related table in the map

Yes, you are correct, the layer should be disabled in layer picker

**Comment by chris-fox** [comment]
@azizaparveen, @sumitzarkar, just to clarify. I think we would want all tables to be disabled, whether they are related tables or not. It is just not possible to select a table record in the Map View, so it makes no sense to make it the active layer/table.

**Comment by pratiksabale07** [comment]
___
## Solution
- Disabled the table from map-layer-picker when in map view layout
- Tools should shown in the toolbar first, if it gets overflows then more dropdown button will shown and it the tools should shown in the more dropdown button
- Added clear selection tool in the map view layout's tool bar to clear the selection if feature is selected
  - If no feature is selected then clear selection tool should shown as disabled
  - Enable the clear selectionn tool when feature is selected  
___
## Dev Checklist


Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | Yes   |   | 
Required Backward compatibility | No  |   | 
Required 508 | Yes  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impacted components |  1. map card </br> 2. layer-table </br> 3. crowdsource-manager
Impact on map view layout |- Table should shown as disabled from map-layer-picker
|| - Tools should shown in the toolbar first, if it gets overflows then more dropdown button will shown and it the tools should shown in the more dropdown button
|| - Clear selection tool should shown in the map view layout's tool bar to clear the selection if feature is selected </br>  - If no feature is selected then clear selection tool should shown as disabled </br>  - Enable the clear selectionn tool when feature is selected

**Comment by azizaparveen** [comment]
This looks good in devext
