### ISSUE TITLE
Comments are not showing in enterprise portal

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#820]
I can only see comment count but the comments aren't listed. 

(I've sent creds in chat)

https://rpubs22401.ags.esri.com/portal/apps/instant/reporter/index.html?appid=0d5131f21e48476b80ab2a2e8a9100be

![image](https://github.com/user-attachments/assets/60a96ee4-a0df-4aa4-a6ad-23373de5a3c5)

**Comment by skrishn** [comment]
console error 
![image](https://github.com/user-attachments/assets/015ca136-c733-493c-862c-300024a871c2)

**Comment by sumitzarkar** [comment]
@skrishn The shared app is not accessible, seems like it requires VPN

It would be helpful if you could share some other sample app or webmap for this

**Comment by skrishn** [comment]
@sumitzarkar It should be accessible now. 

map: https://rpubs22401.ags.esri.com/portal/home/item.html?id=23b5ba15f6fc4f1c9ecd565616b7f028

**Comment by sumitzarkar** [comment]
@Suba ***@***.***> this is still not accessible. We got the issue and working on it.
This is due to different object id field name.

Could you just share the screenshot of fields in the related table, so that we can confirm the issue which we are observing and the one you shared is same

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by skrishn** [comment]
@sumitzarkar 
![image](https://github.com/user-attachments/assets/49fc3ff7-f9f8-4fca-b794-9fa836365d83)
![image](https://github.com/user-attachments/assets/4fa1e2e4-ad98-4da0-8d56-ddad1d4aea7b)

**Comment by sumitzarkar** [comment]
@skrishn this is the same issue we are observing we will fix this and deliver it by EOD today

**Comment by sumitzarkar** [comment]
@skrishn 

## Cause
- Difference in the fieldName for object id field of the related table

___

## Solution
- Update the code to get the objectId field from the table instance
- Also, updated code when getting the parentKey value as the keyfeild recevied from the relationships having casing differences in some cases. 
for e.g. 
  - Field in relationship 
     ![image](https://github.com/user-attachments/assets/6f770718-3957-4850-b01d-65463ba40baf)
  - FieldName in fields array of layer
     ![image](https://github.com/user-attachments/assets/f214b0be-f3a0-4695-b5fd-3de1d8b835da)

___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impacts on commenting functionality |  Test comments functionality
___

**Comment by skrishn** [comment]
Verified.
