### ISSUE TITLE
Add icons to layer switcher to indicate layer type in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#821]
### Describe requirements

Add icons to layer switcher to provide indication of the layer type
![image](https://github.com/user-attachments/assets/44168bf2-c874-4759-98ff-6c9ab1a4dd89)

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen 

## Cause
- Enhancement

___

## Solution
- Add icon-start property to calcite-dropdow-item showin layer/table list

___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impacted functionality |  - Map Layer picker component <br/> - The layer picker should show layer/table icon in the dropdown
___

**Comment by azizaparveen** [comment]
This looks good in devext
