### ISSUE TITLE
Mobile designs for R3 on layout changes In Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#824]
### Describe requirements

We would like to keep the current mobile design for Manager that means

- [ ] When device size changes, Manager will default to split view (the current default layout Split view, for tablets (landscape) it is split view, in tablets (portrait) and smaller devices map and table)
- [ ] Runtime layout options will not be visible
- [ ] we wouldn't allow new features to be created or geometry edits on mobile for R3.

**Comment by azizaparveen** [comment]
@sumitzarkar @pratiksabale07 When seeing the app in iPad pro (both portrait and landscape, runtime layout options are showing up
![image](https://github.com/user-attachments/assets/2d40cbb2-d4fe-4db3-b465-f39995d44df5)

**Comment by sumitzarkar** [comment]
@azizaparveen 

According to the current implementation, we are hiding runtime layout options only for mobile, for tablets it will be the same as for desktop

**Comment by azizaparveen** [comment]
This looks good in devext
