### ISSUE TITLE
User profile image and initial doesn't align with header text

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#839]
User image/initial looks close to the top border and doesn't align with the header text. It appears to be a regression.

Devext:

![image](https://github.com/user-attachments/assets/02177e36-db65-4579-aef4-67f4c8f342ae)

![image](https://github.com/user-attachments/assets/db1e44f0-fb66-40fe-9818-e1ef77d7f316)

Production:

![image](https://github.com/user-attachments/assets/1bfe0502-561f-49c2-98dd-da24d74bff3f)

**Comment by sumitzarkar** [comment]
@skrishn 

This is not a port of reporter component, this shoud be in instat app component.

@jmhauck Please let us know if any changes required from our side for this

**Comment by skrishn** [comment]
Tracking it here https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10588
