### ISSUE TITLE
Submitting a report with attachments throws a discard edits message

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#847]
In production, when I add a report, and attach a file, it takes me back to the form and before submitting the report, it shows discard edits message. I have to click the continue editing button or hit submit to submit the report. 

https://localdeployment.maps.arcgis.com/apps/instant/reporter/index.html?appid=fdd05d8357264042a43973f44e8a61e1

![image](https://github.com/user-attachments/assets/83878ece-68a2-46f1-b1a2-ce92871060af)

![Attach issue](https://github.com/user-attachments/assets/921294ea-583c-4d20-a878-09fb7060172b)

In dev, it shows the message on form load. I've started to see this today only.  https://localgovdev.mapsdevext.arcgis.com/home/item.html?id=884338be7e9e4e31bca9f58d31da4663

**Comment by skrishn** [comment]
This is noticed in Enterprise 11.4 too.

**Comment by skrishn** [comment]
In devext, I see this message when providing an address to add a feature. Not noticed in production. 

![image](https://github.com/user-attachments/assets/f906103b-3b2d-4b7b-a552-cfcc9724866a)

**Comment by sumitzarkar** [comment]
@skrishn 

This is from the editor widget JS API, We have not made any changes to this, could you please check with JS api team if any chnages in this functionality and do we need to handel it in our code seperately

**Comment by skrishn** [comment]
@sumitzarkar I can check with them. The first case is happening on production but it's not reproducible when adding a feature in map viewer. I wonder if this still be an editor widget issue.  This behavior is already been there in production but we didn't notice it. The locator issue is noticed only in devext.

**Comment by sumitzarkar** [comment]
@skrishn 

THe discrd message is shown from the editor widget, we don't have any control on it, this could be due to changes in JS API. Please check this with API team

**Comment by jmhauck** [comment]
`this._editor.viewModel.featureTemplatesViewModel.state` changes more frequently at 4.31 than it used to. This was causing `startCreate` to be fired more than necessary.

**Comment by skrishn** [comment]
@jmhauck Looks good in devext. Thanks!

**Comment by skrishn** [comment]
@jmhauck I still see the issue when adding images when submitting a report in enterprise. Has the code to enterprise been updated with the fix?
