### ISSUE TITLE
Old manager app with hide map option enabled do not show the split view layout when changed in the configuration

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#848]
### Describe the bug

I am seeing this is issue only with this old app, where hide map was enabled, after the new code merge, I was able to change the layout option from the config but the default view is showing table view
![image](https://github.com/user-attachments/assets/54a89295-5377-4c1c-9e9d-aa83ed047d11)

### Expected Behavior

It shows Split view as default view since I changed the config option to Split view.

### Reproduction Steps & Sample

Test app: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=d30ffa4fcdde411f8ced045a26d72030

1. Launch the the app
2. Notice that default view is Table whereas the config option for the layout has changed to split

I am also seeing issue in the configuration, if I changed the view to map view, it does not get updated in the preview, it does not load the map
![image](https://github.com/user-attachments/assets/ecc66e60-f3f4-4426-82ee-12e4c6f15d9c)

**Comment by azizaparveen** [comment]
![image](https://github.com/user-attachments/assets/577c8a50-50c7-478f-a06b-4d681cc4cf98)

**Comment by sumitzarkar** [comment]
@jmhauck 
For backward compatibility we are overriding appLayout to tableView when hideMapOnLoad is enabled

![image](https://github.com/user-attachments/assets/459b75d1-115e-46f3-b122-99b8511fa3dc)

is this issue has impact on how this is handled in Instant app? 

Please let us know your findings

**Comment by jmhauck** [comment]
@sumitzarkar At some point I feel like we should deprecate the prop from the component because it's now confusing what one would expect if they set both the `hideMapOnLoad` and `appLayout`. 

For now at least I think we should just honor `hideMapOnLoad` if it's true and no `appLayout` is set. If `appLayout` is set then we should honor that and ignore `hideMapOnLoad`. 

https://github.com/Esri/solutions-components/pull/867

@chris-fox do you have thoughts on the possible deprecation?

**Comment by chris-fox** [comment]
I am good with deprecating it. At this point I believe we are the only one using the component.

**Comment by sumitzarkar** [comment]
@jmhauck 

#867 changes looks good, after these changes please let us know if any other code changes are required from our side.

**Comment by jmhauck** [comment]
@azizaparveen `hideMapOnLoad` prop has been removed in favor of the new layout options. Old configs that leveraged this prop will need to be re-opened and layout option chosen for the map to be hidden.

**Comment by azizaparveen** [comment]
@jmhauck so the app with hide map layout on will default to split view unless they are opened and changed using the layout option?

**Comment by jmhauck** [comment]
@azizaparveen correct

**Comment by azizaparveen** [comment]
> @azizaparveen correct

@jmhauck  in this case can we can set the layout option to table view automatically in code? I just don't feel like it will be good experience for our users when they see the layout is different than the one they originally set?

**Comment by jmhauck** [comment]
@azizaparveen I hear you...just trying to get rid of the prop that no longer makes sense

@chris-fox when we were talking about deprecation I was thinking remove it. Should we keep the prop for some period of time to support this backwards compatibility issue?

**Comment by chris-fox** [comment]
yea sorry, i didn't understand the implications of removing it. I would like to support backwards compatibility. If there is no other way to remove the prop and support backwards compatibility than I think we should keep the prop around.

**Comment by azizaparveen** [comment]
This looks good in devext
