### ISSUE TITLE
New feature stays highlighted when a language is switched in reporter app

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#850]
I configured a new reporter app with the language switcher option. 

1. Create a new report
2. Add a feature
3. Change the language
4. Panel reloads and goes back to the layer list, which is expected.
5. The feature created in step 2 is still there and stays highlighted.
6. It's still highlighted even after creating another report

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=c51914bdd9974e1cba2cb1bd1c5dec07

![image](https://github.com/user-attachments/assets/258f1cd3-f32c-4a03-aa3b-d5374a25159b)

![LS new feature issue](https://github.com/user-attachments/assets/82d11236-2d99-4471-a997-05f857c42afa)

**Comment by sumitzarkar** [comment]
@skrishn @jmhauck 

## Cause
- We have not considered this case for the reporter component.
- In this case, when the language is changed the Reporter component is reloaded from the instant app. 
- If the user is in the create feature workflow then the editor widget is not getting destroyed.


## Solution
- To avoid this issue we can destroy the editor widget instance in the create-feature component's **disconnectedCallback** lifecycle method.
- This will make sure if the editor is created it will be destroyed and any graphics drawn/highlighted will be removed
````
 /**
   * StencilJS: Called every time the component is disconnected from the DOM,
   */
  disconnectedCallback(): void {
    if (this._editor) {
      this._editor.destroy();
    }
  }
````
@jmhauck  - please let us know your thoughts on this

**Comment by jmhauck** [comment]
@sumitzarkar this sounds like a reasonable approach

**Comment by pratiksabale07** [comment]
@skrishn @jmhauck
 
## Cause
- https://github.com/Esri/solutions-components/issues/850#issuecomment-2374016593
___
## Solution
- https://github.com/Esri/solutions-components/issues/850#issuecomment-2374016593
___
## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on runtime | The feature and its highlight should be removed when a language is switched in the reporter app
