### ISSUE TITLE
Required fields are not being validated in reporter

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#851]
In dev, when I submit a comment it's not validating if the required fields are empty. I'm able to submit a comment without filling the form. It's not reproducible in production and looks like a regression issue. 

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=7e4f6e8f23eb4e79ac1ad6ce0e4a7d99

Devext:
![image](https://github.com/user-attachments/assets/25f50838-330f-4b02-b236-f164706765bb)

Validates in map viewer
![image](https://github.com/user-attachments/assets/49df1606-ac19-41fa-875d-f6fe99831d86)

Validates in Prod:
![image](https://github.com/user-attachments/assets/1cb2fed9-d463-424a-bfa1-fbe83ae12a26)

**Comment by skrishn** [comment]
@sumitzarkar I can still repro when submitting comments on the app provided above

**Comment by sumitzarkar** [comment]
@skrishn Please provide access to the above app. Also, are you able to repro in any other app?

**Comment by skrishn** [comment]
@sumitzarkar https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=7e4f6e8f23eb4e79ac1ad6ce0e4a7d99 is shared public. Are you not able to access it. I dont have other apps that has required field set up. I'll shared if I've any.

**Comment by skrishn** [comment]
Same data but different app https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=1d87c0739da84c63822e7eaf68e7d65b

**Comment by skrishn** [comment]
@sumitzarkar the issue doesn't happen on the layer with required fields but it's noticed in the table.

**Feature layer** 
https://lgtest.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=b4e14bfc74474934b665f7db22af0aeb

![image](https://github.com/user-attachments/assets/2f85adc0-3c57-4491-81c3-a8cf5f57257f)

**Layer and table**
https://lgtest.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=b4e14bfc74474934b665f7db22af0aeb

I'm able to submit the comment without filling in the required fields

![image](https://github.com/user-attachments/assets/d4eaa4a9-f756-4b18-a4db-b727e5c2f404)

![image](https://github.com/user-attachments/assets/e158784d-6bff-487d-aa64-cd3a9af525a1)

**Comment by sumitzarkar** [comment]
@skrishn 

The Table has one Template in which all the required fields have some values defined, in some cases it is blank space, and hence, the form is getting submitted without showing any error
![image](https://github.com/user-attachments/assets/01c4a02c-c431-41e2-98c4-1a8d516d7fcf)

**Comment by skrishn** [comment]
@sumitzarkar It should validate as it does on production https://localdeployment.maps.arcgis.com/apps/instant/reporter/index.html?appid=9f33b0cbb682413f9759910049b9183a

**Comment by chris-fox** [comment]
@skrishn, it is validating correctly, as @sumitzarkar shared the template for the table is inserting a space into the RequiredTextWODefault and RequiredText fields. So they are populated, just with a space which is valid:

![image](https://github.com/user-attachments/assets/ef85ed17-0c32-4a48-a3b7-bc959ae677dc)
 
If you click into the box and clear it out you will see the validation error:

![image](https://github.com/user-attachments/assets/79ad3037-4d78-49ee-86fd-7c8c8b744608)

It just looks empty, but there is a space in the field by default. This is the same behavior in the map viewer.

**Comment by skrishn** [comment]
Thanks, @sumitzarkar and @chris-fox. Closing this issue.
