### ISSUE TITLE
Clicking back button from the related record exits edit mode instead of editing parent feature state in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#852]
### Describe requirements

Clicking back button from the related record goes back out of edit mode instead of editing parent feature state in Manager

Test app: https://arcgis4localgov2.maps.arcgis.com/apps/instant/manager/index.html?appid=6af37c89c1134c1785ddee53057be7a4
To Repro:
1) Launch the app
2) Click on a record
3) Click Edit button
4) Click on a related record
5) Related record edit panel opens
6) Click Back button
7) Notice that it goes out of the editing mode all together
It should go to the Editing parent feature mode.
![Manager_editrrformbackbuttonissue](https://github.com/user-attachments/assets/20e564ed-d8bf-4db6-81bd-82bdb4189354)

**Comment by sumitzarkar** [comment]
@jmhauck 

We analysed and here are our observations, please check and let us know if you see any solution to avoid this:
 - We are using edit-card component for this, which is using Editor widget to edit the features.
 - The editor widget is showing calcite-flow item which has back button
 - When user is navigating to edit the related record and the back button is clicked the activeworkflow is changed and this.open  property is updated to false
 - As we are watching the property and calling _closeEdit() method when open is false, the closeEdit method is navigating user back and exiting the edit mode.

Could you please check and let us know your thoughts on this

**Comment by jmhauck** [comment]
@sumitzarkar We can see this with the core widget outside our code. I'm unaware of any way to handle this. I've reached out to a Editor PE.

**Comment by sumitzarkar** [comment]
@jmhauck  - Thanks, Please keep us updated with the inputs from API team.

**Comment by jmhauck** [comment]
https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/65156

**Comment by jmhauck** [comment]
Just tested with a build from a pr that they have in the works and looked good for related records in our components. We won't need to do anything to benefit from this update other than pull in the latest js api. 

Still need the same type of support added attachments.

**Comment by azizaparveen** [comment]
@sumitzarkar could you please pull the latest js api so we can verify the fix in devext?

**Comment by azizaparveen** [comment]
This looks good in devext
