### ISSUE TITLE
Replace in lightbulb text in report creation process

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#854]
We'd like to change the text "please provide details" to something more intuitive. 

1. Like shown below, we see different text when choosing a layer and when choosing a template. I recommend we update the text shown in image 2 to "Make a selection from the list below."

![2](https://github.com/user-attachments/assets/7f0f0c2c-ada1-4228-b49e-f9e1d5e4f886)

![1](https://github.com/user-attachments/assets/9fd87018-ec57-4633-8d39-6cfd5d3c8667)

2. As discussed [here](https://github.com/Esri/solutions-components/issues/547#issuecomment-2335033187), replace the text. Use the same text as mentioned here. 

3. After adding the feature, use the same text we as do now "Please provide the details."

cc @chris-fox

**Comment by sumitzarkar** [comment]
@skrishn 

 
## Solution
Changed message to 'Make a selection from the list below' for the template picker page
___
## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | Yes   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on create-feature component |  Make a selection from the list below message should shown on the template picker page while creating features
