### ISSUE TITLE
Turning off field in popup is not being honored

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#855]
When i turn off a certain fields in the popup, its not being honored in reporter app. 

I turned off the field (Num from point layer) in popup in map viewer, but it appears when submit report form. I noticed the behavior on the table too. 

Not happening in production apps. 

![image](https://github.com/user-attachments/assets/1586dd52-5f5c-40b6-b22a-a9d9878603d5)

![image](https://github.com/user-attachments/assets/3d29483d-017b-43e3-b575-310f0712d547)

![image](https://github.com/user-attachments/assets/1b012b2d-23bf-4c2a-a8a3-1bd6d103a75a)

https://localgovdev.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=bd6447a8fa504aab85f310be114238fe

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=5b96dd73ff9444b2bdb0dc7836f77efd

**Comment by chris-fox** [comment]
@skrishn, the pop-up config is different from the feature form config. You need to configure the form on the layer to change what is available while editing.

**Comment by skrishn** [comment]
@chris-fox yes and when I tried with form and it didn't work earlier. It looks good now.
