### ISSUE TITLE
Remove/hide reset filter from the filte modal

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#868]
Related to this enhancement https://github.com/Esri/solutions-components/issues/647

Having two reset filters look redundant and let's hide/remove the first one as highlighted. 

![image](https://github.com/user-attachments/assets/e0c13ca7-a81d-478b-9d30-e510f7e46aa2)

**Comment by sumitzarkar** [comment]
@jmhauck 

To implement this we need updates in the instant app component to make reset buttons visibility configurable, just like we have a closeBtn.

FYI - @skrishn

**Comment by jmhauck** [comment]
@sumitzarkar I added another boolean prop `resetBtn` that when `false` will prevent the drawing of the "Reset Filter" button in IAC 1.0.0-beta.260. It's in our develop branch now

**Comment by sumitzarkar** [comment]
@jmhauck 

We are able to use this prop, after setting it to false the reset button is not shown.
We will deliver the code in next code drop

**Comment by sumitzarkar** [comment]
@skrishn 
## Solution
Passed false value to resetBtn for the instant-apps-filter-list to hide the reset button
___
## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on instant app filter list |  Single reset button should shown at the footer of the filter list component
