### ISSUE TITLE
Clicking reset filter button doesn't bring dropdown values 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#869]
### Describe the bug

Related to this enhancement https://github.com/Esri/solutions-components/issues/647

When I apply a filter and reset it with the botton reset filter button, the dropdown arrow switches between up and down arrow and doesn't bring the values

### Expected Behavior

It should bring dropdown values. 

### Reproduction Steps & Sample

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=1d87c0739da84c63822e7eaf68e7d65b
1. Click point layer and Apply Filter
2. Reset it with the bottom reset button
3. Notice the behavior

![dropdown](https://github.com/user-attachments/assets/b3e04912-7ca8-49be-a7b4-cd4866813426)

**Comment by sumitzarkar** [comment]
@jmhauck 

 - We are calling the newly added **forceReset** method when the reset filter button is clicked. 
 - We are not observing any console errors but when we have combobox in the filter list then thte list in the box is not shown after forceReset button click.
 - In the sample you created the force reset button was on first flow item, but in our case we have reset filter button on the same flow item where we have filter list.
 -  If we call the force reset filter UI items and filters applied are resetting but the conbobox list is not shown. 
 - When the reset button is on first flow item in this case the instant-app-filter-list coponent is re created when we navifate to filter list and we can see the combobox list
 - We updated the sample to match the case we have in reporter and we are able to reproduce this in the sample as well.
 [instant-apps-filter-list.zip](https://github.com/user-attachments/files/17114474/instant-apps-filter-list.zip)

Could you please take a look and let us know if we are missing anything in this.

**Comment by jmhauck** [comment]
@sumitzarkar I'll have an another PR to update solutions-components package for the new version if IAC after this: https://github.com/Esri/instant-apps-components/pull/425

**Comment by jmhauck** [comment]
@skrishn this should be good now
