### ISSUE TITLE
Add configurable text option for comment 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#870]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10534

"It would be nice if commenting in a related table to change that text. Just like there is a "Report Submitted Message" and button text, would be great to have equivalent options for "Comment". For Special Event Permitting solution, "Comment" could be change to "Leave Permit Review". "

strings for new text config options
label Comment submitted message
tooltip: Customize the comment confirmation message after a comment has been submitted
label Submit comment report button text
tooltip: Customize the text on the button to submit comments "

@sumitzarkar IA team is making these changes and I'd like to know if we need to do any updates at our end?

**Comment by sumitzarkar** [comment]
@skrishn 

Yes, we need to get the configured text and use it in the components. 
We will add props in reporter to use the configured text.
