### ISSUE TITLE
Clicking on Create feature button is not showing any feature template/form in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#889]
### Describe the bug

Clicking on Create feature button is not showing any feature template/form in Manager, Seeing a bunch of console error.
![image](https://github.com/user-attachments/assets/a85dd8a2-959e-4847-9922-18d1ae26008a)

### Expected Behavior

Feature template or Feature form should show up.

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=414bf95f3ca240faa98df7f5e0537ef9

1. Launch the app
2. Click on Create feature button
3. Observe the behavior, notice that it is not showing create feature template.

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen 

- This isreproduced in instat-app only, we are not able to reproduce this locally in the sample.
- Discussed this with John and we need to import few JS API modules in the instant apps code for manager 
 ![image](https://github.com/user-attachments/assets/72fe3277-a1f9-42d0-90a1-c09f81e8525f)

- Once @jmhauck adds these modules this should be resolved

**Comment by jmhauck** [comment]
Any time a new module is imported we need to add to the appropriate require file. I got Reporter updated when this PR came in but overlooked the fact that Manager would use create-feature as well. Should be good in dev tomorrow after https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/pull/10704

**Comment by azizaparveen** [comment]
This looks good
