### ISSUE TITLE
Full text search is not returning any records in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#893]
### Describe the bug

We have added support for full text search but when I am searching for text with in the fields that has full text index on, Manager is returning any value
![Manager_Fulltextsearch_notworking](https://github.com/user-attachments/assets/cffb857a-a25b-48de-9ab4-2dcd1a15e313)
![image](https://github.com/user-attachments/assets/78aa8398-2cf3-42f9-bf20-14a2ba62fe20)

### Expected Behavior

It should return the records that has the search text in it

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=7a4fec6a30364359ac5355b45d7854f0
1) launch the test app
2) Search any value within Request Category, Request Type and Status field
3) Notice the behavior.

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen 

We are not able to access the shared app, could ou please share the sample webmap or the app

**Comment by azizaparveen** [comment]
@sumitzarkar so sorry, please try now

**Comment by chris-fox** [comment]
This is resolved in DevEXT and the search is working in the test app provided.

**Comment by azizaparveen** [comment]
@sumitzarkar basic search is working as expected, noticed an issue, if I have multiple records selected and I would like to search within selection, Manager is searching among all records not the selection, but it is working fine when filter is applied, could you please look into that. I have few minor enhancements for this functionality and I will create a new issue for those. Thanks so much.

**Comment by azizaparveen** [comment]
@sumitzarkar any update on this issue?

**Comment by sumitzarkar** [comment]
@azizaparveen 

We have not found any complete solution which will work with the selection and the filters. We can discuss this on the call in detail.

**Comment by chris-fox** [comment]
We should discuss this user experience as well. Would users expect a search to only search within the selection set? I am not sure I would initially expect that.

In terms of the technical approach couldn't we compare the list of OIDs returned by the search with the list of OIDs from the selection set to find only the records from the search within the selection set?

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7
