### ISSUE TITLE
Editing on sybtype group layer is failing in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#896]
### Describe the bug

Reference issue : https://github.com/Esri/solutions-components/issues/846#issuecomment-2339696034
This fails in the edit-card code when the code tries to add an event on layer edit, and the on is not available on the layer instance. This seems to be a specific issue to this web map only and could be due to the subtype group layers
![image](https://github.com/user-attachments/assets/94ce1974-f11c-4f00-810d-52567bc4a88e)
![image](https://github.com/user-attachments/assets/3edfa8c3-bc19-42d6-bfda-8c66d333666f)

### Expected Behavior

Editing should not fail

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=6c07ac143e0741908d988bc9aa00f451
1) launch the app
2) Select a record from water Device layer
3) Click Edit button and update a value and click Update
4) Notice that Editing panel goes blank and console error shows up/

**Comment by jmhauck** [comment]
@azizaparveen this should be good now

**Comment by azizaparveen** [comment]
This looks good, verified in devext
