### ISSUE TITLE
Minor enhancements for search and filter functionalities in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#901]
### Describe requirements

- [x] Use the same border color as the toolbar for search box .
![image](https://github.com/user-attachments/assets/fe20cc88-6d64-4692-bfa9-3cbbd60052a4)

- [x] Use comma instead of the pipe in the suggestion text
![image](https://github.com/user-attachments/assets/13e3291e-41c4-49cd-be2c-ffcc02c7fd96)

- [x] Update total count number when search results return, currently it is showing all the record. 

- [x] Update total count number when filter results return, currently it is showing all the record.

**Comment by sumitzarkar** [comment]
@jmhauck 

- To show the current total number of features in the Table, we are planning to use the FeatureTable property size https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-FeatureTable.html#size
- However, when we try to use this property in the manager we get an error
 ![image](https://github.com/user-attachments/assets/bfaedd01-7b77-4ac2-aa24-1083ef2cd88d)
- Temporary we are typecasting it to any and it is working
**(this._table as any).size**

Please let us know if this property is planned to be deprecated or if we need to do something else to avoid this issue

**Comment by jmhauck** [comment]
@sumitzarkar it's a documented prop...I believe this is ok. 

When I look at the code it's doc'd but not decorated with `@property()` not sure why that is exactly but looks like it gets set internally.

![image](https://github.com/user-attachments/assets/3d71a2da-8fe0-4d27-97ba-66bf78411f3e)
 

I will run it by a PE on that team but doesn't seem like its anything to worry about.

**Comment by azizaparveen** [comment]
@sumitzarkar one more very minor change , the search box border looks a bit darker than other borders, can we use the same border color as the toolbar for search box as well?

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by azizaparveen** [comment]
This looks good in devext
