### ISSUE TITLE
Column menu is not opening and Show/hide column is not working at runtime in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#902]
### Describe the bug

Seeing some regression issues in manager

- [ ] Show/hide column is not working at runtime in Manager
![image](https://github.com/user-attachments/assets/06a9a173-5551-499f-ae7d-ef67e73a716d)

- [ ] Column menu is not opening when clicking on the ... button
![image](https://github.com/user-attachments/assets/cff7e500-3fad-4ae0-b285-a2161f71248b)

### Expected Behavior

It should show or hide when a field visibility is turned on/off at runtime

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=7a4fec6a30364359ac5355b45d7854f0

1) Launch the test app
2) Click on More menu
3) Try turning off any field, it uncheck the field in the menu but in the table not doing anything.
4) Also click on ... button on any column and notice that the menu is not opening and the More menu from the main toolbar is flushing.

**Comment by pratiksabale07** [comment]
@azizaparveen 

## Cause
> Show/hide column is not working at runtime in Manager
- When show/hide column from dropdown is clicked MouseEvent was generated
- Depending on that MouseEvent (target) value we were showing and hiding a column
- But we were not getting the updated value of the field from the dropdown
___
## Solution
- Move the _this._handleDocumentClick(e)_ function to the _componentDidRender_ to get the updated value
___
## Dev Checklist


Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | Yes  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on layer table | Column menu should show or hide when a field visibility is turned on/off at runtime

**Comment by azizaparveen** [comment]
Looks good in devext
