### ISSUE TITLE
Map view layout do not show the toolbar when there is single map in the create feature mode

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#905]
### Describe the bug

When clicking on Create feature from split view, the layout changes to map view, if there is only one map, the toolbar is not showing up.
![image](https://github.com/user-attachments/assets/c399fa2d-467a-4987-b54c-4021ea1f5890)
but I have another app that has multiple maps and toolbar shows up.

### Expected Behavior

The toolbar should be visible.

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=414bf95f3ca240faa98df7f5e0537ef9
1) Launch the test app
2) Click on the Create feature
3) Notice that the layout changes to map view layout
4) Notice that the tollbar flashes for a second but goes away after that.

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by pratiksabale07** [comment]
@azizaparveen 

## Cause
- When single map is present in the create feature mode and create feature button is clicked then full-height was getting added to the map and toolbar were not showing
___
## Solution
- When single map is present and create feature button is clicked then add calculated height to the map
___
## Dev Checklist


Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on map in map view layout |  When clicking on Create feature from split view, the layout changes to map view, if there is only one map, the toolbar should always shown

**Comment by azizaparveen** [comment]
Looks good in devext
