### ISSUE TITLE
Remove Create feature message in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#906]
### Describe requirements

There is the "Click on the map to add a point text" in the panel that essentially says the same thing. so it will be better if we remove this message all together.
![image](https://github.com/user-attachments/assets/d1c3867e-60fe-4814-b996-7888a1362dd0)

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen  

FYI...
https://github.com/Esri/solutions-components/issues/547#issuecomment-2391326320

**Comment by pratiksabale07** [comment]
@azizaparveen 

## Cause
- There was a message "Enter an address or click on the map to create a feature." which was shown while creating feature
- There was no condition added to hide that message 
___
## Solution
- Added condition to hide that message while creating the feature in manager
___
## Dev Checklist


Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impact while creating feature |  "Enter an address or click on the map to create a feature" should not shown in manager while creating feature

**Comment by azizaparveen** [comment]
Looks good in devext
