### ISSUE TITLE
Map picker does not show in table view in Manager

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#916]
### Describe the bug

When there are multiple maps, map picker is not showing in Table view layout
![image](https://github.com/user-attachments/assets/05d7d2c1-b2f1-40e2-b9a2-32088146cba5)

### Expected Behavior

Map picker should show up

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=3b707d16ab6649cdb6dac78f2982a6d5

1. Launch the app
2. Notice the app have two maps,
3. Change the layout to Table view
4. Notice that the map picker is not showing up.

**Comment by jmhauck** [comment]
@azizaparveen I just handled this this morning along with the other 2 issues regarding picker icons logged in the IA repo https://github.com/Esri/solutions-components/pull/915

**Comment by azizaparveen** [comment]
awesome John, thanks so much.

**Comment by azizaparveen** [comment]
This looks good in devext
