### ISSUE TITLE
Done button does not activate when open search distance on load is disabled and Search distance option is enabled  in PN

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#917]
### Describe the bug

Done button does not activate when "Open search distance when app loads" is disabled and Search distance option is enabled and used in PN 
![image](https://github.com/user-attachments/assets/019a164f-1eb3-47ee-a010-8cd3d9c564fa)
![image](https://github.com/user-attachments/assets/4271a8ab-9f65-4170-bed7-6dc37ccaf5b4)

### Expected Behavior

The button should activate when search feature is entered and a search distance is specified

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=abe5f5de20714a88976d818d783c18c1
1) Launch the App, 
2) Click on Create list button
3) Copy and paste SID-2 in the search box, **Do not select a value from the suggestions** this is a key step
4) Enable Search Distance,
5) Enter 1 in the Search distance input box.
6) Notice the Done button is still disabled and if you press Enter at the Seach distance input box after entering a value, it is still not enabled or execute the query
![Done_Pn](https://github.com/user-attachments/assets/699a60c7-d29a-4364-ac1e-2122998d46f7)

**Comment by jmhauck** [comment]
@azizaparveen this seems like standard functionality of the search widget. No search is being performed here unless you choose from the list or click enter when the search widget has focus. Same behavior is seen in the search widget sample:

https://developers.arcgis.com/javascript/latest/sample-code/sandbox/?sample=widgets-search-multiplesource

**Comment by azizaparveen** [comment]
@john thanks, will close it as expected behavior
