### ISSUE TITLE
Selection by layer features in PN is showing incorrect results

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#918]
### Describe the bug

I have a map that has 2 layers, USA cities and Counties, I wanted to select all the cities within Pinal County Az, I turned on Use layer features and select the USA-Counties layer , my input layer is US -Cities. PN selected one record in this scenario, actual number of records should be 4. Also the only selected record is not a city within Pinal County, AZ, it shows a city from New York
![image](https://github.com/user-attachments/assets/23fb6e17-1697-4907-979c-fd968c445696)
![image](https://github.com/user-attachments/assets/cd89706d-46aa-410c-bcf6-ccb0a2d8595e)

### Expected Behavior

It should select the cities intersected by Pinal county, Az. It works as expected in production

### Reproduction Steps & Sample

Test app in devext: https://solutions.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=8d56799e5a6b40aeade165e21e556761 (not working)
Test app in production: https://arcgis4localgov2.maps.arcgis.com/apps/instant/notification/index.html?appid=959f8fca10da419d81e629773c418c5d (working as expected)

1. Launch the test app
2. turn on Use layer features option
3. Click on Pinal county , AZ
4. Notice that only on feature is selected.
5. Now click Done and export the result to pdf, notice that the city is in somewhere NY.
6. Now if you go to List tab and click on the Edit button , it takes you to the city in New York.
![layerfeatures_pn](https://github.com/user-attachments/assets/887d2169-3852-43f4-94b4-493d7f942430)

**Comment by azizaparveen** [comment]
cc @ChryseMorales

**Comment by jmhauck** [comment]
@azizaparveen should be good to check this tomorrow

**Comment by azizaparveen** [comment]
looks good in devext

**Comment by azizaparveen** [comment]
This looks good in qa
