### ISSUE TITLE
Filter blue dot doens't appear after going back to layer list

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#919]
When we apply a filter on the layer, there is a blue dot next to the filter icon indicating there's a filter on it. It stays on as long as we're in the layer, but once we go back to the layer list, the filter is still applied but blue dot disappears. 

The same behavior is on production too but we'd like to change this. 

**Filter is on the polygon layer.** 

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=1d87c0739da84c63822e7eaf68e7d65b

![image](https://github.com/user-attachments/assets/456820c8-8cc6-4ea2-a264-dbc239b1764e)

**Filter still applied and it shows only 1 feature**
![image](https://github.com/user-attachments/assets/82a2d44c-444f-4e02-9d60-9e1c61f2a801)

**No blue dot**
![image](https://github.com/user-attachments/assets/d2d33d64-d780-42f2-a38c-f9fd9caf33b3)

**Comment by pratiksabale07** [comment]
@skrishn
## Cause
- While opening the feature list the filter active state was getting reset
___
## Solution
- When the filter is applied to the layer maintain the filter's active state.
- While changing the layer reset the filter active state applied to the previous layer, so the filter's active state can be maintained for the newly selected layer.
___
## Dev Checklist

Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on runtime | The blue dot indicator should be maintained when a filter is applied, and the applied filter should only be reset when switching to another layer.
