### ISSUE TITLE
Sometimes, profile image or profile initial doesn't come through

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#938]
I noticed the profile image or profile initial doesn't come through when the toggle is on to display user images. The issue was reported by other PE's but they weren't able to continuously reproducible. I finally got a repro case.  

https://defense-test.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=7a171a33c52947149c004bf0f5ce7844

![image](https://github.com/user-attachments/assets/aad72812-4f33-4b94-ac7f-9956da0167a7)

I'll share creds separately.

**Comment by skrishn** [comment]
@sumitzarkar another related issue encountered is it displayed initials instead of profile image, but the problem wasn't reproducible after switching the image. The image was shared publicly. I'm wondering if there are any size restrictions, but when I used the same image in my org I wasn't able to repro it. 

![image](https://github.com/user-attachments/assets/a9c55355-17d9-4cc9-92c0-41f5a6a69246)

**Comment by sumitzarkar** [comment]
@skrishn 

> https://defense-test.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=7a171a33c52947149c004bf0f5ce7844
> ![image](https://github.com/user-attachments/assets/aad72812-4f33-4b94-ac7f-9956da0167a7)

- We can reproduce this case
- When we are getting the creator field from the edit field infos we change it to lowercase to match the key, as in some cases we have differences in the casing
 ![image](https://github.com/user-attachments/assets/7042dcde-f871-45ae-aa85-38947b717319)
- To resolve this we will check the field with different cases like complete lower, complete upper, and the fieldName as it is
- We have implemented this and it is working, we will deliver this after our testing in the next code drop
  ![image](https://github.com/user-attachments/assets/42f441ed-0373-4557-a500-c3dda56e6db6)


> https://github.com/Esri/solutions-components/issues/938#issuecomment-2400760035

- We are not able to reproduce this case.

**Comment by pratiksabale07** [comment]
@skrishn
## Cause
- https://github.com/Esri/solutions-components/issues/938#issuecomment-2402337897
___
## Solution
- https://github.com/Esri/solutions-components/issues/938#issuecomment-2402337897
___
## Dev Checklist

Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on comment list | If user information is valid/accessible then profile image or profile initials should always be displayed

**Comment by skrishn** [comment]
@sumitzarkar I see the same issue on newly created apps. The one I provided earlier seems to be fixed.
https://defense-test.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=b24caf22afcc46b897e9582645e6c25e

**Comment by skrishn** [comment]
@sumitzarkar I see the same issue with newly created app https://defense-test.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=e4c99d10edc64d7baab600fa714237f4. The issue seem fixed with the app I provided earlier.

**Comment by sumitzarkar** [comment]
@skrishn 

> https://defense-test.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=e4c99d10edc64d7baab600fa714237f4. 

In this app we are not getting the editFiledInfos and creator field hence all the comments are shown as anonymous

![image](https://github.com/user-attachments/assets/79466b74-b540-4fb7-be8c-f1e75f2d9565)

**Comment by skrishn** [comment]
> @skrishn
> 
> > https://defense-test.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=e4c99d10edc64d7baab600fa714237f4.
> 
> In this app we are not getting the editFiledInfos and creator field hence all the comments are shown as anonymous
> 
> ![image](https://private-user-images.githubusercontent.com/9443956/376198898-79466b74-b540-4fb7-be8c-f1e75f2d9565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTYzMjgsIm5iZiI6MTcyODkxNjAyOCwicGF0aCI6Ii85NDQzOTU2LzM3NjE5ODg5OC03OTQ2NmI3NC1iNTQwLTRmYjctYmU4Yy1mMWU3NWYyZDk1NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTQyNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVkMDQ1NjQ0YzBkYzU3YmFlYmFkNTQxM2UxMTljOWU1MjYxMTljMzY5MTA3MmRmM2U5YjRmM2Q2OWJlYjJhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uzWe4z4okjN23Gu-ytCivEbCNBTmBzUBLEB0KS8qOs4)

I used the wrong data by mistake. thanks for finding it out.
