### ISSUE TITLE
App is using second table instead of first for commenting

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#941]
Related to this issue? https://github.com/Esri/solutions-components/issues/810

The layer has two tables and it uses the second table instead of the first. 

https://defense-test.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=1229e0382afe4a59bafd3cbb2f5c21a8

https://defense-test.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=7d51d3c9cdb041338b852eb2cf115dd5

![image](https://github.com/user-attachments/assets/04c60038-8671-4785-a680-e3ed360aba78)

**Map viewer**

![image](https://github.com/user-attachments/assets/ce51786c-d163-4f77-b93d-97f0b092e76c)

**Production app with the same data uses the first table: comments table**

https://localdeployment.maps.arcgis.com/apps/instant/reporter/index.html?appid=f9030a8b8a5e44d88ab5bb02bb9c3842

https://localdeployment.maps.arcgis.com/apps/mapviewer/index.html?webmap=d5e8a36c031b47e0badfddbe2670dcb2

![image](https://github.com/user-attachments/assets/a8c7d6d8-2406-46c3-ab34-d48e0035b774)

**Comment by sumitzarkar** [comment]
@skrishn 

We can reproduce this and we have fixed this and will deliver it in the next code drop.

**Comment by sumitzarkar** [comment]
## Cause
- We updated the code to support the first valid table when the layer has multiple tables https://github.com/Esri/solutions-components/issues/810#issuecomment-2368589509
- In this, we were creating the array of relationships id and then filtering all the tables from the map to check if the table is present in the map
- As we were filtering on all the layers we were getting tables sequence as in the map and not according to the relationship

___

## Solution
- Update the code to check if the table present in the map for each relationship sequentially 

___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impact | - Test Commenting functionality <br> Test for layers with multiple tables
Impacted ticket |   #810
___
