### ISSUE TITLE
Filter panel keeps loading on applying dropdown filter

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#947]
I applied drop-down filter on the point layer, and the filter panel keeps loading non-stop. I couldn't repro the behavior with other filter types on the same app, and also on drop-down filter on Nearby template

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=1d87c0739da84c63822e7eaf68e7d65b

**Comment by sumitzarkar** [comment]
@skrishn 

We can reproduce this issue and will deliver it in the next code drop

**Comment by pratiksabale07** [comment]
@skrishn 
## Cause
- When the filter is applied we were storing the _filterInitState_ and _filterUrlParams_ states to maintain the state of the filter while opening the filter list.
![image](https://github.com/user-attachments/assets/91565e00-b3be-4dea-9463-46ac97498842)
- When the above states got changed our component was getting rerendered and calling the _restoreFilters_ method then again filter was getting updated so this was getting repeated
- So, the Filter panel keeps loading on applying the dropdown filter
 
___
## Solution
- On applying the filter we will not store the _filterInitState_ then our _restoreFilters_ method will not get called.
- After coming back from the filter list we will store the value of _filterInitState_.
___
## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No  |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on runtime | After applying the filter to the layer, map and the side panel should display updated features.
