### ISSUE TITLE
Feature don't render on the map after applying filter on a layer and navigating to other layers.

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#948]
https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=1d87c0739da84c63822e7eaf68e7d65b

1. Go to Poly layer and apply filter. Notice the filtered feature is rendered. 
2. Go to another layer and choose a feature, it doesn't render on the map it but the popup details appear on the panel.
3.  Go back to poly layer, and notice the filter is reset but no feature is rendered even as we choose the feature from the panel.

The acceptable behavior is to render other layer's features when navigating after applying filter on a particular layer. The filter set on the layer shouldn't reset itself as we navigate to other layers.

**Comment by sumitzarkar** [comment]
@skrishn 

We are able to reproduce this and will deliver it in next code drop

**Comment by pratiksabale07** [comment]
@skrishn 
## Cause
- We have a validLayers and nonVisibleValidLayers array to keep valid and non-valid layers separately.
- On opening a layer we were disabling the visibility of other layers to show only one layer on the map (Enabling visibility when navigating to the layer list).
- When the filter is applied we refresh the layer list to update features count.
- On refreshing the layer, we were getting a callback where again layers were filtered but other layer visibility is disabled that is why they are getting added in the nonVisibleValidLayers array.
- Hence some features don't get rendered on the map after applying the filter.
___
## Solution
- While navigating to the layer list update the layer visibility state and then refresh the layer list.
___
## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact areas |- layer list  </br> - map
Impact on runtime | Appropriate features should render on the map after applying the filter on a layer and navigating to other layers.
