### ISSUE TITLE
Remove the blue highlight border around like and dislike button

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#962]
After clicking the like and dislike button, the blue border stays on until clicked somewhere. Can we remove the border after some time?

![image](https://github.com/user-attachments/assets/dc39afa9-9877-4894-bd7b-6364d10e9887)

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=c51914bdd9974e1cba2cb1bd1c5dec07

**Comment by skrishn** [comment]
@sumitzarkar Depends on loe, we can plan the timeline. It's not high impact

**Comment by sumitzarkar** [comment]
@skrishn 

As discussed on the call we don't see any solution as of now since this is the default behavior of the button component. Also, we may need that highlighted border for 508 accessibility.

**Comment by chris-fox** [comment]
This is default calcite behavior for accessibility. We should not modify this experience.

**Comment by skrishn** [comment]
@sumitzarkar thanks. I'll close this.
