### ISSUE TITLE
Instant app filter component breaks after force reset when slider is present in the filter list UI

### ISSUE THREAD

**Issue by sumitzarkar** [Esri/solutions-components#965]
### Describe the bug

- When slider is present in the Filter list UI and if we apply filters and reset it filter component is breaking:
![image](https://github.com/user-attachments/assets/045ec779-5fd8-4a08-b647-b45b967ceb1c)

### Expected Behavior

Instant app filter component should work after force reset when slider is present in the filter list UI

### Reproduction Steps & Sample

[instant-apps-filter-list-1.zip](https://github.com/user-attachments/files/17411507/instant-apps-filter-list-1.zip)

**Comment by sumitzarkar** [comment]
FYI - @skrishn

**Comment by jmhauck** [comment]
@sumitzarkar in your example the view property was not getting set correctly.

[instant-apps-filter-list.zip](https://github.com/user-attachments/files/17478744/instant-apps-filter-list.zip)

**Comment by sumitzarkar** [comment]
@jmhauck 

After updating the sample to resolve the view issue we still see the issue with force filter reset

**Comment by jmhauck** [comment]
updated IAC here https://github.com/Esri/solutions-components/commit/adaed58c3c95d37bd211e358196de14d702350f5
