### ISSUE TITLE
Filters set to be on by default are not being honored

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#982]
### Describe the bug

Filters are configured to be on by default when the app is opened.

Upon opening the app the blue dot to indicate filters are on is not present and the records in the table are not filtered.
![image](https://github.com/user-attachments/assets/cbd3bf57-7514-4f95-982b-a91e9e5613eb)

When I click the Filters button it shows the filters are checked on but as I mentioned above the records are not filtered
![image](https://github.com/user-attachments/assets/60719b8a-9805-4e7c-89ec-a77f96b4cb90)

If I turn the filters off and then check them back on the records get filtered and the blue dot indicating filters are on is present on the Filter button.

### Expected Behavior

When a filter is configured to be on by default when an app is opened, the expected behavior is:

- Blue dot on the Filter button is present to indicate a filter is active
- The records in the table are filtered

### Reproduction Steps & Sample

1. In Devext, deploy the Lead Service Line Inventory solution
2. Load data into the ServiceLine feature service
3. [ServiceLineSample.gdb.zip](https://devtopia.esri.com/WebGIS/solutions-development-support/files/57352/ServiceLineSample.gdb.zip)
4. Go to the Lead Service Line Replacement Manager item page and click View
5. Look at the Filters button at the top of the table and notice that the blue dot is not present.
6. Look at the number of records at the bottom and notice there are 7227 (there should be 5785)
7. Click the Filters button, the boxes are checked on for Needs Replacement, Scheduled Replacement, and Null (which is correct) but the records didn't filter.
8. Uncheck and recheck the boxes and the records in the table do filter and the blue dot is present on the Filter button.

### Other Relevant Info

Critical - emergency! needs patching
Any solution using Filters on by default in the Manager app will be impacted.

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by sumitzarkar** [comment]
@azizaparveen 

- We can reproduce this issue in DevExt
-  We tried reproducing the same issue in production with Manager App and we are not able to reproduce, so this should be an issue introduced in the recent developments.
- We tried reproducing this with other instant apps on **devExt** which uses the instant-app-filter-list component. We can reproduce this issue in the Reporter, NearBy, and Manager apps.
- This seems to be an issue with the instant-app-filter-list component itself. Where if the filter is active on load the controls like checkbox/dropdown etc. are reflecting them but the definition expression is not updated on the layer

Could you please check this with the instant-app team if any changes are required from our end to fix this?

**Comment by azizaparveen** [comment]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10956

**Comment by azizaparveen** [comment]
Devext test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=7a4fec6a30364359ac5355b45d7854f0, request layer has filter set up to be activated  on load
Qa test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=7a4fec6a30364359ac5355b45d7854f0, Corvallis Structure map -> Corvallis School has a filter set up to be activated on load

**Comment by azizaparveen** [comment]
This looks good in both qa and dev
