### ISSUE TITLE
App displays cover page when switched from arabic to english using language switcher

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#988]
https://localgovqa.mapsqa.arcgis.com/apps/instant/reporter/index.html?appid=64b55174de0a4c2a9b933099df316f02

I switched languages using the language switcher and only when switching from Arabic to English it displays the cover page every time. Is the behavior/bug due to right to left switch? It doesn't provide a smooth experience when a language is switched.

**Comment by skrishn** [comment]
I'm able to repro with other languages too but only occasionally.

**Comment by sumitzarkar** [comment]
@skrishn 

- This is handled in the instant app and we don't have any control from reporter-component on this.

@jmhauck - Any input on this?

**Comment by skrishn** [comment]
Tracking it here https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10946

**Comment by skrishn** [comment]
Fix is in dev. Verified it.
