### ISSUE TITLE
Editing time field opens up the interface behind the table so it is only partially visible

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#992]
### Describe the bug

Editing time field opens up the interface behind the table so it is only partially visible
![image](https://github.com/user-attachments/assets/4913a483-a3b9-4fcc-8635-bcac12b04f77)

### Expected Behavior

Time field editing interface should be visible like the date field

### Reproduction Steps & Sample

Test app: https://solutionsqa.mapsqa.arcgis.com/apps/instant/manager/index.html?appid=b26fc0fb0de54f7d912a296a268148b7
1) Launch the test app
2) Select a record
3) Click Edit button 
4) Navigate to Rosolved on field and click on the time field and observe the behavior

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by azizaparveen** [comment]
Devext app for testing: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=7a4fec6a30364359ac5355b45d7854f0

**Comment by sumitzarkar** [comment]
@jmhauck 

- To fix this issue we need to add z-index = 1 to the parent div of the side container
- After adding this z-index we are observing an issue with the delete dialog not showing the complete modal background, it is showing the background only in the area of the table.

![image](https://github.com/user-attachments/assets/29cf1868-fd22-467f-beba-b2236d4d1a2f)

Please check and suggest if you see any alternate approach to fix this
